gazebo-tooling/release-tools

jenkins-scripts/dsl/_configs_/OSRFBase.groovy, jenkins-scripts/lib/windows_library.bat
This has already been migrated to github,
so use this one instead of bitbucket.
=> Use ignition-tooling/gazebodistro

jenkins-scripts/dsl/ignition.dsl
Changes to ignition to use the new classes and CI integration.
=> Port ignition to GitHub CI

jenkins-scripts/dsl/ignition.dsl
In #169, we missed a few places where `default` needs to be `master`.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition&build=955)](https://build.osrfoundation.org/job/_dsl_ignition/955/) https://build.osrfoundation.org/job/_dsl_ignition/955/
~~~
Added items:
GeneratedJob{name='ignition_cmake-ci-master-xenial-amd64'}
GeneratedJob{name='ignition_cmake-ci-master-bionic-amd64'}
GeneratedJob{name='ignition_common-ci-master-xenial-amd64'}
GeneratedJob{name='ignition_common-ci-master-bionic-amd64'}
GeneratedJob{name='ignition_fuel-tools-ci-master-xenial-amd64'}
GeneratedJob{name='ignition_fuel-tools-ci-master-bionic-amd64'}
GeneratedJob{name='ignition_gazebo-ci-master-xenial-amd64'}
GeneratedJob{name='ignition_gazebo-ci-master-bionic-amd64'} …
=> ignition.dsl: default branch -> master

jenkins-scripts/tools/git_delete_closed_hg_branches.bash
Sorry, merged #177 too quickly. It's missing the target directory.
=> Delete git branches: add missing hg_tmp

jenkins-scripts/dsl/ignition_collection.dsl
testing: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition_collection&build=184)](https://build.osrfoundation.org/job/_dsl_ignition_collection/184/) https://build.osrfoundation.org/job/_dsl_ignition_collection/184/
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_citadel-ci-default-homebrew-amd64&build=4)](https://build.osrfoundation.org/job/ignition_citadel-ci-default-homebrew-amd64/4/) https://build.osrfoundation.org/job/ignition_citadel-ci-default-homebrew-amd64/4/
=> ignition_collection.dsl: use github

jenkins-scripts/docker/lib/_ros_setup_buildsh.bash, jenkins-scripts/lib/windows_library.bat
Suggestion by @dirk-thomas to improve the console log.
=> Use console_cohesion instead of console_direct for colcon logs

jenkins-scripts/dsl/gazebo_ros_pkgs.dsl
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_gazebo_ros_pkgs&build=632)](https://build.osrfoundation.org/job/_dsl_gazebo_ros_pkgs/632/)
New items:
```
GeneratedJob{name='ros2_gazebo11_pkgs-install_pkg_dashing-bionic-amd64'}
GeneratedJob{name='ros2_gazebo11_pkgs-ci-pr_any_dashing-bionic-amd64'}
GeneratedJob{name='ros2_gazebo11_pkgs-ci-default_dashing-bionic-amd64'}
GeneratedJob{name='ros2_gazebo11_pkgs-install_pkg_eloquent-bionic-amd64'}
GeneratedJob{name='ros2_gazebo11_pkgs-ci-pr_any_eloquent-bionic-amd64'}
GeneratedJob{name='ros2_gazebo11_pkgs-ci-default_eloquent-bionic-amd64'}
```
* Dashing Gazebo11:
* install job [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros2_gazebo11_pkgs-install_pkg_dashing-bionic-amd64&build=1)](https: …
=> Add Dashing and Eloquent to gazebo_ros_packages CI for Gazebo 11

bloom/ros_ign_bridge-release.py.bash, jenkins-scripts/dsl/ros1_ign_bridge.dsl
DSL run: https://build.osrfoundation.org/job/_dsl_ros1_ign_bridge/7
```
Added items:
GeneratedJob{name='ros-ign-gazebo-bloom-debbuilder'}
Existing items:
GeneratedJob{name='ros-ign-bloom-debbuilder'}
GeneratedJob{name='ros-ign-bridge-bloom-debbuilder'}
GeneratedJob{name='ros-ign-gazebo-demos-bloom-debbuilder'}
GeneratedJob{name='ros-ign-image-bloom-debbuilder'}
GeneratedJob{name='ros-ign-point-cloud-bloom-debbuilder'}
```
=> Add ros_ign_gazebo package to 

jenkins-scripts/dsl/_configs_/OSRFBrewInstall.groovy, jenkins-scripts/dsl/ignition.dsl, jenkins-scripts/lib/project-install-homebrew.bash
This adds jobs for testing installation of homebrew bottles for supported ignition versions. I generated the jobs with the following dsl build:
* https://build.osrfoundation.org/job/_dsl_ignition/976/
~~~
Added items:
GeneratedJob{name='ignition_cmake1-install-homebrew-bottle'}
GeneratedJob{name='ignition_cmake2-install-homebrew-bottle'}
GeneratedJob{name='ignition_common1-install-homebrew-bottle'}
GeneratedJob{name='ignition_common2-install-homebrew-bottle'}
GeneratedJob{name='ignition_common3-install-homebrew-bottle'}
GeneratedJob{name='ignition_fuel-tools1-install-homebrew-bottle'}
GeneratedJob{name='ignition_fuel-tools2-install-homebrew-bottle'}
GeneratedJob{name='ignition_fuel-tools3-install-homebrew-bottle'}
GeneratedJob{name='ignition_fuel-tools4-install-homebrew-bottle'} …
=> ignition.dsl: add brew install bottle jobs

jenkins-scripts/lib/_homebrew_cleanup.bash, jenkins-scripts/lib/homebrew_bottle_creation.bash
Something is broken about the ruby configuration on our build machines, so we have been using this branch for a while that removes and reinstalls the vendored ruby used by homebrew. When calling `brew audit` or `brew style`, the following error occurs without this branch:
~~~
==> brew audit osrf/simulation/ignition-common3 --online
==> FAILED
Error: cannot load such file -- regexp_parser
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.85.0/lib/rubocop.rb:8:in `<top (required)>' …
=> Clean up ruby when building homebrew bottles

jenkins-scripts/docker/lib/boilerplate_prepare.sh
Before removing it completely in #229, I'm go to merge this to help to fixing #230
=> Default GITHUB variable to True

one-line-installations/gazebo.sh
```sh
$ echo "$(. /etc/lsb-release && echo "$DISTRIB_ID")"
Pop
```
=> Add Pop!OS (essentially ubuntu)

jenkins-scripts/lib/repository_uploader.bash
For source packages we need to check versions not depending on the DISTRO nor the revision number since they contain mostly orig tarball (with sources) and other metadata common to all platforms.
Failing here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=repository_uploader_ng&build=14607)](https://build.osrfoundation.org/view/All/job/repository_uploader_ng/14607/)
With this branch: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=repository_uploader_ng&build=14608)](https://build.osrfoundation.org/view/All/job/repository_uploader_ng/14608/)
=> Fix DSC comparison in repository_uploader

jenkins-scripts/docker/ign_gazebo-compilation.bash, jenkins-scripts/lib/dependencies_archive.sh
Forgot to add physics3 for Gazebo in the original bump
=> Use sdf10 in physics3 dependencies_archive

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy
Need extra refs to be able to work fine. I'm testing it here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_gui-pr-win&build=328)](https://build.osrfoundation.org/view/All/job/ign_gui-pr-win/328/) . I've also include the instructions in the description of the parameter
=> Prepare pr_any jobs to be launched maually

jenkins-scripts/lib/dependencies_archive.sh
dependency from pending ign-gui plotting PR  https://github.com/ignitionrobotics/ign-gui/pull/89/files#diff-4253619161160de146e5ae81dcd1886aR23
Signed-off-by: claireyywang <22240514+claireyywang@users.noreply.github.com>
=> add qml platform dependency

bloom/release-bloom.py, jenkins-scripts/dsl/_configs_/Globals.groovy, jenkins-scripts/dsl/gazebo_ros_pkgs.dsl, jenkins-scripts/lib/dependencies_archive.sh
* Make Foxy and Rolling supported
* Set Galactic as the next one coming up
=> 👩‍🌾 Foxy and Rolling supported, Galactic staged

jenkins-scripts/dsl/ignition.dsl, jenkins-scripts/dsl/ignition_collection.dsl
Also use `main` branch in `ignition_collection.dsl`.
=> ignition.dsl: use main branch instead of master

jenkins-scripts/gazebo-default-devel-windows7-amd64.bat, jenkins-scripts/ign_transport-default-devel-windows-amd64.bat, jenkins-scripts/lib/colcon-default-devel-windows.bat, jenkins-scripts/sdformat-default-devel-windows-amd64.bat
This should fix https://build.osrfoundation.org/job/sdformat-ci-pr_any-windows7-amd64/1593/console that was introduced in #314 
Tested [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-pr_any-windows7-amd64&build=1594)](https://build.osrfoundation.org/job/sdformat-ci-pr_any-windows7-amd64/1594/)
=> Do not use python3 in Windows (yet)

jenkins-scripts/dsl/_configs_/OSRFLinuxABIGitHub.groovy, jenkins-scripts/dsl/_configs_/OSRFLinuxBase.groovy, jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkgBase.groovy
pull #324 did not contain my latest local changes on that branch, sorry. 
These changes run on all dsl fixes the problem:
* Example on Ignition [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition&build=1055)](https://build.osrfoundation.org/job/_dsl_ignition/1055/)
=> Fix limitation of 200 builds (pull #324)

jenkins-scripts/lib/_homebrew_github_setup.bash
It was moved to the brew organization. I've tested it here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_pull_request_updater&build=754)](https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/754/)
=> Update install URL for LinuxBrew

README.md
Includes part of the README from #333.
Document the release process, step-by-step.
=> Add README with release instructions

README.md
* Watch debbuilder jobs to ensure they don't fail.
* Add "build bottle" comment to osrf/homebrew-simulation PR
=> README: more release instructions

jenkins-scripts/docker/ign_fuel-tools-compilation.bash, jenkins-scripts/docker/ign_gazebo-compilation.bash, jenkins-scripts/docker/ign_gui-compilation.bash, jenkins-scripts/docker/ign_launch-compilation.bash, jenkins-scripts/docker/ign_sensors-compilation.bash, jenkins-scripts/docker/ign_transport-compilation.bash
Addresses https://github.com/ignition-tooling/release-tools/issues/362
=> Bump in edifice: ign-msgs7

jenkins-scripts/dsl/brew_release.dsl
We already have a build machine with catalina: https://build.osrfoundation.org/computer/mac-t1000.catalina/
I'll test this before merging.
=> brew_release.dsl: build bottles for catalina

jenkins-scripts/docker/ign_gazebo-compilation.bash
Part of https://github.com/ignitionrobotics/ign-gazebo/issues/568
=> ign-gazebo5: depend on ign-utils1

jenkins-scripts/docker/ign_common-compilation.bash
Part of [ign-common #161](https://github.com/ignitionrobotics/ign-common/issues/161), implementation derived from #387
=> Add utils1 dependency for ign-common4

jenkins-scripts/lib/repository_uploader.bash
The PR changes a bit the way we handle source package (`.dsc` files) version in the repository. There is one source package per distribution (although they share the `.orig` tarball file).
The PR changes the check to use `list` instead of `ls` which allows per distro listing of source packages and remove the machinery in place before to compare across distributions.  I think that this PR can close #267.
I've tested it several times during the last days to upload packages to the testing repository. The rotation has eaten the logs, I'll try to get one in the next days.
=> Permit multiple source packages one per distro

jenkins-scripts/dsl/gazebo.dsl, jenkins-scripts/dsl/ignition_collection.dsl, jenkins-scripts/dsl/sdformat.dsl
https://github.com/osrf/sdformat/issues/531
=> Use osrf/sdformat main branch instead of master

jenkins-scripts/dsl/ignition.dsl
it has been disabled since #422 was merged
=> ignition.dsl: re-enable ign-utils1-debbuilder

jenkins-scripts/dsl/ignition_collection.dsl
=> Bumps in fortress : ign-msgs8

jenkins-scripts/dsl/ignition_collection.dsl
=> Bumps in fortress : ign-rendering6

jenkins-scripts/dsl/ignition_collection.dsl
=> Bumps in fortress : ign-transport11

jenkins-scripts/dsl/ignition_collection.dsl
=> Bumps in fortress : ign-launch5

jenkins-scripts/dsl/ignition_collection.dsl
=> Bumps in fortress : ign-gazebo6

.github/ISSUE_TEMPLATE/release_collection.md
Viewable at https://github.com/ignition-tooling/release-tools/issues/new/choose
Signed-off-by: Steve Peters <scpeters@openrobotics.org>
=> fix typo in issue template

jenkins-scripts/lib/dependencies_archive.sh
Fix https://github.com/ignition-tooling/release-tools/pull/478#discussion_r661058750 while #462 is still under testing
---
https://github.com/osrf/buildfarmer/issues/207
=> 👩‍🌾 Fix Xenial CI for now: don't install ogre2

jenkins-scripts/dsl/ignition.dsl, jenkins-scripts/dsl/ignition_collection.dsl, jenkins-scripts/ign_common-default-devel-windows-amd64.bat
=> Update ign-common to use colcon

jenkins-scripts/ign_rendering-default-devel-windows-amd64.bat
Depending on `ign-math6-eigen3` from 
https://github.com/ignitionrobotics/ign-rendering/pull/420
https://github.com/ignition-tooling/release-tools/issues/459
=> ign-rendering depend on Eigen

terminal-dashboard/table.bash
=> Release dashboard: support pre-releases and nightlies

jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/ignition-tooling/release-tools/issues/545
=> Bumps in garden : ign-gui7

jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/ignition-tooling/release-tools/issues/545
=> Bumps in garden : ign-gazebo7

terminal-dashboard/_dashboard_lib.sh, terminal-dashboard/table.bash, terminal-dashboard/unreleased.bash
It has some duplication from [table.bash](https://github.com/ignition-tooling/release-tools/blob/master/terminal-dashboard/table.bash) that would be nice to remove eventually.
Example output:
```
$ bash unreleased.bash citadel
https://github.com/ignitionrobotics/ign-cmake/compare/ignition-cmake2_2.9.0...ign-cmake2
https://github.com/ignitionrobotics/ign-math/compare/ignition-math6_6.9.2...ign-math6
https://github.com/ignitionrobotics/ign-tools/compare/ignition-tools_1.4.1...ign-tools
https://github.com/ignitionrobotics/ign-common/compare/ignition-common3_3.14.0...ign-common3
https://github.com/ignitionrobotics/ign-msgs/compare/ignition-msgs5_5.8.1...ign-msgs5
https://github.com/ignitionrobotics/ign-transport/compare/ignition-transport8_8.2.1...ign-transport8 …
```
=> Script to help check unreleased changes for each collection

terminal-dashboard/_dashboard_lib.sh
In #543 we lost the metapackages
=> Re-add collection to dashboard lib

jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/ignition-tooling/release-tools/issues/545
=> Bumps in garden : ign-rendering7

release-repo-scripts/bump_dependency.bash
Follow-up to this comment thread: https://github.com/ignitionrobotics/ign-garden/pull/3#discussion_r751504628
Used to generate https://github.com/ignitionrobotics/ign-garden/pull/4
=> bump_dependency.bash: use main in collection.yaml

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash, jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash, jenkins-scripts/lib/windows_library.bat, jenkins-scripts/tools/detect_ci_matching_branch.py
=> Add python tool to check for matching CI branches

jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/ignition-tooling/release-tools/issues/554
=> Bumps in garden : ci_matching_branch/bump_garden_ign-fuel-tools8

jenkins-scripts/docker/sdformat-abichecker.bash, jenkins-scripts/tools/detect_ci_matching_branch.py
Needed by ignitionrobotics/sdformat#780
=> sdformat-abichecker: set GZDEV_PROJECT_NAME

jenkins-scripts/docker/sdformat-compilation.bash
=> sdformat: again stop -DUSE_INTERNAL_URDF=ON

jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/ignition-tooling/release-tools/issues/574
=> Bumps in garden : ci_matching_branch/bump_garden_ign-math7

jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/ignition-tooling/release-tools/issues/574
=> Bumps in garden: ign-physics6

jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/ignition-tooling/release-tools/issues/574
=> Bumps in garden: sdformat13

jenkins-scripts/dsl/sdformat.dsl
* Reverting https://github.com/ignition-tooling/release-tools/pull/605 now that 10.7.0 is out
* Part of https://github.com/ignition-tooling/release-tools/issues/600
=> sdformat.dsl: re-disable sdf10

jenkins-scripts/dsl/sdformat.dsl
Needed by https://github.com/ignition-tooling/release-tools/issues/574
=> Enable sdformat13-debbuilder job

jenkins-scripts/docker/ign_msgs-compilation.bash
Attempt to fix build regression in the `ign_msgs` Linux jobs.
https://build.osrfoundation.org/job/ignition_msgs-ci-pr_any-ubuntu_auto-amd64/736/console
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
=> Pin activesupport to version 6.1.4.4

release-repo-scripts/bump_major_version.bash, release-repo-scripts/changelog_spawn.sh, release-repo-scripts/new_ignition_release_repos.bash
For those of us who don't use bash, makes things work smoother.
=> Fix shebangs on release scripts

jenkins-scripts/docker/lib/debbuild-base.bash
Improve the workaround for #644 implemented before in #643  
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-launch6-debbuilder&build=208)](https://build.osrfoundation.org/job/ign-launch6-debbuilder/208/)
=> Wait until 5min in nightly generation to workaround race conditions

jenkins-scripts/dsl/ignition_collection.dsl
Part of https://github.com/ignition-tooling/release-tools/issues/644
=> Build ign-utils1 nightly before ign-math7

docs/BUILDFARM_NODES.md
Documenting the buildfarm node labels being used in different replaces inside this repository.
=> Add documentation about buildfarm nodes (node labels)

terminal-dashboard/unreleased.bash
* I broke anything with `ign-` on https://github.com/ignition-tooling/release-tools/pull/664  🤦🏽‍♀️
=> Fix unreleased script again

jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/ignition-tooling/release-tools/issues/685
=> Bumps in garden : ign-utils2

jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/ignition-tooling/release-tools/issues/685
=> Bumps in garden : ign-cmake3

jenkins-scripts/docker/ign_plugin-compilation.bash
* Same as #688 
* Needed by https://github.com/ignition-tooling/release-tools/issues/685
=> Fix GZDEV_PROJECT_NAME for ign-plugin2

.github/ISSUE_TEMPLATE/eol_collection.md
Some updates after using the template on
* https://github.com/ignition-tooling/release-tools/issues/600 
* https://github.com/ignition-tooling/release-tools/issues/655
=> Update EOL template after using it for Dome and Edifice

jenkins-scripts/dsl/ignition_collection.dsl
=> Bumps in garden : ign-plugin2

jenkins-scripts/dsl/ignition_collection.dsl
=> Bumps in garden : ign-tools2

jenkins-scripts/lib/dependencies_archive.sh
=> Deprecate Dependencies Archive for ign-tools installs

jenkins-scripts/lib/dependencies_archive.sh
=> Deprecate Dependencies Archive for ign-plugin installs

jenkins-scripts/lib/dependencies_archive.sh
=> Depreciate Dependencies Archive for ign-rendering4 installs

jenkins-scripts/ign_tools-default-devel-windows-amd64.bat
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
=> Fix build regression on ign-tools1 for windows on CI

jenkins-scripts/dsl/extra.dsl
DSL [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_extra&build=516)](https://build.osrfoundation.org/job/_dsl_extra/516/)
Job running https://build.osrfoundation.org/job/ogre-2.3-debbuilder/
=> Generate ogre-2.3 debbuilder

source-repo-scripts/release_summary.bash
Used to generate this announcement:
https://community.gazebosim.org/t/new-releases-2022-06-13-fortress-citadel/1463
Also fixed handling fuel-tools
=> Update release summaries for gz / Gazebo

.github/ISSUE_TEMPLATE/bump_libraries.md, .github/ISSUE_TEMPLATE/eol_collection.md, .github/ISSUE_TEMPLATE/new_collection.md, .github/ISSUE_TEMPLATE/release_collection.md, README.md, bloom/release-bloom.py, jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash, jenkins-scripts/docker/lib/gazebo-base-default.bash, jenkins-scripts/dsl/ignition.dsl, jenkins-scripts/dsl/ignition_collection.dsl, jenkins-scripts/dsl/ros1_ign_bridge.dsl, jenkins-scripts/lib/gazebo-base-windows.bat, jenkins-scripts/lib/gazebo9_10-base-windows.bat, jenkins-scripts/lib/sdformat-base-windows.bat, jenkins-scripts/lib/windows_library.bat, release-repo-scripts/bump_major_version.bash, release-repo-scripts/new_ignition_release_repos.bash, release.py, source-repo-scripts/release_summary.bash, terminal-dashboard/unreleased.bash
Part of: https://github.com/gazebo-tooling/release-tools/pull/746
=> ign -> gz : Release Tools Migrate Links and Lib Names

jenkins-scripts/docker/ign_cmake-compilation.bash, jenkins-scripts/docker/ign_common-compilation.bash, jenkins-scripts/docker/ign_fuel-tools-compilation.bash, jenkins-scripts/docker/ign_gazebo-compilation.bash, jenkins-scripts/docker/ign_gui-compilation.bash, jenkins-scripts/docker/ign_launch-compilation.bash, jenkins-scripts/docker/ign_math-compilation.bash, jenkins-scripts/docker/ign_msgs-compilation.bash, jenkins-scripts/docker/ign_physics-compilation.bash, jenkins-scripts/docker/ign_plugin-compilation.bash, jenkins-scripts/docker/ign_rendering-compilation.bash, jenkins-scripts/docker/ign_sensors-compilation.bash, jenkins-scripts/docker/ign_transport-compilation.bash, jenkins-scripts/docker/ign_utils-compilation.bash, jenkins-scripts/ign_common-default-devel-windows-amd64.bat, jenkins-scripts/ign_fuel-tools-default-devel-windows-amd64.bat, jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat, jenkins-scripts/ign_gui-default-devel-windows-amd64.bat, jenkins-scripts/ign_launch-default-devel-windows-amd64.bat, jenkins-scripts/ign_math-default-devel-windows-amd64.bat, jenkins-scripts/ign_msgs-default-devel-windows-amd64.bat, jenkins-scripts/ign_physics-default-devel-windows-amd64.bat, jenkins-scripts/ign_plugin-default-devel-windows-amd64.bat, jenkins-scripts/ign_rendering-default-devel-windows-amd64.bat, jenkins-scripts/ign_sensors-default-devel-windows-amd64.bat, jenkins-scripts/ign_tools-default-devel-windows-amd64.bat, jenkins-scripts/ign_transport-default-devel-windows-amd64.bat, jenkins-scripts/ign_utils-default-devel-windows-amd64.bat
Part of: https://github.com/gazebo-tooling/release-tools/pull/746
=> ign -> gz : Release Tools Migrate Project Names

bloom/ros_gz_bridge-release.py.bash
See https://github.com/gazebosim/ros_gz/pull/262
Part of: https://github.com/gazebo-tooling/release-tools/issues/698
=> ign -> gz ros_gz Migration : Migrate ros_gz release script

jenkins-scripts/docker/sdformat-compilation.bash
* https://github.com/gazebosim/sdformat/pull/1094
=> Remove SKIP_usd

jenkins-scripts/dsl/ignition_collection.dsl
* Follow up to https://github.com/gazebo-tooling/release-tools/pull/785
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
=> Build nightlies from gz-sim7 branch

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
Following ROS works in https://github.com/ros2/ci/pull/667. Disable the new mechanism of randomly install new updates.
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_cmake-ci-ign-cmake2-focal-amd64&build=24)](https://build.osrfoundation.org/job/ignition_cmake-ci-ign-cmake2-focal-amd64/24/)
=> Disable apt phased updates in Dockerfile

terminal-dashboard/table.bash
=> Remove buster from release dashboard

jenkins-scripts/dsl/ignition.dsl
Fix a problem with the name of gz-sim debbuilder
=> Replace gz-gazebo7 debbuilder by gz-sim7

jenkins-scripts/docker/ignition-abichecker.bash
=> Fix OGRE paths for the ABI checker

.github/ISSUE_TEMPLATE/release_collection.md
Follow-up to https://github.com/gazebo-tooling/release-tools/pull/793#issuecomment-1229123376
=> release collection: stable CI jobs, update view

jenkins-scripts/dsl/gazebo.dsl
Change osrf/gazebo to gazebosim/gazebo-classic.
Signed-off-by: Steve Peters <scpeters@openrobotics.org>
=> gazebo.dsl: use new GitHub URL

jenkins-scripts/dsl/ignition.dsl
Follow up #870 . Would be better to just define it in a single place, I've open an issue for it https://github.com/gazebo-tooling/release-tools/issues/871
=> Add msgs10 and transport12 nightly jobs

jenkins-scripts/dsl/ignition.dsl
=> Use transport13 for new nightlies instead of 12

jenkins-scripts/dsl/ignition.dsl
Following up comment in https://github.com/gazebo-tooling/release-tools/pull/884#issue-1614016367
=> Fix generation of sim7 bottle

jenkins-scripts/lib/colcon-default-devel-windows.bat, jenkins-scripts/lib/windows_library.bat
Following up https://github.com/gazebo-tooling/release-tools/pull/907#discussion_r1164698413
Tested https://build.osrfoundation.org/job/_test_ign_utils-ci-win/3/console#console-section-1
=> List vcpkg packages installed in the build log

jenkins-scripts/README.md
DSL workflow and general information for developers. 
:page_facing_up: [ rendered](https://github.com/gazebo-tooling/release-tools/blob/c7f97a46a945c4d29796ba00cc9df2c96852096f/jenkins-scripts/README.md)
=> Jenkins scripts DSL docs

jenkins-scripts/dsl/ignition.dsl
To facilitate some changes in the CI platforms, this initial PR aims to not changing anything in the XML produced but to reorder the DSL.
=> Reorder DSL code to simplify new changes

jenkins-scripts/lib/check_graphic_card.bash
Currently, #916 is not detecting display in Linux agents.
Some Linux gazebo builds are showing display problems:
* https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/10649/
* https://build.osrfoundation.org/job/ignition_gazebo-ci-gz-sim7-focal-amd64/136/
* https://build.osrfoundation.org/job/ignition_rendering-ci-main-focal-amd64/70/
<details>
<summary>
Log output:
</summary>
```
-- Looking for display capabilities
--  ! valid display not found
--  ! valid dri display not found (no glxinfo or pyopengl)
```
then:
```
65: qt.qpa.xcb: could not connect to display unix::0
```
or 
```
11: [Err] [OgreRenderEngine.cc:358] Unable to open display: unix::0
```
Depending on the job.
</details>
Refer to #979 for more information
=> Revert display detection

jenkins-scripts/dsl/gz-collections.yaml
See https://github.com/gazebo-tooling/release-tools/issues/976
=> Bumps in Harmonic: sdformat14

jenkins-scripts/dsl/ignition.dsl, jenkins-scripts/dsl/ignition_collection.dsl
See https://github.com/gazebo-tooling/release-tools/issues/976
=> Add sdformat14 nightlies 

terminal-dashboard/_dashboard_lib.sh, terminal-dashboard/table.bash
Probably useful during the releasing process @azeey
=> Update terminal dashboard to support Harmonic

.github/workflows/ci.yaml
I noticed CI was failing in #1012
=> Fix CI for pull requests from forks

jenkins-scripts/dsl/gz-collections.yaml
the upcoming lib version will be the version number in [this file](https://github.com/gazebo-tooling/gazebodistro/blob/master/collection-ionic.yaml) + 1.
=> Update rendering and physics lib version in upcoming collection

jenkins-scripts/tools/outdated-job-runner.groovy
Follow up to: https://github.com/osrf/buildfarm-tools/pull/4
=> Update ign-sim6 name

.github/workflows/ci.yaml
Improve readability by sorting the DSL produced jobs in the log file.
=> Sort log generated files from DSL

jenkins-scripts/dsl/ignition.dsl, jenkins-scripts/dsl/sdformat.dsl
Time to completely remove the old `-ci-pr_any-ubuntu_auto` fake jobs that were added #1022 to help the transition.
=> Remove the ubuntu_auto -ci-pr_any- fake jobs

jenkins-scripts/dsl/ignition.dsl
Clean up the jobs created during the transition #1054 . Part of  #1010
=> Remove previous brew -ci-pr_any- jobs

jenkins-scripts/dsl/dsl_checks.bash
Due to https://github.com/gazebo-tooling/release-tools/issues/1095.
=> Disable DSL check for duplicate abicheckers

check_releasepy.bash, release.py
=> Handle ign- prefix in release.py calls

release-repo-scripts/new_ubuntu_distribution.bash
The PR implement the option of not importing from Debian repositories (via an environment variable) when using the `new_ubuntu_distribution` script. Disabled by default since most of the times we don't want to import from debian since there are no recent changes there.
=> Support DEBIAN_IMPORT in the new_ubuntu_distribution script

jenkins-scripts/tools/cmake_to_gtest_junit_output.py
While testing #1130 using gz-fuel-tools9 ASAN branch just noticed that although we are injecting missing context into some tests, in the case of finding ASAN failures, the context is indeed injected but the failure state is not be injected so the tests are still passing all of them even if the status was "fail" in CTest.
With this PR I'm using the field "errors" reserved for non-CI strictly failing reasons to inject the errors from CTest into the Gtest testsuite. The PR also adds a bit of output about what we are doing and where.
See it working in https://build.osrfoundation.org/job/_test_gz_fuel_tools-ci_asan-gz-fuel-tools9-jammy-amd64/17/
=> Make test to fail if problems where found in CTest results (for #1130)

jenkins-scripts/docker/ros_gz-install-test-job.bash
Mainly fix the comparison that was adding a double negative with `!` and `grep -v` . I added a gz topic info command that should generate time enough to the pub/sub system to work. 
Testing it here [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros_gzharmonic_bridge-install-pkg_humble-ci-jammy-amd64&build=66)](https://build.osrfoundation.org/job/ros_gzharmonic_bridge-install-pkg_humble-ci-jammy-amd64/66/)
=> Fix check for pub/sub in unofficial wrappers

release-repo-scripts/convert_gazebodistro_to_release.py
Read `package.xml` from main branches to get the package name if branch is set to main in a gazebodistro file.
=> Deal with main branches for the convert_gazebodistro_to_release script

jenkins-scripts/dsl/gz-collections.yaml, jenkins-scripts/dsl/logs/generated_jobs.txt
=> Ionic CI: use stable branch for sdformat15

jenkins-scripts/dsl/gz-collections.yaml, jenkins-scripts/dsl/logs/generated_jobs.txt
=> Use stable branch gz-fuel-tools10

jenkins-scripts/dsl/gz-collections.yaml, jenkins-scripts/dsl/logs/generated_jobs.txt
Needed to make a pre-release of gz-plugin3.
=> Use stable branch gz-plugin3

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
Should be useful to run the file locally for debugging
=> Add the /bin/bash shebang to build.sh

jenkins-scripts/lib/windows_library.bat
Replace custom call to wget command by a powershell call. Tested this in https://build.osrfoundation.org/job/sdformat-pr-win/1167/badge/ and in the current testing conda works [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_conda_gz_sim-pr-win&build=13)](https://build.osrfoundation.org/job/_test_conda_gz_sim-pr-win/13/) to download pixi.
=> windows_library: replace custom wget with powershell

README.md
They currently point to garden, update to latest.
=> README: update docs links to latest

source-repo-scripts/bump_dependency.bash
This also fixes some issues encountered while running the script for https://github.com/gazebo-tooling/release-tools/issues/1235
=> Add more search/replace patterns in bump_dependency.bash

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
This should hopefully fix https://github.com/gazebosim/gz-sim/pull/2722#issuecomment-2598917305
=> Only use matching branch in gzdev if the branch actually exists

conda/envs/legacy/pixi.lock, conda/envs/legacy/pixi.toml, conda/envs/legacy_ogre23/pixi.lock, conda/envs/legacy_ogre23/pixi.toml
Thanks to @traversaro in https://github.com/gazebo-tooling/release-tools/pull/1232#discussion_r1910700871
=> Update gl, egl and libglvnd libraris in Conda envs

jenkins-scripts/dsl/gazebo_libs.dsl
Should make the existing jobs not to fail
//cc @Crola1702 sorry for that
=> Only check Conda environments on USE_PIXI

jenkins-scripts/dsl/gazebo_libs.dsl
=> Fix typo in checking Conda paths

jenkins-scripts/dsl/_configs_/GenericMail.groovy
=> Change deprecated getEnvVars Groovy method in NO_MAILS

jenkins-scripts/lib/colcon-default-devel-windows.bat
Reducing the weirdness of the variable expansion on Windows after running the script locally.
Testing it here [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_gui-pr-clowin&build=21)](https://build.osrfoundation.org/job/gz_gui-pr-clowin/21/)
=> Fix variable expansion in GPU Windows check

conda/README.md, jenkins-scripts/dsl/_configs_/OSRFWinCompilationAnyGitHub.groovy, jenkins-scripts/dsl/gazebo_libs.dsl
Might be useful for works like #1293 . Need manual settings for testing.
=> Allow -pr- jobs to use a custom CONDA_ENV_NAME via parameter

.github/ISSUE_TEMPLATE/bump_libraries.md
Example command used to open pull requests for #1292.
=> Add example command to issue template

conda/envs/noble_like/pixi.lock, conda/envs/noble_like/pixi.toml
Follow up to https://github.com/gazebo-tooling/release-tools/pull/1230, needed for https://github.com/gazebosim/gz-utils/pull/167.
=> Add cli11 >= 2.4.1,<3 for noble_like/pixi.toml

jenkins-scripts/dsl/test.dsl
=> DSL: change PostBuildSCript II (missing test.dsl)

jenkins-scripts/dsl/_configs_/OSRFDslBase.groovy, jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkgBase.groovy, jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy, jenkins-scripts/dsl/_configs_/OSRFUNIXBase.groovy, jenkins-scripts/dsl/extra.dsl, jenkins-scripts/dsl/generate_dsls.dsl, jenkins-scripts/dsl/test.dsl, jenkins-scripts/dsl/tools/setup_local_generation.bash
The PR should bring the changes in #1327 from master and produce a new updated copy of the local generator for CI and local development.
=> [Crola1702/24.04] Merge master changes and new local generator for DSL

jenkins-scripts/dsl/_configs_/OSRFDslBase.groovy, jenkins-scripts/dsl/generate_dsls.dsl
This PR creates `generate_dsls.dsl` which is a generator of the `_dsl_*` jobs that configure other jobs
=> Copy generate dsls from #1323

jenkins-scripts/dsl/extra.dsl, jenkins-scripts/dsl/test.dsl
Remove the publisher block for dsl files.
=> [Crola1702/24.04] Patch extra.dsl and test.dsl files

jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkgBase.groovy, jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy, jenkins-scripts/dsl/_configs_/OSRFUNIXBase.groovy, jenkins-scripts/dsl/test.dsl
All the expected XML files needs to be present for the configure block. I'm quite sure that now the test.dsl and the OSRFUNIXBase are working. Still testing the SourceCreation.
=> Fix PostBuild DSL configure block (take III)

jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy
Following up #1344 . The full XML for the OSRFSourceCreation. Tested in https://build.osrfoundation.org/job/_test_gz_source/96/
=> OSRFSourceCreation configure block patch

jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkgBase.groovy, jenkins-scripts/dsl/extra.dsl, jenkins-scripts/dsl/ignition_collection.dsl
=> Patch configure block for builders and nightly (take IV)

jenkins-scripts/dsl/gazebo_libs.dsl
Change in #1350 was not affecting all -ci_asan- jobs. Fix the code to do it.
=> Fix -asan- disable to affect all asan jobs

jenkins-scripts/dsl/gz-collections.yaml, jenkins-scripts/dsl/logs/generated_jobs.txt
part of https://github.com/gazebosim/gz-jetty/issues/30
=> Use stable branch for gz-rendeirng10
