release.py

All the release repos are now under https://github.com/ignition-release, so we can simplify the logic in release.py that tried to identify whether bitbucket or GitHub was hosting the release repo.

release.py: simplify logic since all release repos are on GitHub now

---

jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkg.groovy
jenkins-scripts/dsl/ros1_ign_bridge.dsl
jenkins-scripts/lib/debbuild-base.bash
jenkins-scripts/lib/libbullet-release-base.bash

The old chroot scripts need a clean up (those living in jenkins/lib/ instead of jenkins/docker/lib) but I'm changing here all the ocurrences I found.
Testing:
* DSL  [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition&build=949)](https://build.osrfoundation.org/view/All/job/_dsl_ignition/949/)
* debbuild: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-launch2-debbuilder&build=23)](https://build.osrfoundation.org/job/ign-launch2-debbuilder/23/)

Remove Bitbucket release from debbuild scripts

---

jenkins-scripts/lib/dependencies_archive.sh

On BitBucket pipelines, we installed ruby and swig as `ign-math` dependencies to make sure ruby tests were running. It may take a while until we have GitHub actions, so I propose we run these tests on Jenkins.
Test build: [![Build Status](https://build.osrfoundation.org/job/ignition_math-ci-pr_any-ubuntu_auto-amd64/243/badge/icon)](https://build.osrfoundation.org/job/ignition_math-ci-pr_any-ubuntu_auto-amd64/243/)

Add Ruby dependency to ign-math

---

jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash
jenkins-scripts/docker/lib/boilerplate_prepare.sh

There were some problems related to the use of `make -j` with no specific job count. That triggered automatically many jobs that were killing the drogon node in some occasions due to the lack of memory available.
We are calling recursively the generic compilation script in order to get dependencies compiled. Somehow in those calls the MAKE_JOBS variable is missing. I tried to reproduce the problem locally using a minimal script but I was unable to get the same result.
This PR is no more than a workaround in order to avoid that effect by using a file in the WORKSPACE and inject the content of the file in the script.
Tested: https://build.osrfoundation.org/job/_test_maxjobs_ignition_gazebo-ci-default-bionic-amd64/2/consoleFull . (grep for `make -j`).

Workaround to avoid make_jobs to be unset

---

jenkins-scripts/dsl/_configs_/OSRFGitHub.groovy
jenkins-scripts/dsl/sdformat.dsl

Create a `OSRFGitHub` helper class similar to `OSRFBitbucketHg` and change sdformat release branch builds to use it (save the `-ci-pr_any-` branches for later). Also rename the `-ci-default` builds to `-ci-master`.
* https://build.osrfoundation.org/job/_dsl_sdformat/838/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-master-bionic-i386&build=1)](https://build.osrfoundation.org/job/sdformat-ci-master-bionic-i386/1/) https://build.osrfoundation.org/job/sdformat-ci-master-bionic-i386/1/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-master-homebrew-amd64&build=1)](https://build.osrfoundation.org/job/sdformat-ci-master-homebrew-amd64/1/) https://build.osrfoundation.org/job/sdformat-ci-master-homebrew-amd64/1/
* [![Build …

Jenkins dsl: use GitHub for sdformat non-any builds

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy

$SRC_BRANCH is not a parameter created by the
github pull reuqest builder plugin, but $GIT_BRANCH seems to be.
* https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-homebrew-amd64/292/parameters/
Testing with sdformat:
* https://build.osrfoundation.org/job/_dsl_sdformat/853/
* the sdf4 windows jenkins builds don't work, so I was able to see an email with a useful branch name in the subject line from https://github.com/osrf/sdformat/pull/248: "sdformat-ci-pr_any-windows7-amd64 - Branch: github_changelog_sdf4 (#1313) - Failure!"

GithubAny emails: use $GIT_BRANCH in subject line

---

jenkins-scripts/dsl/sdformat.dsl

I noticed some old sdformat branches have failing windows builds:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat5-windows7-amd64&build=47)](https://build.osrfoundation.org/job/sdformat-ci-sdformat5-windows7-amd64/47/) https://build.osrfoundation.org/job/sdformat-ci-sdformat5-windows7-amd64/47/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat4-windows7-amd64&build=74)](https://build.osrfoundation.org/job/sdformat-ci-sdformat4-windows7-amd64/74/) https://build.osrfoundation.org/job/sdformat-ci-sdformat4-windows7-amd64/74/
I disabled the jobs for now, but we need to disable them in dsl for the next time they get regenerated. This PR disables all sdformat5 CI builds since that version is no longer …

Sdformat disable old jobs

---

jenkins-scripts/dsl/gazebo.dsl

Similar to #168 and #169. I expect some configuration needs to happen on the GitHub repository as well.
* https://build.osrfoundation.org/job/_dsl_gazebo/653/
~~~
Added items:
GeneratedJob{name='gazebo-ci-master-bionic-amd64-gpu-nvidia'}
GeneratedJob{name='gazebo-ci-master-bionic-amd64-gpu-none'}
GeneratedJob{name='gazebo-ci-master-bionic-i386-gpu-none'}
GeneratedJob{name='gazebo-ci_BTRelease-master-bionic-amd64-gpu-none'}
GeneratedJob{name='gazebo-ci_BTDebug-master-bionic-amd64-gpu-none'}
GeneratedJob{name='gazebo-ci_BTCoverage-master-bionic-amd64-gpu-none'}
GeneratedJob{name='gazebo-ci-master-homebrew-amd64'}
GeneratedJob{name='gazebo-ci-master-windows7-amd64'}
GeneratedJob{name='gazebo-ci-manual_any'}
~~~
~~~
Unreferenced items: …

gazebo: migrate to github CI

---

jenkins-scripts/docker/ign_msgs-compilation.bash

`ign-msgs1` CI is [failing](https://build.osrfoundation.org/job/ignition_msgs-ci-pr_any-ubuntu_auto-amd64/317/consoleFull) on Xenial with this message:
```
Step 23/34 : RUN gem install protobuf
---> Running in 8e959b4281df
ERROR:  Error installing protobuf:
zeitwerk requires Ruby version >= 2.4.4.
```
A quick solution is to just skip Ruby for Xenial.
Queued a test build: [![Build Status](https://build.osrfoundation.org/job/ignition_msgs-ci-pr_any-ubuntu_auto-amd64/325/badge/icon)](https://build.osrfoundation.org/job/ignition_msgs-ci-pr_any-ubuntu_auto-amd64/325/)

Don't install Ruby for ign-msgs on Xenial

---

jenkins-scripts/tools/git_delete_closed_hg_branches.bash

Using 'hg log -r 'closed()' was inaccurate, as it includes
branches that were closed and then re-opened, causing the
git_delete_closed_hg_branches.bash script to delete open branches.
This improves the logic using 'hg heads -c'.
For gazebo:
~~~
$ hg log -r 'closed()' --template "{branch}\n" | sort | uniq | wc -l
3144
~~~
~~~
$ hg log -r 'closed() and head()' --template "{branch}\n" | sort | uniq | wc -l
3124
~~~
~~~
$ hg branches -c | grep '(closed)$' | sed -e 's@ *[0-9]*[0-9]:.*@@' | sort | uniq | wc -l
3121
~~~
the last one is the most accurate for this purpose

ID closed branches to delete with 'hg heads -c'

---

jenkins-scripts/docker/ign_fuel-tools-compilation.bash
jenkins-scripts/docker/ign_gazebo-compilation.bash
jenkins-scripts/docker/ign_gui-compilation.bash
jenkins-scripts/docker/ign_launch-compilation.bash
jenkins-scripts/docker/ign_sensors-compilation.bash
jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash
jenkins-scripts/docker/lib/gazebo-base-default.bash
jenkins-scripts/docker/sdformat-compilation.bash

When building dependencies from source in the docker scripts, clone from GitHub rather than bitbucket. Also change some `default` branch names to `master`.

Docker scripts: bitbucket -> GitHub

---

jenkins-scripts/dsl/_configs_/OSRFLinuxCompilationAnyGitHub.groovy

This was broken by #168 and caused gazebo_ros_pkgs
jobs to create builds for every ROS distro.

Pass supported_ros_distros parameter

---

jenkins-scripts/lib/sdformat-base-windows.bat
jenkins-scripts/lib/windows_library.bat

This updates `windows_library.bat` to clone the `master` branch by default instead of `default` as a follow-up to #181.
It also cleans up some logic from sdformat-base-windows.bat since that scripts is only used for sdformat5 and earlier (see https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/sdformat-default-devel-windows-amd64.bat#L10-L14 ).

Windows scripts: default -> master

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy
jenkins-scripts/dsl/_configs_/OSRFLinuxCompilationAnyGitHub.groovy
jenkins-scripts/dsl/gazebo_ros_pkgs.dsl

I've removed all gazebo_ros_pkgs branches logic out of generic classes (it was duplicated inside `gazebo_ros_pkgs.dsl`).

Remove gazebo_ros_pkgs branch logic out of generic DSL classes

---

jenkins-scripts/dsl/gazebo_ros_pkgs.dsl

Here we go [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros_gazebo11_pkgs-install_pkg_melodic-bionic-amd64&build=1)](https://build.osrfoundation.org/job/ros_gazebo11_pkgs-install_pkg_melodic-bionic-amd64/1/)
Part of issue https://github.com/ros-simulation/gazebo_ros_pkgs/issues/1088

Add Gazebo11 ROS packages for Melodic to CI

---

jenkins-scripts/dsl/gazebo_ros_pkgs.dsl

The intention is to create "default" jobs for non-official gazebo-ros combinations, for example:
`ros_gazebo9_pkgs-ci-default_kinetic-xenial-amd64`
That should use:
* `gazebo_ros_pkgs`'s `kinetic-devel` branch
* Gazebo9 debs
* Kinetic debs
I just copied the definition of the equivalent `pr_any` jobs. The intention is that we periodically trigger the new ones so that this job's result reflects the default status without any pull request interference. My main goal is to get a meaningful badge :smile: 
In the future, it would be nice for these to be automatically triggered whenever something new is merged into the release branch, but I didn't look into how to enable that.

👩‍🌾 Add 'default' jobs for extra gazebo_ros versions

---

jenkins-scripts/lib/dependencies_archive.sh

@azeey noticed that we weren't installing sdformat9 in our Ubuntu CI:
* https://github.com/ignitionrobotics/ign-physics/pull/54#issuecomment-625319079

Ubuntu CI: install both sdf8/9 for physics

---

release.py

Port our release tool to be able to work with new github repositories. Code is a bit old and would need a good cleanup but the patch seems to work for me while releasing `ignition-rendering2`.
The use is as usual. Remember to include the `-a ignition-foo2 --ignition-repo` arguments.
Tested:
* [builds are in Jenkins](https://build.osrfoundation.org/job/ign-rendering2-debbuilder/43)
* [S3 tarball is in place](https://osrf-distributions.s3.amazonaws.com/ign-rendering/releases/ignition-rendering2-2.4.0.tar.bz2)
* [tag is ok](https://github.com/ignitionrobotics/ign-rendering/releases/tag/ignition-rendering2_2.4.0)

Port release.py to use github repository as source code

---

jenkins-scripts/lib/homebrew_bottle_creation.bash

As I noted in https://github.com/osrf/homebrew-simulation/issues/1005#issuecomment-626047465, [homebrew-test-bot](https://github.com/Homebrew/homebrew-test-bot) has changed a lot recently, and our bottle build script no longer works with the master branch of that repo. We have the ability to use custom branches of `homebrew-test-bot`, but it currently uses `git pull`, which can only merge commits into the current branch; it can't rewind to an old state. So this PR changes the `git pull` to a `git fetch` and `git checkout`. I used it successfully with https://github.com/osrf/homebrew-simulation/pull/1006.

brew bottle build: fetch test-bot branch instead of pull

---

jenkins-scripts/lib/dependencies_archive.sh

Follow-up to this comment ( https://github.com/ignition-tooling/release-tools/pull/194#discussion_r421742541 )from @j-rivero who correctly noted that the approach in #194 was a bit messy. The more precise approach is to install only one version of sdformat depending on the major version of ign-physics.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics-ci-ign-physics1-bionic-amd64&build=44)](https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics1-bionic-amd64/44/) https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics1-bionic-amd64/44/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics-ci-ign-physics2-bionic-amd64&build=21)](https://build.osrfoundation.org/job/ignition_physics-ci-ign-physi …

Install only one sdf dep for ign-physics

---

jenkins-scripts/dsl/brew_release.dsl

The master branch has breaking changes, so use the `still_working` branch from my fork until they have been resolved. I've been manually restarting these jobs with these parameters (most recently https://github.com/osrf/homebrew-simulation/pull/1009 ), so let's just automate it for now.
* homebrew:master: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_bottle_builder&build=774)](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/774/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/774/parameters/
* scpeters:still_working: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_bottle_builder&build=777)](https://build.osrfoundation.org/job/generic-relea …

Use still_working branch of test-bot

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy
jenkins-scripts/dsl/test.dsl

One of the problems to develop DSL code that we have now is that [the trick to generate jobs](https://github.com/jenkinsci/job-dsl-plugin/wiki/User-Power-Moves) (check syntax and results) does not work with the github PR plugin DSL code.
This PR changes the DSL to use configure block. Although we are losing a layer of indirection and almost inject code directly in the XML I think it worth to back to be able to generate code locally to speed up development.
I still need to configure test.dsl and a test repo to do the checks on Jenkins itself.

Move Github integration DSL code to configure block

---

jenkins-scripts/lib/homebrew_bottle_creation.bash

I noticed that the dartsim@6.10.0 bottle filename had changed the `@` character to `%40` before upload to s3, which caused it to fail to download during `brew install dartsim@6.10.0` (see the build artifacts in https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/830/label=osx_highsierra/ ).
This is caused by https://github.com/Homebrew/brew/pull/7532 which encodes the filename in json. This PR decodes it, which should fix the problem.

brew: decode bottle filename as URI.

---

jenkins-scripts/docker/ign_cmake-compilation.bash
jenkins-scripts/ign_cmake-default-devel-windows-amd64.bat
jenkins-scripts/lib/generic-default-devel-windows.bat

In support of ignitionrobotics/ign-cmake#97

Add BUILDSYSTEM_TESTING flag to enable ign-cmake

---

jenkins-scripts/dsl/ignition.dsl

This package is no longer used by delphyne or anything else,
so we can stop running its CI jobs.
Signed-off-by: Steve Peters <scpeters@openrobotics.org>

ignition.dsl: stop CI for ign-rendering0

---

jenkins-scripts/dsl/ignition.dsl

Disable these PR jobs because they're expected to fail:
* https://build.osrfoundation.org/job/ign_gazebo-pr-win/
* https://build.osrfoundation.org/job/ign_launch-pr-win/
The equivalent release branch jobs are already disabled.
Re-enable when https://github.com/ignitionrobotics/ign-gazebo/issues/168 is fixed.

Disable gazebo and launch PR-any on Windows

---

jenkins-scripts/docker/lib/_gazebo_utils.sh
jenkins-scripts/docker/lib/boilerplate_prepare.sh
jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/docker/lib/eigen-abi-checker.bash
jenkins-scripts/docker/lib/eigen_pcl-abi-checker.bash
jenkins-scripts/docker/lib/vrx-compilation-base.bash
jenkins-scripts/docker/multidistribution-ignition-debbuild.bash
jenkins-scripts/docker/vrx-install-test-job.bash
jenkins-scripts/lib/boilerplate_prepare.sh
jenkins-scripts/lib/debbuild-base.bash
jenkins-scripts/multidistribution-ignition-debbuild.bash
one-line-installations/gazebo.sh

I grepped for `://bitbucket` to see which files are still using bitbucket URL's, and I've replaced many of them. Two commits change URL's in comments, and one changes a URL for eigen's ABI-checking jobs. The more consequential changes are in 3aed217, which fetches the gazebo_models tarball from GitHub now, and 06ce0dd, which clones from GitHub for nightly builds.

Replace more bitbucket urls with github

---

jenkins-scripts/dsl/brew_release.dsl
jenkins-scripts/lib/homebrew_bottle_creation.bash

Add `BREW_REPO` and `BREW_BRANCH` parameters to use in bottle builds
and default to still_working branch of scpeters/brew. This is needed since https://github.com/Homebrew/brew/pull/7700 broke our `still_working` branch of homebrew-test-bot.
Next week I'll try to update our workflow so we don't depend on old branches, but protobuf seems to break our bottles every week, so I'm just doing this to unbreak the bottles for now in https://github.com/osrf/homebrew-simulation/pull/1043.

brew dsl: add parameters for brew branch and repo

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy
jenkins-scripts/dsl/_configs_/OSRFLinuxCompilationAnyGitHub.groovy
jenkins-scripts/dsl/gazebo.dsl

Implement the support to generate jobs that can work with PR git references but they are not automatically integrated with github PRs. This is the case of the `gazebo-ci-pr_any+sdformat_any+ign_any-${distro}-${arch}-gpu-${gpu}` that should not appear in github notifications.

Disable github integration in gazebo+sdformat+ignition

---

jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/lib/debbuild-base.bash

I broke all the nightly builds in #215.
Use "git clone -b" instead of "git clone -r".
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-transport7-debbuilder&build=489)](https://build.osrfoundation.org/view/debbuild/job/ign-transport7-debbuilder/489/) https://build.osrfoundation.org/view/debbuild/job/ign-transport7-debbuilder/489/
~~~
+ git clone https://github.com/ignitionrobotics/ign-transport -r ign-transport7
error: unknown switch `r'
~~~

Fix git clone in nightly debbuilds

---

jenkins-scripts/docker/lib/debbuild-base.bash

Since we change the VCS all +hg versions suffixes are having a greater version than new nightlies using +git. Proposed by @scpeters to use nightly to get the new ones to have greater versions (alpha order) than old +hg.

Rename nightly suffix to fix problems with order between hg and git

---

jenkins-scripts/lib/dependencies_archive.sh

Use tinyxml2 for sdformat10

---

jenkins-scripts/lib/dependencies_archive.sh

I just merged #220 but it has a syntax error:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_cmake-install-pkg-xenial-amd64&build=936)](https://build.osrfoundation.org/job/ignition_cmake-install-pkg-xenial-amd64/936/) https://build.osrfoundation.org/job/ignition_cmake-install-pkg-xenial-amd64/936/
~~~
./scripts/jenkins-scripts/docker/../lib/dependencies_archive.sh: line 62: syntax error in conditional expression: unexpected token `;'
~~~

dependencies_archive.sh: fix bash syntax

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy

I've looking into improve the Jenkins results published to github for cases where the build is not green but unstable. My findings are not very optimistic since the plugin is not maintained and seems to lack the ability to report Jenkins variables coming from warnings or even build status.
All I found is an option that comes with the plugin and report a summary of the testing run (see the bubble box, ignore the rest): ![image](https://user-images.githubusercontent.com/2098802/84543425-a8623a80-acfb-11ea-9195-bbc7b91d5d7b.png)
The only viable option I see to report more interesting things in Github statuses would be to add a post-build action against the github API, that would require far more work.
Test run for Gazebo seems happy …

Add report of testing to Github status

---

release.py

Git does not support `~` in tag names. I'm changing it to use a `-` in repository tags. I don't think that we are using the tags for anything in release-tools, if that is correct we don't need to change anything more.

Do not use ~ (tilde) in git tags

---

jenkins-scripts/dsl/_configs_/OSRFLinuxBackportPkg.groovy
jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkg.groovy
jenkins-scripts/dsl/brew_release.dsl
jenkins-scripts/dsl/extra.dsl
jenkins-scripts/dsl/gazebo_ros_pkgs.dsl
jenkins-scripts/dsl/ros1_ign_bridge.dsl

The copy artifact plugin we are using to copy generated binaries from one jobs to another (mainly pkgs -> repository uploader and brew bottles -> hash updater) has changed the behavior and [we need to make explicit which jobs are allowed to import the binaries]( https://github.com/jenkinsci/copyartifact-plugin#CopyArtifactPlugin-MigrationMode).
The DSL does not implement this option so I needed to inject code using the configure block. Tested in brew here: https://build.osrfoundation.org/job/_dsl_brew_release/435/console . The permission show up just fine if you open the job configuration.
Mental note: remind to change the working mode of the plugin from migration to production.

Update copy artifact configuration with permissions

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy
jenkins-scripts/dsl/gazebo.dsl
jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/sdformat.dsl

The pull request change how ABI jobs are triggered:
* Before, it was a conditional step in compilation jobs if target branch was different than master
* After: the abi job integrates itself in github calls only if the target branch is a supported branch (major version branches)
I'm leaving the same parameters as before to be able to run builds manually in the same way.
**Testing:**
Be careful to run dsl changes on Jenkins since they will affect production code. I've used my fork to check:
* Test PR with ABI breaking against sdf9 https://github.com/j-rivero/sdformat/pull/1
* Test PR with no ABI breaking changes in sdf8 https://github.com/j-rivero/sdformat/pull/2
All DSL runs fine on my local system and the produced xml for branches seems fine to me.
Closes #191

Integrate ABI jobs in Github

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Provide direct path to pip3 in case it is not linked to `/usr/local/bin`
Workaround until the following is merged:
https://github.com/Homebrew/homebrew-core/pull/57654
All gazebo brew builds are failing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-ci-pr_any-homebrew-amd64&build=1993)](https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1993/) https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1993/

Workaround for missing pip3 on brew

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy
jenkins-scripts/dsl/_configs_/OSRFLinuxABIGitHub.groovy
jenkins-scripts/dsl/ignition.dsl

There was a mistake in a parameter when calling `OSRFLinuxABIGitHub` using checkout subir instead of repository qualified name. This PR should fix the problem and also add correct XML tags for permissions.

Fix ABI jobs integration on ignition CI

---

jenkins-scripts/docker/ign_transport-compilation.bash

The PR is needed to compile ign-msgs6 in transport9 from sources
Tested here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_transport-ci-pr_any-ubuntu_auto-amd64&build=385)](https://build.osrfoundation.org/job/ignition_transport-ci-pr_any-ubuntu_auto-amd64/385/)

Compile msgs from source

---

jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/sdformat.dsl

It needs to be defined in sdformat.dsl, not ignition.dsl because otherwise it makes the job like this:
* https://build.osrfoundation.org/job/ign-sdformat10-debbuilder/
Replace sdformat7-debbuilder with sdformat10-debbuilder, since we aren't planning to make sdformat7 releases.
Don't add sdformat10 to supported branches yet because we don't need ABI checking.

Fix sdformat10 debbuilder job

---

jenkins-scripts/lib/windows_library.bat

While testing some changes in ign-cmake I realize that the CI job preserve the workspace and `vcs import` does not update the checkout directories if they exists. Adding a `vcs pull` updates all repositories to latest commits.
Testing it here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_gui-pr-win&build=328)](https://build.osrfoundation.org/view/All/job/ign_gui-pr-win/328/)

Run vcs pull after vcs import to get latest changes

---

jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat
jenkins-scripts/ign_physics-default-devel-windows-amd64.bat
jenkins-scripts/ign_sensors-default-devel-windows-amd64.bat

sdformat10 now uses tinyxml2, so add it as a vcpkg dependency for ign-physics, sensors, and gazebo builds. Related to https://github.com/ignitionrobotics/ign-physics/pull/85

Add tinyxml2 dependency for windows builds

---

jenkins-scripts/dsl/gzdev.dsl
jenkins-scripts/dsl/subt.dsl
jenkins-scripts/dsl/vrx.dsl

//cc @caguero , @nkoenig 
Migrate the VRX, Subt and gzdev CI code to use github. These should be the last projects we change to the new CI integration.

Migrate VRX, SubT and gzdev to Github

---

jenkins-scripts/dsl/_configs_/OSRFBrewCompilation.groovy
jenkins-scripts/dsl/_configs_/OSRFLinuxCompilation.groovy
jenkins-scripts/dsl/_configs_/OSRFWinCompilation.groovy

The `warning` plugin in Jenkins is deprecated and the upgrade is to use the new warnings-ng.
I suspect that part of the current warning run can kill memory in Jenkins, see https://github.com/osrf/buildfarmer/issues/75.
About the implementation:
* The new plugin does not support the usual declarative DSL so I'm using here a directly injection by [the configure block](https://github.com/jenkinsci/job-dsl-plugin/wiki/The-Configure-Block).
* The change will add cmake parser to our builds and probably trigger a good bunch of new warnings in some builds, I consider it as a desired improvement in QA and something maintainers probably want to fix.
Testing:
* The XML produced locally seems to match what I found in jenkins jobs created manually. I run a gazebo11 test with this configuration: …

Migrate from warnings plugin to warnings-ng

---

bloom/release-bloom.py
jenkins-scripts/dsl/ros1_ign_bridge.dsl

Add a new parameter called `IGNITION_COLLECTION` to support builds of `ros_ign` with custom ignition releases.
DSL is tested here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ros1_ign_bridge&build=29)](https://build.osrfoundation.org/job/_dsl_ros1_ign_bridge/29/)
Output of release script displays correctly the use of the parameter and the inclusion in the Jenkins call:
```
jrivero@nium bloom $ (ign_bridge) ./ros_ign_bridge-release.py.bash 1.0.0 foo-release melodic pass --ignition-collection blueprint -r 1 --dry-run
Accessing: http://build.osrfoundation.org/job/ros-ign-image-bloom-debbuilder/buildWithParameters?PACKAGE=ros-ign-image&UPLOAD_TO_REPO=stable&RELEASE_VERSION=1&UPSTREAM_RELEASE_REPO=foo-release&token=pass&VERSION=1.0.0&IGNITION_COLLECTION=blueprint& …
```

Support to use ignition_version to release ign_ros_bridge

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Should fix problems here: https://github.com/ignitionrobotics/ign-gazebo/pull/262
Tested here:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-pr_any-ubuntu_auto-amd64&build=3783)](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/3783/)

Fix gzdev to get changes in repositories when docker cache is old

---

jenkins-scripts/lib/dependencies_archive.sh

We're missing some QML dependencies, which is causing test failures on https://github.com/ignitionrobotics/ign-gui/pull/69/. 
Test build using this branch queued: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gui-ci-pr_any-ubuntu_auto-amd64&build=567)](https://build.osrfoundation.org/job/ignition_gui-ci-pr_any-ubuntu_auto-amd64/567/)

More QML dependencies for ign-gui

---

jenkins-scripts/docker/lib/subt-compilation-base.bash
jenkins-scripts/lib/dependencies_archive.sh

The problem was not to use the `ENABLE_ROS` parameter so python versions used was python3 instead of python2. 
The change to include theora-image-transport should help caching although the real fix is https://github.com/osrf/subt/pull/523
Tested:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=subt-ci-pr_any-bionic-amd64&build=1177)](https://build.osrfoundation.org/job/subt-ci-pr_any-bionic-amd64/1177/)
I've leaved this branch as default for job running today in subt since current code is pretty broken. Working on fixing the warning.

Fix subt CI compilation by using ENABLE_ROS

---

jenkins-scripts/docker/lib/docker_run.bash

Given the audio capabilities present in Gazebo the CI script map the `/dev/snd` device when running docker to avoid warnings coming from gazebo when it can not find an audio environment. Some of our nodes could potentially not have a sound device, like the AWS nodes.
This PR check that it exists before pass it to the docker run command.
Tested here:
* No `/dev/snd/` node: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-pr_any-ubuntu_auto-amd64&build=1129)](https://build.osrfoundation.org/view/All/job/sdformat-ci-pr_any-ubuntu_auto-amd64/1129/)
* Node with `/dev/snd`: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-pr_any-ubuntu_auto-amd64&build=1130)](https://build.osrfoundation.org/view/All/job/sdformat-ci-pr_any-ubuntu_a …

Check that /dev/snd exists before using it in docker run

---

jenkins-scripts/docker/lib/generic-abi-base.bash

Otherwise the target branch may be out of date.

abi script: fetch origin before checkout

---

jenkins-scripts/docker/lib/debbuild-base.bash

We disabled lintian for focal arm64 builds in #245, but focal armhf builds are hanging too:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-cmake2-debbuilder&build=542)](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/542/) https://build.osrfoundation.org/job/ign-cmake2-debbuilder/542/
So disable lintian for focal armhf too. I queued a build for testing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-cmake2-debbuilder&build=555)](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/555/) https://build.osrfoundation.org/job/ign-cmake2-debbuilder/555/

debbuild: no-lintian for focal armhf also

---

jenkins-scripts/dsl/ignition.dsl

These packages don't have C++ code, so they don't need ABI checking.

Disable ABI checker for ign-cmake and ign-tools

---

jenkins-scripts/docker/lib/docker_run.bash

As part of the works in #262 I'm rescuing here the relevant bits, mostly to make all our builds not to use the `DOCKER_IN_DOCKER` which should give us builds without `--priveledge` mode. Need a good bunch of testing before merge to be sure nothing is broken.
Testing:
* sdformat ci-pr_any [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-pr_any-ubuntu_auto-amd64&build=1132)](https://build.osrfoundation.org/view/All/job/sdformat-ci-pr_any-ubuntu_auto-amd64/1132/) . Unstable for other reasons.
* subt ci-pr_any [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=subt-ci-pr_any-bionic-amd64&build=1268)](https://build.osrfoundation.org/job/subt-ci-pr_any-bionic-amd64/1268/)
* gazebo install [![Build …

Default docker_in_docker to false

---

jenkins-scripts/docker/lib/gazebo_ros_pkgs-base.bash

The gazebo_ros_pkgs CI builds have a cmake warning:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros_gazebo_pkgs-ci-default_melodic-bionic-amd64&build=61)](https://build.osrfoundation.org/job/ros_gazebo_pkgs-ci-default_melodic-bionic-amd64/61/) https://build.osrfoundation.org/job/ros_gazebo_pkgs-ci-default_melodic-bionic-amd64/61/cmake/
~~~
CMake Warning:
Manually-specified variables were not used by the project:
ENABLE_DISPLAY_TESTS
~~~
We are passing this cmake option intended for gazebo_plugins to all the packages in a gazebo_ros_pkgs workspace, which causes the cmake warning. This PR creates a [colcon.meta file](https://colcon.readthedocs.io/en/released/user/configuration.html#using-meta-files) using the `ROS_WS_PREBUILD_HOOK` to target the `gazebo_plugins` …

Use colcon.meta file to fix cmake warning

---

jenkins-scripts/lib/repository_uploader.bash

Some nightly packages have problems uploading the source package since they conflict between distributions. While is not a critical problem itself (few use cases for source packages) it makes the uploads to fail so no binaries go to the repo which in fact it is a critical problem. I'm making the script not to fail but report unstable until I code the right fix for the whole thing.
Tested:
* Failing [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=repository_uploader_ng&build=14910)](https://build.osrfoundation.org/view/All/job/repository_uploader_ng/14910/)
* Good (although the parser was not properly setup) [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=repository_uploader_ng&build=14913)](https://build.osrfoundation.org/view/All/job/repository_ …

Do not fail uploades of source packages

---

jenkins-scripts/lib/windows_library.bat

I tested this with `ign-gui2`.
* Without this PR, there are almost 20 thousand warnings: https://build.osrfoundation.org/job/ign_gui-pr-win/422/
* With this PR, there are 108: https://build.osrfoundation.org/job/ign_gui-pr-win/425/

👩‍🌾 Ignore warnings when compiling dependencies on Windows CI

---

jenkins-scripts/lib/dependencies_archive.sh

Needs testing when buildfarm is less busy than today. Fix https://github.com/osrf/gazebo/issues/2820

Clean up dependencies archive from Gazebo old versions

---

jenkins-scripts/docker/ignition-abichecker.bash

I noticed while reviewing https://github.com/ignitionrobotics/ign-physics/pull/86 that the ignition ABI checker jenkins jobs aren't setting the `GZDEV_PROJECT_NAME` variable, since I enabled prerelease repositories for `ignition-physics2` in https://github.com/osrf/gzdev/pull/16 which fixed the other Ubuntu jobs but not the ABI checker.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics-abichecker-any_to_any-ubuntu_auto-amd64&build=493)](https://build.osrfoundation.org/job/ignition_physics-abichecker-any_to_any-ubuntu_auto-amd64/493/) https://build.osrfoundation.org/job/ignition_physics-abichecker-any_to_any-ubuntu_auto-amd64/493
The `ABI_JOB_SOFTWARE_NAME` variable is currently `ign-${IGN_DESIGNATION}`, so expand "ign-" to "ignition-" and append the …

ignition-abichecker: set GZDEV_PROJECT_NAME

---

jenkins-scripts/dsl/_configs_/OSRFLinuxBackportPkg.groovy
jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkg.groovy
jenkins-scripts/dsl/brew_release.dsl
jenkins-scripts/dsl/extra.dsl
jenkins-scripts/dsl/gazebo_ros_pkgs.dsl
jenkins-scripts/dsl/ros1_ign_bridge.dsl

This change replace the use of the old `repository_uploader_ng` that uploaded packages to build.osrfoundation.org to `repository_uploader_packages` that uploads packages directly to packages.osrfoundation.org. Currently the first one was forwarded calls to the second one which is the most important.
This will kill the old.packages.osrfoundation.org, announced long ago [here](https://community.gazebosim.org/t/packages-osrfoundation-org-new-machine/426/3?u=jrivero)

Replace old packages uploader

---

jenkins-scripts/dsl/_configs_/OSRFLinuxBase.groovy

This should help people to reproduce the Jenkins builds locally. The first commit is the only one interesting https://github.com/ignition-tooling/release-tools/commit/e2b17390fbf405b471daba6403929c815d8e5e48, second is just proper tabs.
Testing in DSL here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_sdformat&build=912)](https://build.osrfoundation.org/view/All/job/_dsl_sdformat/912/)

Export Dockerfile/build.sh as artifacts from each build 

---

jenkins-scripts/dsl/_configs_/OSRFBrewCompilationAnyGitHub.groovy
jenkins-scripts/dsl/brew_release.dsl
jenkins-scripts/lib/_homebrew_github_commit.bash
jenkins-scripts/lib/homebrew_bottle_creation.bash

This fixes the scripts for building homebrew bottles for the osrf/homebrew-simulation tap since our infrastructure is out of date (https://github.com/osrf/homebrew-simulation/issues/1049). Instead of passing a pull request URL as an argument to `brew test-bot`, the tap needs to be checked out to the correct revision first, so we use `hub pr checkout` with the integer pull request ID to checkout the correct branch. Using `hub pr` requires a `GITHUB_TOKEN`, which @j-rivero was kind enough to assist with configuring.
Additionally, builds can now be triggered by a comment from an authorized user that contains the phrase `build bottle` (see https://github.com/osrf/homebrew-simulation/pull/1122 for an example). Note that testing this required hard-coding the release-tools branch with …

Trigger homebrew bottle builds from GitHub comments

---

jenkins-scripts/dsl/ignition_collection.dsl

OSRFLinuxBase jobs expect a Dockerfile and build.sh, which causes the nightly scheduler job to fail, but OSRFUnixBase should work instead.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition-dome-nightly-scheduler&build=75)](https://build.osrfoundation.org/job/ignition-dome-nightly-scheduler/75/) https://build.osrfoundation.org/job/ignition-dome-nightly-scheduler/75/
Similar to 9aa5dbe3cbc88a9e65033d30937a51e82274c23e from #280.

Use OSRFUnixBase for nightly scheduler

---

jenkins-scripts/dsl/ignition_collection.dsl

Fix typo in #283.
I should have tested #283:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition_collection&build=237)](https://build.osrfoundation.org/job/_dsl_ignition_collection/237/) https://build.osrfoundation.org/job/_dsl_ignition_collection/237/
This should fix it:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition_collection&build=238)](https://build.osrfoundation.org/job/_dsl_ignition_collection/238/) https://build.osrfoundation.org/job/_dsl_ignition_collection/238/

dsl: fix capitalization in OSRFUNIXBase

---

jenkins-scripts/lib/repository_uploader.bash

The bottles for `dartsim@6.10.0` were rebuilt in https://github.com/osrf/homebrew-simulation/pull/1148, but they failed to upload:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder&build=34)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/34/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/34/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=repository_uploader_packages&build=6626)](https://build.osrfoundation.org/job/repository_uploader_packages/6626/) https://build.osrfoundation.org/job/repository_uploader_packages/6626/
I had  previously attempted to fix a related problem in #208, but it needs a follow-up here, …

URI decode bottle filename before uploading

---

jenkins-scripts/docker/gazebo-compilation.bash
jenkins-scripts/docker/ign_common-compilation.bash
jenkins-scripts/docker/ign_gazebo-compilation.bash
jenkins-scripts/docker/ign_gui-compilation.bash
jenkins-scripts/docker/ign_launch-compilation.bash
jenkins-scripts/docker/ign_math-compilation.bash
jenkins-scripts/docker/ign_msgs-compilation.bash
jenkins-scripts/docker/ign_physics-compilation.bash
jenkins-scripts/docker/ign_plugin-compilation.bash
jenkins-scripts/docker/ign_rendering-compilation.bash
jenkins-scripts/docker/ign_sensors-compilation.bash
jenkins-scripts/docker/ign_transport-compilation.bash
jenkins-scripts/docker/ignition-abichecker.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/docker/lib/generic-abi-base.bash
jenkins-scripts/docker/sdformat-abichecker.bash
jenkins-scripts/docker/sdformat-compilation.bash
jenkins-scripts/dsl/ignition.dsl

As far as I can see we are using two variable for the same thing. I prefer `NEED_C17_COMPILER` so I changed all references to USE_GCC8 here to use it. Needs to be tested, alternative to #289 , close #288

Unify USE_GCC8 and NEED_C17_COMPILER variables

---

jenkins-scripts/docker/lib/boilerplate_prepare.sh

With new features in modern docker, this PR tries to use them to clean up space when other clean ups strategies are not enough.

Use docker system prune --all to clean docker cache

---

jenkins-scripts/dsl/ignition_collection.dsl

The ignition collection brew CI jobs are not configured properly:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_dome-ci-default-homebrew-amd64&build=3)](https://build.osrfoundation.org/job/ignition_dome-ci-default-homebrew-amd64/3/) https://build.osrfoundation.org/job/ignition_dome-ci-default-homebrew-amd64/3/
They are using branch name `default` instead of `master` and also using an "any" branch configuration instead of the specific branch. I copied the configuration from the following lines:
* https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/dsl/ignition.dsl#L522-L526
Testing: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition_collection&build=241)](https://build.osrfoundation.org/job/_dsl_ig …

Use master branch for ignition collection brew CI jobs

---

jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash
jenkins-scripts/docker/lib/boilerplate_prepare.sh
jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/debbuild-bloom-base.bash
jenkins-scripts/docker/lib/gazebo-base-default.bash
jenkins-scripts/docker/lib/generic-abi-base.bash
jenkins-scripts/docker/lib/simbody-release-base.bash
jenkins-scripts/gazebo-one_liner-homebrew.bash
jenkins-scripts/lib/dependencies_archive.sh
jenkins-scripts/lib/homebrew_bottle_creation.bash

First commit 5374cf6 installs `bc` tool in agents, used to calculate docker version introduced in #282.
Second commit ee4eca4 replaces or removes the mercurial occurrences still present in the scripts.

Replace mercurial with git in job installations. Install bc in agents.

---

jenkins-scripts/dsl/ignition.dsl

The [`ignition_debbuild variable`](https://github.com/ignition-tooling/release-tools/compare/fix_c17_compiler_dsl?expand=1#diff-8c195dd6c7fec2a7aaf5895c7ebaad77R52) is composed from the usual dictionary of software names unversioned plus an array of supported versions and we add to it debbuilds for the software still unreleased in the form of an array of versioned software names. This mess needs to be fix properly in a different PR. This one makes ign-gazebo4-debbuilder to really use the `NEED_C17_COMPILER` variable.
As an extra ball, remove version 6 of transport which is unsupported.
Tested here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition&build=1030)](https://build.osrfoundation.org/view/All/job/_dsl_ignition/1030/)

Fix C17 compiler support ign-gazebo4

---

jenkins-scripts/docker/lib/_ros_setup_buildsh.bash

The PR should remove files in build and install spaces created by ROS. This should help to reduce the disk space used by the different builds.

Clean up installspace + buildspace in ROS workspaces

---

jenkins-scripts/dsl/gazebo.dsl

The PR removes the -none job that is part of the Gazebo CI in pull request. The results are covered by the use ci-pr_any-ubuntu-gpu-nvidia job.

Remove the gazebo-ci-pr_any-ubuntu-none jobs

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/debian.dsl
jenkins-scripts/dsl/gazebo.dsl
jenkins-scripts/dsl/gazebo_ros_pkgs.dsl
jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ignition_collection.dsl
jenkins-scripts/dsl/sdformat.dsl
jenkins-scripts/dsl/subt.dsl
jenkins-scripts/dsl/vrx.dsl

The PR changes the frequency of our -install- jobs on Linux from once a day to once every three days. As an extra ball, all debian install jobs are removed since Debian has its own QA methods.

Change frenquency of install jobs to 1 every three days

---

jenkins-scripts/dsl/sdformat.dsl

This project is still disabled even though the stable release has been made. It's safe to enable it now.
https://build.osrfoundation.org/view/ign-dome/job/sdformat-install-sdformat10_pkg-bionic-amd64/

sdformat.dsl: enable sdformat10 linux install job

---

jenkins-scripts/docker/ign_fuel-tools-compilation.bash
jenkins-scripts/docker/ign_gazebo-compilation.bash
jenkins-scripts/docker/ign_gui-compilation.bash
jenkins-scripts/docker/ign_launch-compilation.bash
jenkins-scripts/docker/ign_rendering-compilation.bash
jenkins-scripts/docker/ign_sensors-compilation.bash
jenkins-scripts/docker/ign_transport-compilation.bash

All dome packages have been released, so we don't need to build any dome dependencies from source anymore.

Dome CI: don't need to build deps from source

---

jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ignition_collection.dsl

I failed to disable a few of the ignition dome xenial install jobs:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_msgs6-install-pkg-xenial-amd64&build=1)](https://build.osrfoundation.org/job/ignition_msgs6-install-pkg-xenial-amd64/1/) https://build.osrfoundation.org/job/ignition_msgs6-install-pkg-xenial-amd64/1/
This should fix it.

ignition.dsl: disable dome xenial install jobs

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/dsl/gzdev.dsl

Proposal from @chapulina.
If github does not redirect the old repository to the new
URI we might find problems in docker cache and this merge
will need to be in sync with the relocation.

Move gzdev to ignition-tooling

---

release-repo-scripts/bump_major_version.bash
release-repo-scripts/new_ignition_release_repos.bash

Some bash lines to make our life easier when changing to a new version of Ignition collections. What it does:
1. Create ign-fooY-release if it does not exits
1. Clone to the current directory
1. Pull from main/master branch from previous version, ign-fooX-release repository to have the whole history
1. Run the  bump_major_version from X to Y
1. Show the results
1. commit/push all the changes
I've used it to create https://github.com/ignition-release/ign-fuel-tools6-release using:
```bash
~/code/release-tools/release-repo-scripts/new_ignition_release_repos.bash ign-fuel-tools6
```
Multiple space separated arguments can be passed. It requires that the user has the awesome https://github.com/cli/cli installed and configured.

New script to create multipe -release repos for new Ignition releases

---

jenkins-scripts/docker/ign_fuel-tools-compilation.bash
jenkins-scripts/docker/ign_gazebo-compilation.bash
jenkins-scripts/docker/ign_gui-compilation.bash
jenkins-scripts/docker/ign_launch-compilation.bash
jenkins-scripts/docker/ign_rendering-compilation.bash
jenkins-scripts/docker/ign_sensors-compilation.bash
jenkins-scripts/docker/ign_transport-compilation.bash

This reverts commit 04854e7869a9da90208ea5c4999db3c220bc43c0. I failed to update the dependencies script, so a lot of things were broken by #305. This just reverts it for now, and we can take a more careful approach.

Revert "Dome CI: don't need to build deps from source (#305)"

---

jenkins-scripts/dsl/ignition.dsl

ign-rndf CI is failing as it doesn't have a main branch, but it has been inactive for a while; I propose to disable its CI jobs.

Disable CI for ign-rndf

---

jenkins-scripts/docker/ign_fuel-tools-compilation.bash
jenkins-scripts/docker/ign_gazebo-compilation.bash
jenkins-scripts/docker/ign_gui-compilation.bash
jenkins-scripts/docker/ign_launch-compilation.bash
jenkins-scripts/docker/ign_rendering-compilation.bash
jenkins-scripts/docker/ign_sensors-compilation.bash
jenkins-scripts/docker/ign_transport-compilation.bash
jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Related tickets: https://github.com/ignition-tooling/release-tools/issues/190 / https://github.com/ignition-tooling/action-ignition-ci/pull/15 / https://github.com/ignition-tooling/release-tools/pull/316
All Ignition libraries now have `.github/ci/package*.apt` files in their source code defining all their debian dependencies. An elaborate example is `ign-gazebo`, which has [3 packages files](https://github.com/ignitionrobotics/ign-gazebo/tree/main/.github/ci):
* `packages.apt` for dependencies common to all platforms
* `packages-bionic.apt` for dependencies specific to Bionic
* `packages-focal.apt` for dependencies specific to Focal
These files are being used by the GitHub actions CI in https://github.com/ignition-tooling/action-ignition-ci , and we can use them here too. Having these …

Install dependencies defined on packages.apt file in source code 

---

jenkins-scripts/lib/homebrew_bottle_creation.bash

Since Homebrew/brew#8883, tapped repositories in CI are not shallow, so we don't need to unshallow them.
I noticed this while debugging the following build failure related to https://github.com/osrf/homebrew-simulation/pull/1179:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder%2Flabel%3Dosx_highsierra&build=66)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_highsierra/66/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/66/label=osx_highsierra/console

Don't need to unshallow taps anymore

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy

The configuration for the Github Pull Request plugin needs to be updated to avoid log problems coming from the fact that cron is not the right XML but spec. The other small change is to remove the duplicate `useGitHubHooks`.

Fix XML generation for the ghprb plugin in DSL

---

jenkins-scripts/dsl/ignition_collection.dsl
release.py

The PR changes release.py to use python3. Needed to work in nightlies of the new server 20.04 where no python is present.
Some changes:
* urllib.encode is now under urllib.parse
* output from subcalls needs to be decoded
* next attribute in generators is now __next__()
Non related to python3:
* Move sc3md check to only in non nightly mode 7711c4c 
* Fix bad use of Exception what df3e11f 
* Change way of checking git remote repositories fa533e2
Tested:
* dry run in nightly scheduler [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition-edifice-nightly-scheduler&build=12)](https://build.osrfoundation.org/job/ignition-edifice-nightly-scheduler/12/)

Migrate release.py to python3

---

release.py

I've used this change in the testing server so nightlies can be built there. Should not change anything for users.

Use JENKINS_URL in release.py if enviroment variable exists

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

If a git branch name contains `packages.apt`, it currently breaks our jenkins script (first noticed in osrf/sdformat#392). This adds a `grep -v '/\.git/' to exclude the contents of a `.git` folder.
Reproduced the failure with [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat9-bionic-amd64&build=42)](https://build.osrfoundation.org/job/sdformat-ci-sdformat9-bionic-amd64/42/) https://build.osrfoundation.org/job/sdformat-ci-sdformat9-bionic-amd64/42/
Testing this branch: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat9-bionic-amd64&build=43)](https://build.osrfoundation.org/job/sdformat-ci-sdformat9-bionic-amd64/43/) https://build.osrfoundation.org/job/sdformat-ci-sdformat9-bionic-amd64/43/

Exclude */.git/* files when finding packages.apt

---

jenkins-scripts/dsl/_configs_/OSRFLinuxBase.groovy

Found Jenkins consuming extensive CPU and one of the reasons could be the more 9k builds that are kept for debbuild or abi jobs. This change should keep a max of 200.

Limit ABI and debbuild jobs to max of 200 builds

---

jenkins-scripts/dsl/brew_release.dsl

New credential is being deployed in the new server invalidate current hash
* Failing: https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_highsierra/74/console
* With this change: https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_highsierra/76/console

Use crendential alias in new server for GITHUB_TOKEN

---

jenkins-scripts/lib/homebrew_bottle_pullrequest.bash

We didn't change all the homebrew scripts to use `python3` in #314 because mojave (10.14) doesn't have a system version of `python3`. The `homebrew_bottle_pullrequest.bash` script is executed on Linux, so it should use python3.
I noticed this from the following failure trying to update https://github.com/osrf/homebrew-simulation/pull/1186:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_pr_bottle_hash_updater&build=1075)](https://build.osrfoundation.org/job/generic-release-homebrew_pr_bottle_hash_updater/1075/) https://build.osrfoundation.org/job/generic-release-homebrew_pr_bottle_hash_updater/1075/
with this branch:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_pr_bottle_hash_updater&build= …

bottle PR script: use python3

---

jenkins-scripts/dsl/gazebo.dsl

Related to https://github.com/osrf/homebrew-simulation/issues/1110
I think it would be good to also disable CI for PRs targeting `gazebo7`, but I'm not sure where to do that.

👩‍🌾 Disable Gazebo7 CI on macOS

---

jenkins-scripts/docker/ign_gazebo-compilation.bash
jenkins-scripts/docker/ign_gui-compilation.bash
jenkins-scripts/docker/ign_launch-compilation.bash
jenkins-scripts/docker/ign_sensors-compilation.bash

Build from source for `ign-rendering` and its dependencies.
Part of https://github.com/ignition-tooling/release-tools/issues/331

Bump in edifice: ign-rendering5

---

jenkins-scripts/dsl/gazebo_ros_pkgs.dsl

Foxy has branched off `ros2` on https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1184 and now has a dedicated branch.

Use new foxy branch

---

release-repo-scripts/new_ignition_release_repos.bash

Updating script introduced in #310 so that the newly created repository has a `main` branch instead of `master`.
I believe most of our infra supports either, but the nightly releases requires `--release-repo-branch main`:
https://github.com/ignition-tooling/release-tools/blob/34375f7489764209c6e934bcf06ba65bf621eb67/jenkins-scripts/dsl/ignition_collection.dsl#L623-L624
I created this repository with the updated script:
https://github.com/ignition-release/ign-math7-release/

Create new release repos with main branch

---

jenkins-scripts/dsl/brew_release.dsl
jenkins-scripts/dsl/gazebo.dsl

macOS Big Sur (11.0) has been released, and [homebrew is no longer building bottles for high sierra](https://github.com/Homebrew/brew/pull/9054/files#diff-b5752027e688b330ed260dd944dbf2674c98c1b44355282d93ead10f89dbc3fdL58-R58), so we will stop building them as well. Once we have configured a macOS catalina machine, we can instruct it to build bottles for that platform as well.
I've also removed a bit of outdated logic from `gazebo.dsl`.

Stop building homebrew bottles for High Sierra

---

jenkins-scripts/docker/lib/boilerplate_prepare.sh

There are problems related to nodes disk space since sometimes builds are so big (gazebo and/or subt can go over 10Gb) that the disk space available is not enough. Other times the Jenkins configuration disables the node under 10Gb of free space. For trying to avoid that situation the PR does two thigns:
* Reduce the percents of the disk usage to trigger cleaning.
* Add a new method to find build/ directories bigger than 5Gb (gazebo packages are under this) as a final resource. These directories are from time to time left when a build failed and in the case of Gazebo can be up to 14Gb.

Improve free of disk space: reduce limits and clean /build dirs

---

jenkins-scripts/lib/gazebo-base-windows.bat
jenkins-scripts/lib/gazebo9_10-base-windows.bat

Failing Windows jobs: https://build.osrfoundation.org/job/gazebo-ci-pr_any-windows7-amd64/3062/consoleFull
```
Downloading http://download.qt-project.org/official_releases/jom/jom.zip
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2020-11-18 08:18:39--  http://download.qt-project.org/official_releases/jom/jom.zip
Resolving download.qt-project.org... 77.86.229.90
Connecting to download.qt-project.org|77.86.229.90|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://mirrors.ocf.berkeley.edu/qt/official_releases/jom/jom_1_1_3.zip [following]
--2020-11-18 08:18:39--  https://mirrors.ocf.berkeley.edu/qt/official_releases/jom/jom_1_1_3.zip
Resolving mirrors.ocf.berkeley.edu... 169.229.226.30
Connecting to …
```

Replace jom path to new location

---

jenkins-scripts/dsl/gazebo_ros_pkgs.dsl

gazebo8 is EOL, so disable its use in CI for kinetic.
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_gazebo_ros_pkgs&build=713)](https://build.osrfoundation.org/job/_dsl_gazebo_ros_pkgs/713/) https://build.osrfoundation.org/job/_dsl_gazebo_ros_pkgs/713/
~~~
Unreferenced items:
GeneratedJob{name='ros_gazebo8_pkgs-ci-default_kinetic-xenial-amd64'}
GeneratedJob{name='ros_gazebo8_pkgs-ci-pr_any_kinetic-xenial-amd64'}
GeneratedJob{name='ros_gazebo8_pkgs-install_pkg_kinetic-xenial-amd64'}
Disabled items:
GeneratedJob{name='ros_gazebo8_pkgs-install_pkg_kinetic-xenial-amd64'}
GeneratedJob{name='ros_gazebo8_pkgs-ci-pr_any_kinetic-xenial-amd64'}
GeneratedJob{name='ros_gazebo8_pkgs-ci-default_kinetic-xenial-amd64'}
~~~

gazebo_ros_pkgs.dsl: stop testing gazebo8

---

jenkins-scripts/lib/_homebrew_cleanup.bash

It's now required for non-interactive calls to brew list.
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_transport9-install_bottle-homebrew-amd64&build=55)](https://build.osrfoundation.org/job/ignition_transport9-install_bottle-homebrew-amd64/55/) https://build.osrfoundation.org/job/ignition_transport9-install_bottle-homebrew-amd64/55/
~~~
+++ /usr/local/bin/brew list
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
~~~

Call brew list with --formula

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

I'm not sure where this script is being run, but it looks like there may be other libraries in the same workspace (maybe left-overs from previous builds?). This causes occasional build failures in case the other libraries need nightlies for example.
This change makes sure that only the dependencies for the branch being tested are installed. See these 2 test builds:
[Without this PR](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/4410/consoleFull), an `ign-gazebo` build is also installing dependencies for many other libraries that happen to be in the workspace. In this case the build didn't fail because the other libraries happened to be compatible.
```
++++ sort -u ./ign_rendering/.github/ci/packages.apt ./ign_fuel_tools/.github/ci/packages.apt …
```

👩‍🌾 Only install dependencies from library being tested

---

jenkins-scripts/lib/project-install-homebrew.bash

The other tests give more informative feedback.
Compare the output from the master branch:
* https://build.osrfoundation.org/view/ign-blueprint/job/ignition_launch1-install_bottle-homebrew-amd64/174/console
~~~
#BEGIN SECTION: brew doctor analysis
+ brew missing
+ brew missing
+ brew doctor
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
ignition-launch1
Warning: Broken symlinks were found. Remove them with `brew …

Check brew doctor after other tests

---

jenkins-scripts/dsl/_configs_/OSRFWinCompilationAnyGitHub.groovy
jenkins-scripts/dsl/core.dsl
jenkins-scripts/ign_common-default-devel-windows-amd64.bat
jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat
jenkins-scripts/lib/windows_env_vars.bat
jenkins-scripts/lib/windows_library.bat
jenkins-scripts/vcpkg-bootstrap.bat

This should close https://github.com/ignition-tooling/release-tools/issues/340 (also help in https://github.com/ignitionrobotics/ign-common/issues/122). The idea is to define a which snapshot of vcpkg we are using (it matches with its github releases), use it statically until we find a reason to upgrade. To help with the upgrade, this PR creates two jobs:
*  ` _vcpkg_testing_snapshot`: uses a special label `wintesting` to run the upgrade of the snapshot together with trying to build `ign-gazebo` (which should exercise most of the ignition software given its dependency chain).
* `_vcpkg_update_snapshot`: the job has a parameter to inject a node name to run the upgrade of vcpkg (beware, takes long time). Instead of making it to run in all nodes in parallel I decided to go with the selected …

vcpkg snapshot support: check and upgrade

---

jenkins-scripts/ign_fuel-tools-default-devel-windows-amd64.bat
jenkins-scripts/ign_msgs-default-devel-windows-amd64.bat
jenkins-scripts/sdformat-default-devel-windows-amd64.bat

Some builds are failing due to missing tinyxml2 dependency defined in ignition libraries coming from msgs. See https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-windows7-amd64/523/.
This PR adds the dependency to missing ones.
Still needs testing but merging should not break anything.

Missing tinyxml2 vcpkg dependencies from ign-msgs

---

jenkins-scripts/ign_common-default-devel-windows-amd64.bat

This change is being made based on the comments in
https://github.com/ignition-tooling/release-tools/pull/347/files#r529115468
and the failure of several jobs to find tinyxml2 on the windows_nuc
agent.

Add additional dependencies for ignition-tooling components.

---

jenkins-scripts/docker/bloom-debbuild.bash

Missing variable to get right the python version inside bloom:
Before: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros-ign-gazebo-bloom-debbuilder&build=12)](https://build.osrfoundation.org/job/ros-ign-gazebo-bloom-debbuilder/12/)
After: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros-ign-gazebo-bloom-debbuilder&build=14)](https://build.osrfoundation.org/job/ros-ign-gazebo-bloom-debbuilder/14/)

Declare ENABLE_ROS in bloom-debbuild

---

jenkins-scripts/dsl/core.dsl
jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat
jenkins-scripts/ign_gui-default-devel-windows-amd64.bat
jenkins-scripts/ign_launch-default-devel-windows-amd64.bat
jenkins-scripts/ign_rendering-default-devel-windows-amd64.bat
jenkins-scripts/lib/colcon-default-devel-windows.bat
jenkins-scripts/lib/windows_library.bat
jenkins-scripts/vcpkg-bootstrap.bat

The PR implements the use of [`--overlay-ports` parameter in vcpkg](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) to inject our custom ogre2 port available at https://github.com/osrf/vcpkg-ports . Until now, the package was manually copied to the ports/ directory.
We don't need the variable `DEPEN_OSRF_PKGS` anymore so I moved all ogre2 references to `DEPEN_PKGS`. The PR still update the master branch of the vcpkg-ports on every installation to catch new changes.
The PR includes a bit of Groovy to display the Updated node for https://build.osrfoundation.org/job/_vcpkg_update_snapshot/.
Tested here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_vcpkg_update_snapshot&build=9)](https://build.osrfoundation.org/job/_vcpkg_update_sn …

Migrate vcpkg to use --overlay-ports parameter for osrf/vcpkg-ports

---

jenkins-scripts/lib/windows_env_vars.bat

Found problems trying to use `2020.01` snapshot and my debugging about what failed when I tested it discovered that I was using `2020.11` for testing instead of `2020.01`. I [tried to backport fixes](https://github.com/osrf/vcpkg-ports/pull/2) for `2020.01` snapshot bug but the thing became not easy and I don't really have a good reason not to use the latest snapshot for vcpkg.
[
I've provisioned](https://build.osrfoundation.org/job/_vcpkg_update_snapshot/28/) the `windows_nuc` agent and run an ign-rendering test: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_vcpkg_migration_ign_rendering-ci-win&build=1)](https://build.osrfoundation.org/job/_test_vcpkg_migration_ign_rendering-ci-win/1/)
The list of external dependencies versions up to ign-rendering:
```
$ …
```

Snapshot 2020.11 for ignition vcpkg

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy

Should workaround https://github.com/ignition-tooling/release-tools/issues/242 in two ways:
* If the [my comment about](https://github.com/ignition-tooling/release-tools/issues/242#issuecomment-746099647) `<spec>` and `<cron>` is correct and there is a miss-configuration in the XML that leads to polling operations, I've verified that with the definition of `<cron>` as empty there is no default value anymore coming to crontab when opening the Jenkins GUI manually.
* I'm adding a default `sha1` value here following instructions of the Jenkins plugin [that explains](https://github.com/jenkinsci/ghprb-plugin):
> If you want to manually build the job, in the job setting check This build is parameterized and add string parameter named sha1 with a default value of master.

Add sha1 default branch in -pr- and fix XML configuration for crontab polling

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

boost 1.75 is exposing icu4c libraries as transitive dependencies (see https://github.com/osrf/homebrew-simulation/issues/1235). I think this is incorrect, but for now add `/usr/local/opt/icu4c/lib` to the `LIBRARY_PATH`.
Without this fix: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics-ci-ign-physics3-homebrew-amd64&build=9)](https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics3-homebrew-amd64/9/) https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics3-homebrew-amd64/9/
With this fix: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics-ci-ign-physics3-homebrew-amd64&build=10)](https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics3-homebrew-amd64/10/) …

brew: add icu4c library path

---

jenkins-scripts/lib/homebrew_bottle_creation.bash

:x11 requirements are deprecated (https://github.com/osrf/homebrew-simulation/issues/1227), skip tap syntax checking for now
Our bottle builds are failing the tap syntax check, for example from https://github.com/osrf/homebrew-simulation/pull/1238:
*  [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder%2Flabel%3Dosx_mojave&build=139)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_mojave/139/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_mojave/139/console

brew bottles: skip tap syntax

---

jenkins-scripts/sdformat-default-devel-windows-amd64.bat

We still have some scripts that relies on the old behaviour of using tarballs + configure.bat files. Here I'm enabling colcon + vcpkg to sdformat10 and above. This should fix the problem with tinyxml2.
Tested here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat10-windows7-amd64&build=21)](https://build.osrfoundation.org/job/sdformat-ci-sdformat10-windows7-amd64/21/)
The failing tests can come from the fact of compiling ign-tools support (in gazebodistro file) that was previously ignored.
//cc @scpeters @azeey

Use colcon + vcpkg for sdformat10 and newer

---

release.py

The `download_release_repository` method has logic for correcting the branch name of the release repository, but the result is not saved, and an incorrect value may be passed to jenkins. This returns the updated branch name and overwrites the previous value.

release.py: use correct release repo branch

---

jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ignition_collection.dsl

We always have the dilemma with version 1 of whether to omit the 1 or not. I'm just following the `ign-plugin` pattern and omitting 1... Hey, maybe we'll never need a version 2 :wink:

Ignition Utils will be version 1 on Edifice

---

jenkins-scripts/lib/homebrew_bottle_creation.bash

The logic for auto-tapping has changed recently in https://github.com/Homebrew/brew/pull/10366, so we need to explicitly re-tap it. This should help with https://github.com/osrf/homebrew-simulation/pull/1310

Explicitly tap homebrew-test-bot

---

jenkins-scripts/lib/windows_env_vars.bat

Needed to avoid internal compiler errors when compiling large packages such as ogre or qt.

Use VCPKG_MAX_CONCURRENCY to limit compilation threads on Windows

---

jenkins-scripts/docker/lib/docker_run.bash
jenkins-scripts/lib/check_graphic_card.bash

The pull request changes two things:
* Prefer nvidia in nodes with two cards installed. d0eeb3e 
* Auto select the nvidia/docker integration from current available options 
Testing:
* r2d2 node (nvidia-docker): [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_ignition_rendering-ci-default-bionic-amd64&build=11)](https://build.osrfoundation.org/job/_test_ignition_rendering-ci-default-bionic-amd64/11/)
* optimus node (nvidia-container-toolkit) [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_ignition_rendering-ci-default-bionic-amd64&build=10)](https://build.osrfoundation.org/job/_test_ignition_rendering-ci-default-bionic-amd64/10/)
* drogon node (nvidia-container-toolkit) [![Build …

Improve nvidia detection and docker integration

---

jenkins-scripts/dsl/ignition.dsl

Together with the merge of https://github.com/ignitionrobotics/ign-gazebo/pull/585 it will enable the Windows CI on ignition-gazebo.
Partially fix https://github.com/ignition-tooling/release-tools/issues/351

Enable ignition-gazebo CI on Windows

---

jenkins-scripts/dsl/ignition.dsl

The ignition-gazebo pr job needs to be restricted to the main branch since it does not work on other previous released.

Restrict ign_gazebo-pr to main branch

---

jenkins-scripts/docker/lib/boilerplate_prepare.sh
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/docker/lib/docker_run.bash
jenkins-scripts/lib/check_graphic_card.bash

This should fix the problems on current optimus introduced in #386, since `nvidia-toolkit-container` does not install `ENV NVIDIA_VISIBLE_DEVICES` variables needed to expose gpus into the container.
Other improvements:
* Remove the need for `NVIDIA_DOCKER2_NODE` in nodes configuration. Autodetected from packages installed.
* Remove the `libglvnd` installation. Testing seems not to need it.
Testing:
* Optimus [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_ignition_rendering-ci-default-bionic-amd64&build=22)](https://build.osrfoundation.org/job/_test_ignition_rendering-ci-default-bionic-amd64/22/)
* Drogon (one failing, flaky) [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_ignition_rendering-ci-default-bionic-amd64&build=23)](https:// …

Auto detect nvidia support

---

README.md
release.py

The PR removes death code using argument  `--ignition-repo` (there is no release information outside of `ignition-release` if I'm not wrong). It also enable the auto calculation of `package-alias` for anything package starting with `ign-` unless the option `---no-ignition-auto` is enabled (to cover hidden corner cases).

Simplify release.py for ignition releases

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/docker/lib/docker_run.bash

The `libglvnd` was removed in #392 and seems like some nodes are being failing since them when running the gazebo classic install job (does not seems to happen in ign-rendering CI). The PR installed it again and simplifies the nvidia-docker2 calls.
**Tested in:**
* drogon [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_gazebo-install-gazebo9_pkg-xenial-amd64&build=3)](https://build.osrfoundation.org/job/_test_gazebo-install-gazebo9_pkg-xenial-amd64/3/)
* optimus [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_gazebo-install-gazebo9_pkg-xenial-amd64&build=4)](https://build.osrfoundation.org/job/_test_gazebo-install-gazebo9_pkg-xenial-amd64/4/)
* r2d2 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_gazebo-ins …

Use libglvnd to handle GL calls correctly in GPU docker

---

jenkins-scripts/lib/repository_uploader.bash

There are still some references to nightly hg tag in repository_uploader. Replace them by git.

Replace hg references by git in repository_uploader

---

jenkins-scripts/docker/ign_common-compilation.bash
jenkins-scripts/docker/ign_fuel-tools-compilation.bash
jenkins-scripts/docker/ign_gazebo-compilation.bash
jenkins-scripts/docker/ign_gui-compilation.bash
jenkins-scripts/docker/ign_launch-compilation.bash
jenkins-scripts/docker/ign_physics-compilation.bash
jenkins-scripts/docker/ign_sensors-compilation.bash
jenkins-scripts/docker/ign_transport-compilation.bash
jenkins-scripts/docker/sdformat-compilation.bash

Ubuntu CI is already installing dependencies from nightlies, so we don't need to build them from source too.
This should save lots of CI time.
If this gets in, I'll decline #379 and update #333

Don't build dependencies from source on CI, use nightlies

---

jenkins-scripts/dsl/ignition_collection.dsl

The release script was updated in https://github.com/ignition-tooling/release-tools/pull/393/, but the nightly invocation wasn't, which is making the nightly scheduler unstable:
https://build.osrfoundation.org/job/ignition-edifice-nightly-scheduler/158/
For example:
```
releasing ign-cmake3 (as ignition-cmake3) from branch main --ignition-repo
usage: release.py [-h] [--dry-run] [-u] [-a PACKAGE_ALIAS]
[-b RELEASE_REPO_BRANCH] [-r RELEASE_VERSION]
[--no-sanity-checks] [--no-generate-source-file]
[--no-ignition-auto] [--upload-to-repo UPLOAD_TO_REPOSITORY]
[--extra-osrf-repo EXTRA_REPO]
[--nightly-src-branch NIGHTLY_BRANCH]
package version jenkins_token
release.py: error: unrecognized arguments: --ignition-repo
MARK_AS_UNSTABLE
- done
```
---
https://github.com/osrf/buildfarmer/issues/156

👩‍🌾 Fix nightlies, use latest script

---

jenkins-scripts/dsl/extra.dsl

Easy change to make UPLOAD_TO_REPO a parameter instead of defaulting to stable all the times.
Tested here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_extra&build=361)](https://build.osrfoundation.org/job/_dsl_extra/361/)

Support to user input in UPLOAD_TO_REPO for extra.dsl

---

jenkins-scripts/lib/_homebrew_base_setup.bash
jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Fixes https://github.com/osrf/homebrew-simulation/issues/1343
We usually disable warnings coming from upstream libraries, so I think it makes sense to suppress warnings from upstream tooling as well.
---
https://github.com/osrf/buildfarmer/issues/161

👩‍🌾 Suppress Homebrew Ruby warnings

---

jenkins-scripts/lib/homebrew_bottle_creation.bash

Similar to #401. Needed to fix bottle build jobs:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder&build=285)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/285/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/285/
There's not an easy way to test this before merging.

Suppress chdir brew warning during bottle builds

---

jenkins-scripts/dsl/ignition.dsl

Following https://github.com/ignition-tooling/release-tools/pull/389#issuecomment-786921854

Use utils1 as name for the debbuilder

---

jenkins-scripts/dsl/ignition_collection.dsl
release.py

From dry-run test of nightly build scheduler:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition-edifice-nightly-scheduler&build=169)](https://build.osrfoundation.org/job/ignition-edifice-nightly-scheduler/169/) https://build.osrfoundation.org/job/ignition-edifice-nightly-scheduler/169/
~~~
releasing ign-utils (from branch main
Traceback (most recent call last):
File "./scripts/release.py", line 615, in <module>
go(sys.argv)
File "./scripts/release.py", line 517, in go
sanity_checks(args, repo_dir)
File "./scripts/release.py", line 307, in sanity_checks
sanity_package_name(repo_dir, args.package, args.package_alias)
File "./scripts/release.py", line 212, in sanity_package_name
error("Error in changelog package name or alias: " + line.decode())
AttributeError: …

Fix ign-utils1 nightly build

---

jenkins-scripts/docker/lib/debbuild-base.bash

I've noticed some debbuild jobs failing at the `wget` step, but there is little debugging info because `wget` is called with `--quiet`:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-msgs6-debbuilder&build=244)](https://build.osrfoundation.org/job/ign-msgs6-debbuilder/244/) https://build.osrfoundation.org/job/ign-msgs6-debbuilder/244/
~~~
+ wget --quiet -O orig_tarball https://osrf-distributions.s3.amazonaws.com/ign-msgs/releases/ignition-msgs6-6.4.0.tar.bz2
Build step 'Execute shell' marked build as failure
~~~
This adds a second invocation of `wget` without `--quiet` if the first one fails:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-msgs6-debbuilder&build=252)](https://build.osrfoundation.org/job/ign-msgs6-debbuilder/252/) …

debbuild-base: run wget without --quiet if first call fails

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

The qt@5 alias has been replaced by the qt@5 formula so we need to update some logic in our scripts. I believe all ign-gazebo homebrew builds are failing due to this issue.

brew: fix linking to keg-only qt@5

---

jenkins-scripts/dsl/sdformat.dsl

Not sure where this comes from or if we modified it somehow but seems like there are conditions but not actions inside the conditional steps.
Tested DSL here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_sdformat&build=988)](https://build.osrfoundation.org/job/_dsl_sdformat/988/).
retry failed build here: https://build.osrfoundation.org/job/sdformat-ci-pr_any-ubuntu_auto-amd64/1632/console

Remove DSL code for conditionalsteps in sdformat (seems empty)

---

jenkins-scripts/docker/lib/debbuild-base.bash

There are some platforms where the certificate of S3 is not valid, making wget to fail. It happened in several Debian builds and at least in Focal/armhf. The PR ignores the cert only in the given cases, I did not found a way of importing it to the system. 
Tested:
* Failing [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-plugin-debbuilder&build=611)](https://build.osrfoundation.org/job/ign-plugin-debbuilder/611/)
* Passing [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-plugin-debbuilder&build=614)](https://build.osrfoundation.org/job/ign-plugin-debbuilder/614/)
Found during the Edifice release #421

Workaround on S3 AWS cert  for platforms not supporting it

---

jenkins-scripts/docker/lib/debbuild-base.bash

New versions of devscripts in Debian Sid left some files in the source code directory making the builds to fail. Just remove them before continuing.
Tested:
* Fail [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-plugin-debbuilder&build=613)](https://build.osrfoundation.org/job/ign-plugin-debbuilder/613/)
* Success [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-plugin-debbuilder&build=615)](https://build.osrfoundation.org/job/ign-plugin-debbuilder/615/)
Found during the Edifice release https://github.com/ignition-tooling/release-tools/issues/421

Remove artifacts from mk-build-deps in new versions

---

jenkins-scripts/dsl/sdformat.dsl

The OSRFGitHub.create() function takes an optional branch name parameter that defaults to "master". We now need to explicitly pass "main" in these places.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-main-bionic-amd64&build=1)](https://build.osrfoundation.org/job/sdformat-ci-main-bionic-amd64/1/) https://build.osrfoundation.org/job/sdformat-ci-main-bionic-amd64/1/
~~~
Fetching upstream changes from https://github.com/osrf/sdformat.git
> git fetch --tags --progress https://github.com/osrf/sdformat.git +refs/heads/*:refs/remotes/origin/* # timeout=10
> git rev-parse origin/master^{commit} # timeout=10
> git rev-parse master^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
~~~

sdformat.dsl: fix some main branch CI

---

jenkins-scripts/ign_fuel-tools-default-devel-windows-amd64.bat
jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat
jenkins-scripts/ign_launch-default-devel-windows-amd64.bat

I'm improving the windows support on Ign fuel tools, I believe that `openssl` is not installed that's why we are getting this errors on the buildfarm:
```bash
libcurl: (1) Protocol "https" not supported or disabled in libcurl
```
Related with:
- issue https://github.com/ignitionrobotics/ign-fuel-tools/issues/105
- PR https://github.com/ignitionrobotics/ign-fuel-tools/pull/178
@j-rivero 
Signed-off-by: Alejandro Hernández <ahcorde@gmail.com>

Install openssl on Windows

---

jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/ign_cmake-default-devel-windows-amd64.bat
jenkins-scripts/ign_common-default-devel-windows-amd64.bat
jenkins-scripts/ign_fuel-tools-default-devel-windows-amd64.bat
jenkins-scripts/ign_math-default-devel-windows-amd64.bat
jenkins-scripts/ign_msgs-default-devel-windows-amd64.bat
jenkins-scripts/ign_plugin-default-devel-windows-amd64.bat
jenkins-scripts/ign_rndf-default-devel-windows-amd64.bat
jenkins-scripts/ign_tools-default-devel-windows-amd64.bat
jenkins-scripts/lib/colcon-default-devel-windows.bat

:farmer:  To solve the failing of ci windows on main I just moved the build to colcon (part of #412) 
Before: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_fuel-tools-ci-main-windows7-amd64&build=19)](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-main-windows7-amd64/19/)
After: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_fuel-tools-ci-main-windows7-amd64&build=20)](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-main-windows7-amd64/20/)
The PR includes a fix for all SCRIPT_DIR variables, Windows does not like quotes.

Migrate fuel tools windows build to colcon

---

release.py

The PR adds the `--only-bump-revision-linux` that allows to call Jenkins on revision bumps (those only changing build metadata no source code from the application) without uploading tarballs.
The current code is a bit messy and to get the tarball name that was finally uploaded in the first time it is needed to generate locally the tarball, although it is not finally uploaded. 
recommendation: enable w=1 to see differences in code https://github.com/ignition-tooling/release-tools/pull/394/files?w=1

Implement --only-bump-revision-linux in release.py

---

jenkins-scripts/dsl/ignition.dsl

This is a workaround for a bug in the way we use gzdev inside docker so changes in its configuration are not propagated to docker images thus fails occur. The PR is a workaround, it adds the `INVALIDATE_DOCKER_CACHE` variable that will make jobs not to use docker images cached. It is doing it in all the ignition linux jobs, not very elegant but my impression that it the workload would be manageable by the buildfarm.
Tested locally:
```bash
release-tools/jenkins-scripts/dsl on  edifice_docker_invalidation [?] ❯ grep INVALIDATE * 
...
ignition_transport-ci-main-xenial-amd64.xml:export INVALIDATE_DOCKER_CACHE=true
ignition_transport-ci-pr_any-ubuntu_auto-amd64.xml:export INVALIDATE_DOCKER_CACHE=true
ignition_utils-abichecker-any_to_any-ubuntu_auto-amd64.xml:export …
```

Invalidate docker cache to avoid gzdev problems on Fortress

---

jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Upstream bug fixed in newer versions available in backports repo.
Close: https://github.com/ignition-release/gazebo11-release/issues/7
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo11-debbuilder&build=69)](https://build.osrfoundation.org/job/gazebo11-debbuilder/69/)

Workaround Buster dwz problem by using backports version

---

jenkins-scripts/dsl/ignition.dsl

Clean up the logic for disabling jobs that don't work on xenial. Some of the recently added jobs are not properly disabled on xenial:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_common4-install-pkg-xenial-amd64&build=6)](https://build.osrfoundation.org/job/ignition_common4-install-pkg-xenial-amd64/6/) https://build.osrfoundation.org/job/ignition_common4-install-pkg-xenial-amd64/6/
Testing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition&build=1143)](https://build.osrfoundation.org/job/_dsl_ignition/1143/) https://build.osrfoundation.org/job/_dsl_ignition/1143/
~~~
Added items:
GeneratedJob{name='ignition_utils-install-pkg-bionic-amd64'}
...
Unreferenced items: …

ignition.dsl: cleanup logic for xenial support

---

jenkins-scripts/dsl/ignition.dsl

Fixing a typo from #150 
Test run: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition&build=1147)](https://build.osrfoundation.org/job/_dsl_ignition/1147/)
See how the Windows jobs are enabled now: https://github.com/osrf/buildfarmer/blob/main/Ignition.md
---
https://github.com/osrf/buildfarmer/issues/181

👩‍🌾 Fix Windows job disable logic

---

jenkins-scripts/dsl/ignition.dsl

Tested with: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition&build=1150)](https://build.osrfoundation.org/job/_dsl_ignition/1150/)
Now I see the `ign-gazebo5` branch whitelisted under the trigger advanced settings here: https://build.osrfoundation.org/job/ign_gazebo-pr-win/configure
---
https://github.com/osrf/buildfarmer/issues/181

👩‍🌾 Windows CI for ign-gazebo5

---

README.md
release-repo-scripts/bump_dependency.bash

I used iterations of this script to open all the pull requests connected to https://github.com/ignition-tooling/release-tools/issues/331, except for the `gzdev` one.
The script still needs a lot of work, but it's a great improvement over doing all of that by hand. Some TODO items that stand out:
* The script relies on most of the PRs not being merged. After https://github.com/ignition-tooling/gazebodistro/pull/13 was merged, I had to pin to the previous commit.
* Running the script twice shouldn't change the output.
* The `release-tools` part still has a manual step
* Updating `gzdev` is not included yet
* ~~Updating `ign-edifice`, `ign-edifice-release` and `ign-edifice` on homebrew~~ ff4ac9ce2f6dac66327c9df4ba938410ee88b42e
* The coloring could be more consistent to make it easier to …

Script to bump a library's version in the upcoming collection

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/gazebo.dsl
jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/sdformat.dsl

Gazebo 7 & 10 have reached EOL a while back, and took `ign-math2`, `ign-transport2` and `libsdformat4` with them.
See [announcement](https://community.gazebosim.org/t/gazebo-7-10-officially-end-of-life/799) and [support table](https://github.com/ignitionrobotics/docs/blob/master/tools/versions.md)

🏁 Gazebo 7 & 10 EOL

---

jenkins-scripts/ign_fuel-tools-default-devel-windows-amd64.bat

Failing here: https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-windows7-amd64/649/consoleFull#-102647437aa60f765-a60a-427d-900c-dc128ab22287
This PR: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_fuel-tools-ci-pr_any-windows7-amd64&build=651)](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-windows7-amd64/651/)

Declare protobuf dependency on fuel-tools for Windows

---

jenkins-scripts/dsl/extra.dsl

The PR adds the ogre2.2 debbuilder, test here https://build.osrfoundation.org/job/ogre-2.2-debbuilder/.
Also moves the current debbuilder under the fork organization.

Ogre 2.2 debbuilder. Fixing forks debbuilders

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

See discussion in the following issue:
https://github.com/osrf/homebrew-simulation/issues/1477
This was needed by the gazebo11 test in
https://github.com/osrf/homebrew-simulation/pull/1479

brew: set CPATH if tbb@2020 is a dependency

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

The `tbb@2020` formula in homebrew-core is deprecated, so use `tbb@2020_u3` from our tap instead.
Testing: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-ci-gazebo11-homebrew-amd64&build=65)](https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/65/) https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/65/
This is a follow-up to #465.

Use tbb@2020_u3 instead of tbb@2020

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

The PR should work to fix the incident with the [expired ROS keys](https://docs.google.com/document/d/1ze0h6bmEwJfE0Xb2Nw9vuy20mselG08nGQLcqM1ui0U/edit). It is invalidating the current docker cache in the nodes by modifying the docker commands before the first apt-get update is in place.
Tested:
* ROS1: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros_gazebo_pkgs-install_pkg_stable_ros_melodic-bionic-amd64&build=929)](https://build.osrfoundation.org/view/all/job/ros_gazebo_pkgs-install_pkg_stable_ros_melodic-bionic-amd64/929/)
* ROS2: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros2_gazebo_pkgs-install_pkg_stable_ros_eloquent-bionic-amd64&build=274)](https://build.osrfoundation.org/view/all/job/ros2_gazebo_pkgs-install_pkg_stable_ros_eloqu …

Update ROS apt setup after expired keys

---

jenkins-scripts/ign_rendering-default-devel-windows-amd64.bat

This is an attempt to resolve the following error as seen on the build
machine Locutus:
```
Could not find pkg-config information for IgnOGRE.  It was not provided by
the find-module for the package, nor was it explicitly passed into the call
to ign_find_package(~).  This is most likely an error in this project's use
of ign-cmake.
Call Stack (most recent call first):
CMakeLists.txt:66 (ign_find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR)
```

Boost is required to build ign-rendering.

---

jenkins-scripts/dsl/gazebo_ros_pkgs.dsl

Dashing's support window has ended so we no longer need to regenerate
gazebo_ros_pkgs for it.
Dashing is still referenced in a few scripts, mostly in version and distribution maps. @j-rivero would you prefer that I clean those up or leave them there for now?
```
jenkins-scripts/lib/dependencies_archive.sh
246:      dashing)
bloom/README.md
10:   $ BLOOM_RELEASE_REPO_BASE=https://github.com/osrf/ bloom-release --no-pull-request --rosdistro dashing --track dashing gazebo11_ros2_pkgs
18:   $ ros_gazebo_pkgs-release.py.bash 3.4.4 https://github.com/osrf/gazebo11_ros2_pkgs-release dashing xxx -r 1 --dry-run
bloom/release-bloom.py
18:UBUNTU_DISTROS_IN_ROS2 = {'dashing': ['bionic'],
jenkins-scripts/dsl/_configs_/Globals.groovy
22:                     'dashing'  : ['bionic'] ,
31: …
```

Stop generating jobs for Dashing.

---

jenkins-scripts/dsl/_configs_/Globals.groovy

Following https://github.com/ignition-tooling/release-tools/pull/462#discussion_r632179850 .
A testing run for Gazebo9 (currently broken abi checker on Xenial) after changing DISTRO value manually to bionic:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-abichecker-any_to_any-ubuntu_auto-amd64&build=884)](https://build.osrfoundation.org/job/gazebo-abichecker-any_to_any-ubuntu_auto-amd64/884/)

Migrate ABI checker default platform from Xenial to Bionic

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy
jenkins-scripts/dsl/sdformat.dsl

See https://community.gazebosim.org/t/sdformat-moved-to-the-ignition-github-organization/994
I was hoping this wouldn't be necessary and CI would just keep working :confused: 
These are just the minimal changes to get CI running for SDF, there are more bits to change in other places too.
Generated in https://build.osrfoundation.org/job/_dsl_sdformat/1025/
You can see PR builds running, for example: https://github.com/ignitionrobotics/sdformat/pull/608
---
https://github.com/osrf/buildfarmer/issues/207

👩‍🌾 Move SDFormat to ignitionrobotics org

---

jenkins-scripts/lib/dependencies_archive.sh

Removed some versions according to this list:
https://github.com/ignitionrobotics/docs/blob/bd79c6fe26d8ce043d19f34b8562a3c5afe43322/tools/versions.md
I purposely didn't remove ROS versions, which is done in #475, and didn't remove Xenial, which is done in #462.
This PR is meant to make #462 a bit smaller.
---
https://github.com/osrf/buildfarmer/issues/207

👩‍🌾 Remove some EOL versions from dependencies_archive

---

bloom/README.md
bloom/release-bloom.py
jenkins-scripts/docker/lib/boilerplate_prepare.sh
jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/gazebo_ros_pkgs.dsl
jenkins-scripts/dsl/ros1_ign_bridge.dsl
jenkins-scripts/lib/dependencies_archive.sh

Galactic was just missing in a couple of places.
Dashing, Eloquent and Kinetic are EOL.
Dashing removal started in #471.
Kinetic is also being removed in #462, but that PR may take a bit more massaging for Xenial, so I added just those changes here. Hopefully this makes it easier to review.
---
https://github.com/osrf/buildfarmer/issues/207

👩‍🌾 Add ROS Galactic, remove Dashing, Eloquent and Kinetic

---

jenkins-scripts/dsl/_configs_/GenericCompilation.groovy
jenkins-scripts/dsl/_configs_/OSRFBrewInstall.groovy
jenkins-scripts/dsl/_configs_/OSRFLinuxInstall.groovy

There's enough traffic in some jobs that we often lose builds from the same day. Increasing 5x, we can reduce if it starts to take up too much space.

👩‍🌾 Keep last 75 builds instead of 15

---

one-line-installations/gazebo.sh

The caskroom tap is deprecated, so use `homebrew/cask/xquartz` instead. Also check for two different pkg names with `pkgutil`, as the homebrew cask uses a different name. This fix will allow us to bring t1000 back online:
* https://build.osrfoundation.org/computer/mac-t1000.catalina/

one-line gazebo.sh: use homebrew/cask/xquartz

---

jenkins-scripts/docker/lib/boilerplate_prepare.sh

There are some false positives of running gzservers from lingering
processes like: 'tee /tmp/ign/logs/gzserver_stdout.log'
This increases the precision of the regular expressions used to
detect running gzserver processes.
There is currently such a false-positive process running on drogon, so I have marked it offline:
* https://build.osrfoundation.org/computer/linux-aws_drogon.nv.xenial/

Use more precise regex to detect running gzserver

---

jenkins-scripts/lib/_homebrew_cleanup.bash

This causes problems for machines that get xquartz from a cask (like t1000).
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gui4-install_bottle-homebrew-amd64&build=268)](https://build.osrfoundation.org/job/ignition_gui4-install_bottle-homebrew-amd64/268/) https://build.osrfoundation.org/job/ignition_gui4-install_bottle-homebrew-amd64/268/
~~~
++ /usr/local/bin/brew untap homebrew/cask
Error: Refusing to untap homebrew/cask because it contains the following installed formulae or casks:
xquartz
~~~

Don't untap homebrew/cask

---

jenkins-scripts/dsl/ignition.dsl

I started the port of ign-launch in Windows https://github.com/ignitionrobotics/ign-launch/pull/120, The PR is targeting the `main` branch I enabled only this branch
Signed-off-by: ahcorde <ahcorde@gmail.com>

Enable ign-launch main branch on Windows

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash
jenkins-scripts/lib/project-install-homebrew.bash

The sdl formula was recently deprecated, which is breaking
out `brew doctor` checks for any formulae that install dartsim,
since sdl is an indirect dependency of dartsim, via open-scene-graph.
For now, skip `brew doctor` checks if sdl is installed.
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-pr_any-homebrew-amd64&build=5992)](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/5992/) https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/5992/
~~~
+ brew doctor
Warning: …

brew: skip brew doctor checks if sdl is installed

---

jenkins-scripts/ign_gui-default-devel-windows-amd64.bat

Signed-off-by: ahcorde <ahcorde@gmail.com>
This PR https://github.com/ignitionrobotics/ign-gui/pull/250 requires the package `qt5-winextras` when we use the tool `windeployqt.exe`

Added qt5-winextras to ign-gui

---

jenkins-scripts/dsl/ignition.dsl

Continuation from https://github.com/ignition-tooling/release-tools/pull/485.
I noticed that Windows CI is being triggered for all `ign-launch` branches. I think this is needed so it's only triggered for `main`. See https://github.com/ignition-tooling/release-tools/pull/453, which was the equivalent for `ign-gazebo`.
(also fixed some indentation)

Only trigger Windows CI for ign-launch main

---

jenkins-scripts/dsl/ignition_collection.dsl

This adds the nightly debbuild jobs to the corresponding Jenkins view:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition_collection&build=379)](https://build.osrfoundation.org/job/_dsl_ignition_collection/379/) https://build.osrfoundation.org/job/_dsl_ignition_collection/379/
* https://build.osrfoundation.org/view/ign-fortress/

ignition_collection.dsl: nightly debbuild in view

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy

I [found that there is an option to cancel any previous build](https://github.com/jenkinsci/ghprb-plugin/issues/379) from PRs in the Jenkins plugin that handle github integration with pull requests. 
Tested DSL with Gazebo in: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_gazebo&build=815)](https://build.osrfoundation.org/job/_dsl_gazebo/815/). I've verified that the configuration landed in GUI as expected but did not check that the plugin is indeed working.

Cancel any running previous builds from the same PR in -any- jobs

---

jenkins-scripts/lib/dependencies_archive.sh

Signed-off-by: ahcorde <ahcorde@gmail.com>
Related to https://github.com/ignitionrobotics/ign-math/pull/216. `libpython3-dev` is not installed. This PR adds the dependecy to build the Ignition math Python interfaces.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_math-ci-pr_any-ubuntu_auto-amd64&build=581)](https://build.osrfoundation.org/job/ignition_math-ci-pr_any-ubuntu_auto-amd64/581/)

Added libpython3-dev as a dependency of ign-math

---

jenkins-scripts/docker/debian-ratt-builder.bash
jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash
jenkins-scripts/docker/lib/_install_nvidia_docker.sh
jenkins-scripts/docker/lib/_ros_setup_buildsh.bash
jenkins-scripts/docker/lib/_ros_setup_catkin_make_isolated_buildsh.bash
jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/debbuild-bloom-base.bash
jenkins-scripts/docker/lib/debian-git-repo-base.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/docker/lib/docker_run.bash
jenkins-scripts/docker/lib/gazebo-base-default.bash
jenkins-scripts/docker/lib/generic-abi-base.bash
jenkins-scripts/docker/lib/generic-install-base.bash
jenkins-scripts/docker/lib/ros_debian-base-linux.bash
jenkins-scripts/docker/lib/simbody-release-base.bash
jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkgBase.groovy
jenkins-scripts/dsl/debian.dsl
jenkins-scripts/dsl/extra.dsl
jenkins-scripts/lib/dependencies_archive.sh

I have noticed some times when Jenkins fails to clear a workspace for a job. After investigating the machines over ssh, I have noticed the remaining folders contain files owned by `root`. This is caused by our use of the `root` user in the docker-based Ubuntu CI jobs. To avoid using the `root` user, this pull request creates a user in the Dockerfile that matches the current user, and switch to this user before using commands that touch the workspace folders.
I have tested with the following job:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-main-bionic-i386&build=14)](https://build.osrfoundation.org/job/sdformat-ci-main-bionic-i386/14/) https://build.osrfoundation.org/job/sdformat-ci-main-bionic-i386/14/
In order for this job to pass, I had to …

Use jenkins user inside docker jobs instead of root

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Following #494 
In upstart systems (r2d2), the USER variable is not set for Jenkins sessions. The PR sniff the user from the Jenkins process when that happen and USER is empty.
Failing: https://build.osrfoundation.org/job/ignition_gui3-install-pkg-bionic-amd64/366/console
With this branch : [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-ign-gazebo5-bionic-amd64&build=36)](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo5-bionic-amd64/36/)

Set USER var from PPID if USER is not present

---

jenkins-scripts/docker/lib/generic-abi-base.bash

Clean the cmake build folder in between compiling the source and destination branches. In particular, swig doesn't handle file renaming or moving, so it's better to start from a fresh build folder. I think this will fix the failing ABI build in https://github.com/ignitionrobotics/ign-math/pull/216
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_math-abichecker-any_to_any-ubuntu_auto-amd64&build=413)](https://build.osrfoundation.org/job/ignition_math-abichecker-any_to_any-ubuntu_auto-amd64/413/) https://build.osrfoundation.org/job/ignition_math-abichecker-any_to_any-ubuntu_auto-amd64/413/

abi script: clean build folder between builds

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Follow up to #494, there are some jobs that try to create folders under `$HOME`, but the Ubuntu docker builds seem to lack these permissions. The following two builds for example have many more test failures than normal:
* 549 new test failures [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-ci-gazebo9-bionic-amd64-gpu-nvidia&build=5)](https://build.osrfoundation.org/job/gazebo-ci-gazebo9-bionic-amd64-gpu-nvidia/5/) https://build.osrfoundation.org/job/gazebo-ci-gazebo9-bionic-amd64-gpu-nvidia/5/
* 22 new test failures [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-ign-gazebo4-bionic-amd64&build=91)](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo4-bionic-amd64/91/) …

docker script: chown home folder

---

jenkins-scripts/docker/lib/boilerplate_prepare.sh
jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

After #494 some problems appear with interactive apt-get installation. I have not detected yet what is exactly the root cause of the problems since not all builds are affected. I'm pretty sure that problems are related to the use of sudo and the change on environments context.
The PR changes:
* `ENV DEBIAN_FRONTEND noninteractive` is not doing its job after changing to non root accounts in docker. Seems like this configuration is not recommended so I've move it to use ARG https://github.com/moby/moby/pull/4035 . This seems insufficient to fix problems.
* Inject the `DEBIAN_FRONTEND` var inside `/root/.bashrc`. This did not fix the problem.
* Inject the variable directly in the debbuild-base line of installing packages. This fixed the problem although we can find other places were the …

Right frontend debian

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Map the USER value to shell variable. Needed for different projects to setup right permissions or other tasks.

Inject USER variable inside docker containers

---

README.md
source_changelog.bash

This helps generate changelog entries based on the git commit history. Originally posted by @chapulina in https://github.com/ignition-tooling/release-tools/issues/246#issuecomment-791833598. I've added it to `release-tools` since I've updated it to support `sdformat`.

Add source_changelog.bash script

---

jenkins-scripts/dsl/ignition_collection.dsl

After https://github.com/ignition-tooling/release-tools/issues/319, we don't need the prerelease repositories when building the nightlies.  This is changing https://github.com/ignitionrobotics/docs/pull/139 (Edifice).

Do not build nightly packages with prerelease repository enabled

---

jenkins-scripts/lib/windows_library.bat

Before the option of `--overlay-ports` exists in vcpkg, we were using a separate variable to declare OSRF vcpkg ports. `install_osrf_vcpkg_package`. That function was updating the overlay each time.  That is not the case anymore, that function is not in use and the same `install_vcpkg_package` can handle OSRF vcpkg ports. This PR removes the old function and move the update mechanism to current one.
Tested [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_gazebo-pr-win&build=3062)](https://build.osrfoundation.org/job/ign_gazebo-pr-win/3062/) 
Fixes #513

Update VCPKG_OSRF_DIR on every package installation

---

jenkins-scripts/lib/homebrew_formula_pullrequest.bash

The homebrew formulae with bumped major versions in fortress use `url` fields that point to the `git` repository rather than a tarball, so they don't have a `sha256` field (see https://github.com/osrf/homebrew-simulation/pull/1481 and https://github.com/osrf/homebrew-simulation/issues/1314). This caused our pull request updater job to fail (the one that is triggered by `release.py`):
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_pull_request_updater&build=957)](https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/957/) https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/957/
I've updated the logic to append a `sha256` field if the formula does not already contain such a field. If …

brew formula pr: Insert sha256 line if missing

---

jenkins-scripts/dsl/brew_release.dsl

Mojave will be unsupported by homebrew soon, so stop building these bottles, and build for bigsur instead. We already have one bigsur machine. After this, we can start upgrading Mojave machines to 10.16. Part of https://github.com/ignition-tooling/release-tools/issues/382.

brew_release.dsl: build bigsur bottles instead of mojave

---

release.py

Update the label expression for ARM releases to allow them to run on
hosts with the `linux-arm64` or `linux-armhf` labels respectively in
addition to hosts with the `large-memory` label.
Example ARM host: https://build.osrfoundation.org/computer/linux-ip-172-30-1-225.focal-00fdeb8a/

Allow ARM jobs to run on native arm hosts.

---

jenkins-scripts/dsl/ignition.dsl

Recent changes to the OSRF build farm have enabled scaling Linux agents.
With these we can increase the number of workers during release windows in order to build packages more efficiently. In order to take advantage of that we need to increase the concurrent build count. 8 concurrent jobs is both a doubling of the current count (inherited from OSRFUnixBase) and the max count of 4 amd64 and 4 arm64 workers in the scaling groups.

Increase max concurrent debbuild jobs to 8.

---

jenkins-scripts/dsl/sdformat.dsl

Use default `osx` label for sdformat brew CI jobs. Currently they are using `osx_mojave`, but there are no more machines in the build farm with that label, since they have had OS upgrades:
* https://build.osrfoundation.org/job/sdformat-ci-sdformat11-homebrew-amd64/

sdformat.dsl: use default label for brew CI

---

jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkgBase.groovy

Package builders were recently updated (#521) to take advantage of an
increased number of jenkins agents and this has surfaced a bug which has
been dormant due to the lack of concurrent jobs.
Ignition Fortress releases currently have 13 platform combinations of
different OS versions and CPU architectures. Which means that with the
previous archiveToKeep value of 10, if the eleventh debbuilder job runs
before the first is copied to the packaging server then the artifacts
will be cleaned up before they can be imported.
The new value of 25 is more than double the current number of target
platforms but is sadly still a constant and not based on the number of
target platforms. I still think it is a more sensible default than 10
given the current situation.
With this change we will have to …

Keep more package build artifacts.

---

jenkins-scripts/dsl/sdformat.dsl

Needed by https://github.com/ignitionrobotics/sdformat/pull/724

Add sdf12 to ABI checker

---

terminal-dashboard/table.bash

Fixes #505 . The reason because is not working in not really that we are not providing source packages for ignition-$collections but that [is not mandatory to include](https://www.debian.org/doc/debian-policy/ch-controlfields.html#binary-package-control-files-debian-control) a `Source:` clause in .deb packages. My hypothesis is: when there is a single binary package with the same name than the source package, the `Source:` field is omitted. This is the case for our ignition-$collection packages.
The PR is changing the previous `grep`:
`grep -1 "Source: ${LIB}"`
By:
`grep -1 -m 1 -e "Source: ${LIB}" -e "Package: ${LIB}"`
Adding `-m 1` should make grep to stop on the first match (side effect, this can speed up the script). If we don't find the `Source:`field we fallback to look for the …

Fix dashboard to include packages without Source field (i.e ignition-fortress)

---

jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ignition_collection.dsl

Ignition launch was ported to Windows some months ago and enabled for `main` and `-pr-`. This PR enables the version 5 just released and add it to the Fortress collection.
Build is fine: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_launch-ign-5-win&build=1)](https://build.osrfoundation.org/job/ign_launch-ign-5-win/1/)
DSL for ignition: [![Build Status](https://build.osrfoundation.org/job/_dsl_ignition/1204/badge/icon)](https://build.osrfoundation.org/job/_dsl_ignition/1204/)
DSL for collection:  [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition_collection&build=403)](https://build.osrfoundation.org/job/_dsl_ignition_collection/403/)
Fixes: https://github.com/ignition-tooling/release-tools/issues/351

Enable ign-launch5 windows jobs. Add it to Fortress

---

jenkins-scripts/dsl/ignition_collection.dsl

The nightly scheduler build is unstable:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition-fortress-nightly-scheduler&build=212)](https://build.osrfoundation.org/job/ignition-fortress-nightly-scheduler/212/) https://build.osrfoundation.org/job/ignition-fortress-nightly-scheduler/212/
~~~
releasing ign-tools1 (from branch main
MARK_AS_UNSTABLE
- done
releasing ign-cmake2 (from branch ign-cmake2
- done
releasing ign-math6 (from branch ign-math6
- done
releasing ign-plugin1 (from branch ign-plugin1
MARK_AS_UNSTABLE
- done
~~~
The correct debbuild names don't include the major version:
* https://build.osrfoundation.org/job/ign-plugin-debbuilder/
* https://build.osrfoundation.org/job/ign-tools-debbuilder/

Fix debbuild names for nightly scheduler

---

jenkins-scripts/dsl/ignition_collection.dsl

The ign-tools nightly build was triggered with the `main` branch instead of `ign-tools1` due to missing logic in the dsl file.
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-tools-debbuilder&build=192)](https://build.osrfoundation.org/job/ign-tools-debbuilder/192/) https://build.osrfoundation.org/job/ign-tools-debbuilder/192/

ignition_collection: fix ign-tools nightly branch

---

jenkins-scripts/dsl/ignition.dsl
release.py

CI failed in https://github.com/ignitionrobotics/ign-physics/pull/294 on a non-`large-memory` machine, and several debbuilds failed as well. Let's require `large-memory` for all ign-physics CI and debbuild jobs.
* ubuntu/bionic amd64: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-physics5-debbuilder&build=375)](https://build.osrfoundation.org/job/ign-physics5-debbuilder/375/) https://build.osrfoundation.org/job/ign-physics5-debbuilder/375/
* ubuntu/focal amd64: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-physics5-debbuilder&build=379)](https://build.osrfoundation.org/job/ign-physics5-debbuilder/379/) https://build.osrfoundation.org/job/ign-physics5-debbuilder/379/

ign-physics CI/debbuilds use large-memory label

---

jenkins-scripts/docker/lib/generic-abi-base.bash

Fixes https://github.com/ignitionrobotics/ign-rendering/issues/488
The abi-checker in ign-rendering is broken with the following error [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_rendering-abichecker-any_to_any-ubuntu_auto-amd64&build=821)](https://build.osrfoundation.org/job/ignition_rendering-abichecker-any_to_any-ubuntu_auto-amd64/821/):
```
The GCC parameters:
gcc -fdump-lang-raw -fkeep-inline-functions -c -x c++ -fpermissive -w  -std=c++17 "/tmp/MZxkwdymxg/dump1.h"  -I/usr/local/destination_branch/include/ignition/rendering6 -I/usr/include/OGRE-2.2 -I/usr/include/OGRE -I/usr/include/ignition/utils1 -I/usr/include/ignition/math6 -I/usr/include/ignition/common4 -I/usr/include/OGRE/Paging
In file included from …
```

Support for OGRE extra includes in abi checker

---

jenkins-scripts/docker/ignition-abichecker.bash
jenkins-scripts/docker/lib/generic-abi-base.bash

Fix for builds not using ogre2.2 after #560.
Set the `EXTRA_INCLUDES` variable in `ignition-abichecker.bash` to add ogre2.2 include paths only if a package using `ignition-rendering6`+ is detected.
Test:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gui-abichecker-any_to_any-ubuntu_auto-amd64&build=655)](https://build.osrfoundation.org/job/ignition_gui-abichecker-any_to_any-ubuntu_auto-amd64/655/) https://build.osrfoundation.org/job/ignition_gui-abichecker-any_to_any-ubuntu_auto-amd64/655/

ABI builds: only set ogre2.2 paths if needed

---

jenkins-scripts/parser_rules/debbuild_missing.parser

This should help to identify when we are missing optional dependencies in the packaging jobs by turning unstable the builds.
Tested here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-physics5-debbuilder&build=523)](https://build.osrfoundation.org/job/ign-physics5-debbuilder/523/) with the results of the parser here https://build.osrfoundation.org/job/ign-physics5-debbuilder/523/parsed_console/.
If we merge it now, there would be a good bunch of unstable builds due to different missing packages. The way to solve it would be to inject in the packaging rules files the corresponding `SKIP_$software=True` in the `override_dh_auto_configure` like we are doing for other configurations (i.e: https://github.com/ignition-release/ign-msgs6-release/blob/main/ubuntu/debian/ …

Make debbuilds unstable when a missing component is triggering a warning

---

jenkins-scripts/docker/ignition-abichecker.bash

Follow up to https://github.com/ignition-tooling/release-tools/pull/562#discussion_r753403375

Fix ABI builds with ogre 2.2 for launch5+

---

jenkins-scripts/lib/windows_env_vars.bat

Update the vcpkg snapshot used by all our CI jobs to `2021-05-12`. 
@Blast545 was testing the different supported versions:
* Citadel / Gazebo3: not supported
* Dome / Gazebo4: not supported
* Edifice / Gazebo5: https://build.osrfoundation.org/job/_vcpkg_testing_snapshot/104/
* Fortress / Gazebo6: https://build.osrfoundation.org/job/_vcpkg_testing_snapshot/102/
* Garden / GazeboMain: https://build.osrfoundation.org/job/_vcpkg_testing_snapshot/103/
The Windows machine should be update using https://build.osrfoundation.org/job/_vcpkg_update_snapshot/ before merging this.

Update vcpkg snapshot to 2021.05.12

---

release-repo-scripts/bump_dependency.bash

There were several issues with the auto-generated homebrew formulae in the `bump_dependency.bash` script.
* The major version number in the ign-collection formula was negative (see https://github.com/osrf/homebrew-simulation/pull/1422/commits/509abd322c131e2e31b92a8dc15d101c8fc4eb3f)
* The url replacing logic would replace every url in the file, including the PyYAML url
* It did not remove `revision` numbers
* It was using source commits in the URLs instead of building from the `main` branch, as decided in https://github.com/osrf/homebrew-simulation/pull/1481
* It didn't handle SDFormat properly in a few places
I've used this to open the homebrew-simulation pull requests for https://github.com/ignition-tooling/release-tools/issues/545

bump_dependency.bash: improve homebrew support

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

gazebo11 needs an older version of cmake on homebrew,
but it is keg-only so prepend its bin folder to the PATH.
Workaround for #573, follow-up to https://github.com/osrf/homebrew-simulation/pull/1696 and https://github.com/osrf/homebrew-simulation/pull/1697

Brew CI: set PATH if cmake@3.21.4 is used

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

If a GitHub pull request branch contains `matching_branch/`, then try to checkout that branch from `gzdev`. To simplify checking out other branches, clone gzdev without `--depth 1`.
Part of #564.
Testing:
* https://github.com/ignitionrobotics/ign-fuel-tools/pull/218
* https://github.com/ignition-tooling/gzdev/compare/scpeters/matching_branch/test_msgs9?expand=1
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_fuel-tools-ci-pr_any-ubuntu_auto-amd64&build=673)](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-ubuntu_auto-amd64/673/) https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-ubuntu_auto-amd64/673/

Try to checkout matching gzdev branch for PR jobs

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Part of #564, similar to #572.
Tested with
* https://github.com/ignitionrobotics/ign-fuel-tools/pull/218
* https://github.com/osrf/homebrew-simulation/compare/scpeters/matching_branch/test_msgs9?expand=1
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_fuel-tools-ci-pr_any-homebrew-amd64&build=656)](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-homebrew-amd64/656/) https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-homebrew-amd64/656/
The `brew pull` command has been deprecated, so that code was replaced with checking for matching branches.

Brew CI: try checking out matching branches

---

release-repo-scripts/bump_dependency.bash

This updates the `bump_dependency.bash` script to prefix branch names with `ci_matching_branch/` so that CI should automatically use the matching branch in infrastructure repositories. I'm using this branch with #554, and branch matching currently works for `homebrew-simulation`, so I would expect the homebrew builds to work properly.
The following changes support the matching branch names:
* https://github.com/ignition-tooling/release-tools/commit/861c0229633177b970837a67e0ebf6c68d64a839: use consistent branch names with `ci_matching_branch/` prefix
* https://github.com/ignition-tooling/release-tools/commit/7a0f7369d79d8a2a8efdd87e3a3c7c103f2cc62b: fix sanity check of branch names, which was hard-coded to expect that the names start with `bump_`
The following fixes a bug in fuel-tools …

Use ci_matching_branch/ in bump_dependency.bash

---

release-repo-scripts/bump_dependency.bash

There were some errors in osrf/homebrew-simulation#1704 with `fuel_tools` not properly recognized by the regex. I re-ran with this branch to generate https://github.com/osrf/homebrew-simulation/pull/1704/commits/f31f88251caf8aeeac1c0ffbd99069a9441f3095.

Fix _ handling in bump_dependency for formula

---

jenkins-scripts/lib/colcon-default-devel-windows.bat
jenkins-scripts/lib/windows_library.bat

Do [not use /b](https://ss64.com/nt/exit.html) on error routines to let Windows kill the whole terminal so the build scripts don't keep running.
Testing without this patch: https://build.osrfoundation.org/job/_test_ign_gui/5/consoleFull#console-section-15 (build is failing on `colcon build` but the script keep going)
Testing with this patch: https://build.osrfoundation.org/job/_test_ign_gui/15/consoleFull#console-section-15 (build is failing as soon as the first problem appear)

Fail hard on Windows when a command fails

---

jenkins-scripts/lib/_homebrew_cleanup.bash

Untested but should fix https://github.com/osrf/buildfarmer/issues/257 .
I don't know if there is a better way to avoid the presence of the lock on the aborted builds but this should not cause too much problem.

Clean up any possible lock on gitconfig from aborted builds

---

release.py

We currently always have an arm node in our buildfarm, and sometimes arm builds fail in qemu ( https://github.com/ignitionrobotics/ign-rendering/issues/212 ), so update the docker node label tag to only use arm agents for arm builds.

release.py: only use arm* nodes for arm* builds

---

.github/ISSUE_TEMPLATE/eol_collection.md

This could be nice as it could actually trigger some people to finish off work they had half-done, instead of letting it time out and having to rebase it for other versions.

EOL template: add a task about notifying the community

---

jenkins-scripts/dsl/sdformat.dsl

We have not yet made the final release of libsdformat10, so re-enable it as a supported branch to allow ABI-checker CI jobs. Needed by https://github.com/ignitionrobotics/sdformat/pull/800. Part of https://github.com/ignition-tooling/release-tools/issues/600

sdformat.dsl: re-enable sdf10 until release

---

jenkins-scripts/tools/detect_ci_matching_branch.py

This has been failing on some of our CI runs, such as [this](https://build.osrfoundation.org/job/ignition_common-ci-pr_any-ubuntu_auto-amd64/1015/console)
```
+++ python3 ./scripts/jenkins-scripts/docker/../tools/detect_ci_matching_branch.py ci_matching_branch/bump_garden_ign-common5
File "./scripts/jenkins-scripts/docker/../tools/detect_ci_matching_branch.py", line 14
print(f"{branchName} matches {pattern}")
^
SyntaxError: invalid syntax
```
This may be fixed when we migrate to Focal (#565), but until then, we can just use a backwards-compatible syntax

detect_ci_matching_branch: support python < 3.6

---

.github/ISSUE_TEMPLATE/bump_libraries.md
.github/ISSUE_TEMPLATE/release_collection.md

* Goes with https://github.com/ignition-tooling/gzdev/pull/50#issue-1090637906, see that issue for the reasoning

Move "enable nightlies" task from bump libraries to post-release

---

.github/ISSUE_TEMPLATE/release_collection.md

Updates after using it on
* https://github.com/ignition-tooling/release-tools/issues/459

Update release template after using it for Fortress

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/gazebo.dsl
jenkins-scripts/dsl/sdformat.dsl
jenkins-scripts/lib/dependencies_archive.sh

Our CI is currently defaulting to Bionic. Garden is going to drop Bionic though (see https://github.com/ignitionrobotics/docs/pull/215), so we should default to Focal instead, which is supported for all the Ignition versions we're currently working on (Citadel, Dome, Edifice, Fortress, Garden).
We should do a lot of testing before merging this; I can do it next week. I think we may need to hardcode `bionic` for Gazebo 9 and dependencies.

Default to Focal for CI

---

jenkins-scripts/lib/windows_library.bat
jenkins-scripts/tools/detect_ci_matching_branch.py

I noticed in the [ign_gazebo-pr-win/3576](https://build.osrfoundation.org/job/ign_gazebo-pr-win/3576/) build that `detect_ci_matching_branch.py` printed `chapulina/7/triggered does not match ci_matching_branch/`, but it still tried to checkout `chapulina/7/triggered` from `gazebodistro`. This is caused by a syntax problem when checking the `ERRORLEVEL` in `windows_library.bat`. This fixes it by explicitly setting error codes in `detect_ci_matching_branch.py`
and fixes the syntax for checking `ERRORLEVEL` in `windows_library.bat` since `ERRORLEVEL` evaluates to true if the error number is `>=` the number specified (see [documentation](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if)).
Testing with https://github.com/ignitionrobotics/ign-utils/pull/34
* …

Fix checking for ci_matching_branch on windows

---

jenkins-scripts/lib/dependencies_archive.sh

The dependencies are already properly defined in the
packages.apt files in the ign-physics repository.
The IGN_PHYSICS_DEPENDENCIES variable in
dependencies_archive.sh is incorrect, and we'd be
better off without it.
Focal builds are broken: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics-ci-ign-physics5-focal-amd64&build=1)](https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics5-focal-amd64/1/) https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics5-focal-amd64/1/
Testing with this branch: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics-ci-ign-physics5-focal-amd64&build=2)](https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics5-focal-amd64/2/) …

Remove IGN_PHYSICS_DEPENDENCIES variable

---

jenkins-scripts/docker/lib/generic-abi-base.bash

Fixes this issue:
```
+ git clone git://github.com/lvc/abi-compliance-checker.git
Cloning into 'abi-compliance-checker'...
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
See build failure here:
https://build.osrfoundation.org/job/ignition_fuel-tools-abichecker-any_to_any-ubuntu_auto-amd64/380/consoleFull#console-section-8

Fix failure to clone abi-compliance-checker

---

terminal-dashboard/_dashboard_lib.sh

Makes it possible to run:
`bash terminal-dashboard/table.bash garden nightly`

Add Garden to terminal dashboard

---

jenkins-scripts/docker/sdformat-compilation.bash

Signed-off-by: ahcorde <ahcorde@gmail.com>
We are getting this warning in the CI, because we don't have `pxr` binaries available yet. This PR should remove this warning
```
CMake Warning at /usr/share/cmake/ignition-cmake2/cmake2/IgnConfigureBuild.cmake:55 (message):
CONFIGURATION WARNINGS:
-- Skipping component [usd]: Missing dependency [pxr].
^~~~~ Set SKIP_usd=true in cmake to suppress this warning.
Call Stack (most recent call first):
CMakeLists.txt:121 (ign_configure_build)
```

Skip pxr for sdformat

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Needed by osrf/homebrew-simulation#1790, https://github.com/ignitionrobotics/ign-common/pull/290
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_common-ci-pr_any-homebrew-amd64&build=1271)](https://build.osrfoundation.org/job/ignition_common-ci-pr_any-homebrew-amd64/1271/) https://build.osrfoundation.org/job/ignition_common-ci-pr_any-homebrew-amd64/1271/
~~~
+ echo '#BEGIN SECTION: brew doctor analysis'
#BEGIN SECTION: brew doctor analysis
+ brew missing
+ brew missing
+ brew list
+ grep '^sdl$'
+ brew doctor
Warning: Some …

Ignore brew doctor warnings for proj@7

---

jenkins-scripts/ign_common-default-devel-windows-amd64.bat
jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat
jenkins-scripts/ign_gui-default-devel-windows-amd64.bat
jenkins-scripts/ign_launch-default-devel-windows-amd64.bat
jenkins-scripts/ign_physics-default-devel-windows-amd64.bat
jenkins-scripts/ign_rendering-default-devel-windows-amd64.bat
jenkins-scripts/ign_sensors-default-devel-windows-amd64.bat
jenkins-scripts/lib/windows_library.bat

Needed by https://github.com/ignitionrobotics/ign-rendering/pull/539

ign_common windows: use gdal

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash
jenkins-scripts/lib/project-install-homebrew.bash

Repeat of #626 for install_bottle jobs.
Needed to fix the following:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_garden-install_bottle-homebrew-amd64&build=72)](https://build.osrfoundation.org/job/ignition_garden-install_bottle-homebrew-amd64/72/) https://build.osrfoundation.org/job/ignition_garden-install_bottle-homebrew-amd64/72/
~~~
#BEGIN SECTION: brew doctor analysis
+ brew missing
+ brew missing
+ brew list
+ grep '^sdl$'
+ brew doctor
Warning: Some installed formulae are deprecated or disabled.
You should find …

brew doctor: unstable instead of fail, ignore proj@7 warnings

---

jenkins-scripts/lib/_homebrew_base_setup.bash

There is an unreleased fix for a brew doctor bug (https://github.com/Homebrew/brew/issues/12788), so stop using `HOMEBREW_UPDATE_TO_TAG` for now.

Don't use HOMEBREW_UPDATE_TO_TAG for now

---

jenkins-scripts/lib/_homebrew_github_setup.bash

Problem happened here https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/1079 with the error:
```
+++ ssh -T git@github.com
+++ grep successfully
++ [[ -z '' ]]
++ echo 'The github connection seems not to be valid:'
The github connection seems not to be valid:
++ ssh -T git@github.com
Host key verification failed.
Build step 'Execute shell' marked build as failure
```
Running the same command manually in the server displays the real error:
```
jenkins@ip-172-30-1-10:~$ ssh -T git@github.com
Warning: the ECDSA host key for 'github.com' differs from the key for the IP address '192.30.255.112'
Offending key for IP in /var/lib/jenkins/.ssh/known_hosts:5
Matching host key in /var/lib/jenkins/.ssh/known_hosts:11
Are you sure you want to continue connecting …
```

Try refreshing github key if auth failed for brew

---

jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkgBase.groovy

There are problems with non cleaning up the whole workspace on -debbuild jobs.
Reported by @scpeters:
* https://build.osrfoundation.org/job/sdformat10-debbuilder/245/ is good
* https://build.osrfoundation.org/job/sdformat10-debbuilder/246/  is failing
The reason for the failure is the lack of liburdfdom-dev installed in the system. Problem is the `SOURCE_DEFINED_DEPS` variable. Bionic seems not to find anything:
```
+++ DEPENDENCIES_PATH_TO_SEARCH=.
++++ tr '\n' ' '
+++++ find . -iname packages-bionic.apt -o -iname packages.apt
+++++ grep -v '/\.git/'
++++ sort -u
+++ SOURCE_DEFINED_DEPS=
```
Focal find a build/ directory with a packages.apt file:
```
+++ DEPENDENCIES_PATH_TO_SEARCH=.
++++ tr '\n' ' '
+++++ find . -iname packages-focal.apt -o -iname packages.apt
+++++ grep -v '/\.git/' …
```

Clean the whole workspace in -debbuild jobs

---

jenkins-scripts/docker/sdformat-compilation.bash

Follow-up to https://github.com/ignition-tooling/release-tools/pull/625.
Without this branch:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat11-focal-amd64&build=5)](https://build.osrfoundation.org/view/ign-edifice/job/sdformat-ci-sdformat11-focal-amd64/5/) https://build.osrfoundation.org/view/ign-edifice/job/sdformat-ci-sdformat11-focal-amd64/5
With this branch:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat11-focal-amd64&build=6)](https://build.osrfoundation.org/view/ign-edifice/job/sdformat-ci-sdformat11-focal-amd64/6/) https://build.osrfoundation.org/view/ign-edifice/job/sdformat-ci-sdformat11-focal-amd64/6

Only set SKIP_usd for libsdformat 12+

---

jenkins-scripts/lib/colcon-default-devel-windows.bat

Somehow one of the colcon windows build for ign-gazebo failed with problems on the build/ directory https://github.com/ignitionrobotics/ign-gazebo/pull/1246#issuecomment-993714643. 
I think that our check for `KEEP_WORKSPACE` flag is wrong and is not cleaning up the workspaces as expected.

Fix build/ cleanup in colcon Windows build

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Requested by https://github.com/osrf/homebrew-simulation/pull/1793#discussion_r792556070

Install brew :build dependencies for CI builds

---

jenkins-scripts/docker/lib/_common_scripts.bash
jenkins-scripts/docker/lib/generic-install-base.bash

Something in our focal -install- jobs has changed and it is pulling `keyboard-configuration` package into the list of packages to be installed. That requires of user interaction unless we configure the system not to do it.
Failing build: https://build.osrfoundation.org/job/ignition_gazebo6-install-pkg-focal-amd64/15/console
We are using `ARG DEBIAN_FRONTEND=noninteractive` in our Docker images but that variable is not present when we invoke a a command with `sudo`. The PR adds a new variable to encapsulate the `noninteractive` configuration.
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo6-install-pkg-focal-amd64&build=14)](https://build.osrfoundation.org/job/ignition_gazebo6-install-pkg-focal-amd64/14/)

Use custom apt command to avoid problems in noninteractive

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Until we can update the ignition-common code to use the new ffmpeg 5 API, let's stick with using the `ffmpeg@4` formula in homebrew (https://github.com/osrf/homebrew-simulation/pull/1804). This is a keg-only formula, so we have to set `PKG_CONFIG_PATH` to point to the `ffmpeg@4` install prefix.
without this branch: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_common-ci-ign-common1-homebrew-amd64&build=32)](https://build.osrfoundation.org/job/ignition_common-ci-ign-common1-homebrew-amd64/32/) https://build.osrfoundation.org/job/ignition_common-ci-ign-common1-homebrew-amd64/32/
with this branch: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_common-ci-ign-common1-homebrew-amd64&build=33)](https://build.osrfoundation.org/job/ig …

brew: set PKG_CONFIG_PATH if using ffmpeg@4

---

jenkins-scripts/docker/lib/debbuild-base.bash

There has been problems with recent nightlies that failed due to problems in the upgrade path of packages. Example: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-gazebo7-debbuilder&build=186)](https://build.osrfoundation.org/job/ign-gazebo7-debbuilder/186/)
The PR force the `INVALIDATE_DOCKER_CACHE` to run all the nightly builds without cache. Tested in the same node failing before, here: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-gazebo7-debbuilder&build=189)](https://build.osrfoundation.org/job/ign-gazebo7-debbuilder/189/)

Use INVALIDATE_DOCKER_CACHE in nightly generation

---

jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Part of the mitigation measure for the impact of https://github.com/ignition-tooling/release-tools/issues/639.
First, try to avoid the problem by all means on new Jammy releases that are being done these days.
Tested here: https://build.osrfoundation.org/job/ign-math6-debbuilder/1359/console

Be sure of not using gcc8 on jammy

---

jenkins-scripts/docker/lib/debbuild-base.bash

The problem with the default compression to zstd on Jammy for .deb packages and our old version of reprepro can be workarounded by keeping compression in xz.
dpkg-deb does not expose the compression option for the internal artifacts inside .deb (the options available seems to affect only to the tarballs not in the .deb). The workaround is a bit tricky since we need to create a wrapper that forces this option, see https://alioth-lists-archive.debian.net/pipermail/devscripts-devel/2014-May/002232.html
Tested here: https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1343/
Upoaded just fine here: https://build.osrfoundation.org/job/repository_uploader_packages/22181/

Use xz to compress .deb packages on jammy

---

jenkins-scripts/docker/lib/_gazebo_utils.sh
jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/debian-git-repo-base.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

The PR generalize the use of [autopkgtest](https://wiki.debian.org/ContinuousIntegration/autopkgtest) to be shared between the debian-git-repo and now with debbuild-base. autopkgtest basically supports CI for packages generated by defining the build and testing scripts in the debian metadata. See https://github.com/ignition-release/ign-cmake2-release/pull/2 for an example of it.
As a side change required, the cleanup of the `sources.list` file to avoid warnings that make autopkgtest to fail, here d31418ea0f300005a06cc5bdc563df43c6f74970.
Tested [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-cmake2-debbuilder&build=1317)](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1317/):
```
+ cd /home/jenkins/workspace/ign-cmake2-debbuilder/pkgs
+ set +e
+ sudo …
```

Use autopkgtest (debian testing mechanism) in debbuild runs

---

jenkins-scripts/docker/lib/debbuild-base.bash

The PR implements the mechanism to repeat the execution of mk-build-deps to help with problems in nightlies. This should cover possible race conditions between different packages being built and uploaded at the same time.
Together with #642, this should help to diagnose the problems on the nightly generation.
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-gazebo7-debbuilder&build=202)](https://build.osrfoundation.org/job/ign-gazebo7-debbuilder/202/)

Retry the packages installation in nightlies if failed

---

jenkins-scripts/lib/gazebo-base-windows.bat

This fixes https://github.com/osrf/gazebo/issues/3170. 
The problem with the linking of boost there was the mix of vcpkg header files with the tarballs we use to build Gazebo. While working in the fix I removed everything I see used by vcpkg including tinyxml2.
Turns out that `msgs5` requires tinyxml2 and that was coming from vcpkg. This is an obvious bug in the buildsystem but I'm going to live with this until we solve #373 or provide a good build environment to Gazebo classic.
Failing before: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-ci-gazebo11-windows7-amd64&build=129)](https://build.osrfoundation.org/job/gazebo-ci-gazebo11-windows7-amd64/129/)
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-ci-gazebo11-windows7-am …

 Remove vcpkg boost,ogre,gdal,protobuf before running Gazebo builds on Windows

---

jenkins-scripts/docker/lib/boilerplate_prepare.sh
jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/docker/multidistribution-ignition-debbuild.bash

This should stop problems with #639. Two main changes in the PR:
* Remove `NEED_C11_COMPILER` since all our linux platforms implements the standard by default.
* Reduce logic duplication for `NEED_C17_COMPILER`
Tested:
* common4 build on Bionic, needs the custom compiler:  [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common4-debbuilder&build=814)](https://build.osrfoundation.org/job/ign-common4-debbuilder/814/)
* common4 build on Focal, don't use the custom compiler: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common4-debbuilder&build=815)](https://build.osrfoundation.org/job/ign-common4-debbuilder/815/)

Remove NEED_C11_COMPILER variable and simplify NEED_C17_COMPILER

---

release.py

Part of https://github.com/ignition-tooling/release-tools/issues/644 as suggested by @scpeters.
We have Bionic, Focal and Jammy, I've setup temporary the tags in docker (need permanent configuration) as follow:
* optimus: focal
* r2d2: bionic
* linux-ip-172-30-1-216: jammy (not large-memory but can probably handle the existing jammys)

Use a special node tag for processing nightlies

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/docker/lib/docker_run.bash

There is no `osrf/jammy_armhf` image so @nuclearsandwich suggested to give it a try to the native platform docker support. That worked just fine: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-math6-debbuilder&build=1365)](https://build.osrfoundation.org/job/ign-math6-debbuilder/1365/)
@nuclearsandwich commented offline:
> One thing I noticed when doing manual testing, the vanilla docker-build command was not platform aware. So using FROM --platform=linux/armhf ubuntu:jammy would work the first time but if I tried to build or run a different platform image for ubuntu:jammy it would keep using the armhf one until I ran docker-rmi ubuntu:jammy It may be worth testing whether that same host will correctly build an arm64 or amd64 package as well. And you may need to …

Native docker platform support for armhf on Jammy

---

release.py

The jammy docker image requires updated docker versions to handle it properly. The xenial nodes in the buildfarm are affected and can not be updated easily. The focal nodes, after being updated to version greater than 20.10.07 to deal with different problems on jammy including the clone3 syscall.
This change should be temporary until we update all the nodes.

Use docker-jammy TAG in jenkins for Jammy jobs

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Don't set tbb@2020_u3 variables if github branch
name matches replace_deprecated_tbb_task, which
allows testing of osrf/gazebo#3174.

brew: test fix for new tbb with gazebo

---

jenkins-scripts/lib/_homebrew_base_setup.bash

This reverts commit 6370d9882faeb8615c9ff5590e33948e170b29dd (#629).
It is no longer needed since brew 3.3.13 has been released.
Testing: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat12-install_bottle-homebrew-amd64&build=124)](https://build.osrfoundation.org/job/sdformat12-install_bottle-homebrew-amd64/124/) https://build.osrfoundation.org/job/sdformat12-install_bottle-homebrew-amd64/124/

Revert "Don't use HOMEBREW_UPDATE_TO_TAG for now (#629)"

---

jenkins-scripts/lib/_homebrew_base_setup.bash

Several bottles are failing linkage checks since Homebrew/brew#12584 was merged, so disable these checks for now.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gui-ci-ign-gui3-homebrew-amd64&build=74)](https://build.osrfoundation.org/view/ign-citadel/job/ignition_gui-ci-ign-gui3-homebrew-amd64/74/) https://build.osrfoundation.org/view/ign-citadel/job/ignition_gui-ci-ign-gui3-homebrew-amd64/74/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gui-ci-ign-gui3-homebrew-amd64&build=75)](https://build.osrfoundation.org/view/ign-citadel/job/ignition_gui-ci-ign-gui3-homebrew-amd64/75/) https://build.osrfoundation.org/view/ign-citadel/job/ignition_gui-ci-ign-gui3-homebrew-amd64/75/

Set HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK for now

---

jenkins-scripts/dsl/_configs_/OSRFLinuxBase.groovy

Previously a simple generated job failed with [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_job_from_dsl&build=9)](https://build.osrfoundation.org/job/_test_job_from_dsl/9/)  
```
ERROR: Step ?Archive the artifacts? failed: No artifacts found that match the file pattern "Dockerfile,build.sh". Configuration error?
```
Fixed if run with this branch: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_job_from_dsl&build=10)](https://build.osrfoundation.org/job/_test_job_from_dsl/10/)

DSL: do not fail if Linux jobs don't have Dockefile

---

jenkins-scripts/docker/lib/_gazebo_utils.sh

When the debbuilds run the `autopkgtest` (mechanism to smoke testing the freshly generated packages) the tool automatically generates tests for python packages by trying to guess the python module in the case that no other autopkgtest were defined in (`debian/tests/*` directory). This is probably going to fail in most of the occasions for us since our python bindings use a different filesystem schema.
This PR disabled that auto-generation for python packages.

Do not run autogenerated tests in autopkgtest

---

jenkins-scripts/lib/windows_env_vars.bat
jenkins-scripts/lib/windows_library.bat
jenkins-scripts/vcpkg-bootstrap.bat

Follow up and superseed https://github.com/ignition-tooling/release-tools/pull/657. Originally coming from https://github.com/ignitionrobotics/ign-common/pull/292#issuecomment-1039738233 , problems with gdal in some of the Windows nodes.
We can not install gdal again from previous versions of vcpkg because some of the files have been removed from the mirrors since new versions are out. This PR updates vcpkg to the latest snapshot available. This is going to bump many versions at once, including ogre to 1.12.9, ffmpeg to 4.4.1, etc.
The testing job for compiling all ignition family up to main on[ ign-gazebo seems fine](https://build.osrfoundation.org/job/_vcpkg_testing_snapshot/113/). Probably all the update work done in Brew and all the patched for Windows sent by conda-forge contributors …

Update vcpkg-snapshot to 2022.02.23

---

terminal-dashboard/unreleased.bash

`bash terminal-dashboard/unreleased.bash edifice`
Before:
```
...
https://github.com/ignitionrobotics/sdformat/compare/sdformat11_11.3.0...sdformat11
...
```
After:
```
...
https://github.com/ignitionrobotics/sdformat/compare/sdformat11_11.3.0...sdf11
...
```

Fix SDF links in unreleased table

---

release.py

All jenkins nodes were updated to Focal and docker versions should be modern enough to handle jammy. Removing the workaround of `docker-jammy` from release.py.

Remove docker-jammy jenkins label, not needed anymore

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Closes #666. Relocate gzdev 2nd run after the full cache invalidation.
Being tested [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-pr_any-ubuntu_auto-amd64&build=8247)](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/8247/)

Relocate gzdev 2nd run after cache invalidation

---

jenkins-scripts/lib/_homebrew_base_setup.bash

This reverts commit e316d8497c67d5342c6f595f8a3c48363fdccb5e from #656.
This is no longer needed since Homebrew/brew#12979 was merged.
There is still an issue with the rpath in some formulae (see https://github.com/osrf/homebrew-simulation/issues/1827), but CI works without setting this environment variable, so we can revert it.
Testing with this branch:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gui-ci-ign-gui3-homebrew-amd64&build=76)](https://build.osrfoundation.org/view/ign-citadel/job/ignition_gui-ci-ign-gui3-homebrew-amd64/76/) https://build.osrfoundation.org/view/ign-citadel/job/ignition_gui-ci-ign-gui3-homebrew-amd64/76/

Revert "Set HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK for now (#656)"

---

jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/dsl/ignition.dsl

The PR restricts to 1 the building threads in arm native nodes for both CI and packaging:
* The CI was using GLOBAL_SHELL_CMD to add the configuration but that variable is global and it is going to affect all jobs generated after setting it. I changed it to a local variable. Also fix bashism to sh.
* Add the same configuration to packaging jobs
Tested in ign-physics arm64 build: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-physics5-debbuilder&build=625)](https://build.osrfoundation.org/job/ign-physics5-debbuilder/625/)

Limit ign-physics building threads to 1 in arm native nodes

---

jenkins-scripts/docker/lib/debbuild-base.bash

Continue of #674 and fixed problems on Focal after merging that PR
dh-make version in Focal and lower is buggy when using the `--defaultless` flag since it requires to have a debian/rules file mandatory. Reported and fixed https://salsa.debian.org/debian/dh-make/-/merge_requests/8
Workaround is to run the tool without the parameter and remove the created debian/ directory afterwards.
Tested in: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering7-debbuilder&build=264)](https://build.osrfoundation.org/job/ign-rendering7-debbuilder/264/)

dh-make lower than 2.202003 is buggy using --defaultess

---

jenkins-scripts/dsl/_configs_/GenericCompilation.groovy
jenkins-scripts/dsl/_configs_/OSRFCIWorkFlowMultiAnyGitHub.groovy

At the moment there is a backlog of ign_gazebo-pr-win jobs due in part to the fact that only one may run at a time.
I am not sure if there are some job types which should not be allowed to run conditionally but decided to start by just opening the floodgates in case it was just that easy.

Allow CI Workflow jobs to run concurrently.

---

jenkins-scripts/lib/_homebrew_cleanup.bash

Sometimes `brew list` fails if the brew installation on a build machine has been corrupted. This will check for failures and invoke restore_brew if needed.
The [mac-ultron.bigsur](https://build.osrfoundation.org/computer/mac-ultron.bigsur/) Jenkins node recently started failing jobs with the following error message:
* https://build.osrfoundation.org/job/sdformat12-install_bottle-homebrew-amd64/180/console
~~~
+++ /usr/local/bin/brew list --formula
/usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `require': cannot load such file -- sorbet-runtime-stub (LoadError)
from /usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `<top (required)>'
from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `require'
from …

brew: try to rescue if `brew list` fails

---

jenkins-scripts/docker/ign_utils-compilation.bash
release-repo-scripts/bump_major_version.bash

Needed by 
* https://github.com/ignition-tooling/release-tools/issues/685
* https://github.com/ignitionrobotics/ign-utils/pull/49
Oops, that was probably bad copy-paste. See how other libs are correct:
https://github.com/ignition-tooling/release-tools/blob/54d09aeadb420e6f9bbb7836fa929cda5dfd1788/jenkins-scripts/docker/ign_math-compilation.bash#L36
https://github.com/ignition-tooling/release-tools/blob/54d09aeadb420e6f9bbb7836fa929cda5dfd1788/jenkins-scripts/docker/ign_msgs-compilation.bash#L35
Without this, `gzdev` is not enabling nightlies for `ign-utils2` ubuntu builds

Fix GZDEV_PROJECT_NAME for ign-utils2

---

release.py

Signed-off-by: Jose Luis Rivero <jrivero@osrfoundation.org>

Restrict i386 on release.py to Bionic on Ubuntu

---

release-repo-scripts/bump_dependency.bash

Handles some of the edge cases tracked here:
https://github.com/ignition-tooling/release-tools/issues/689
Specifically:
- Cases like `ign-tools2 2.0.0` -> `ign-tools3 2.0.0` don't bump properly. (2.0.0 is expected to be bumped to 3.0.0)
- Handle cases where those versions come as an argument to another parameter (e.g. `ign-tools2 VERSION 2.0.0`)
- Case: `IGN_<LIB>_VER N-1` -> `IGN_<LIB>_VER N` is not addressed

Fix some bump_dependency edgecases

---

release-repo-scripts/bump_dependency.bash

Followups from: https://github.com/ignition-tooling/release-tools/pull/699 , which introduced a bug where later replacements wouldn't get caught due to prior replacements.
Also introduces a rule to remove the IGN_<LIB>_VER N pattern:
```
^^^ <-- Bumped!
```

Fix ordering and remove IGN_<LIB>_VER pattern

---

.github/ISSUE_TEMPLATE/release_collection.md

We often forget to execute them. This item should help

Perform deprecation tocks when a main branch is created

---

jenkins-scripts/ign_tools-default-devel-windows-amd64.bat

* Needed by https://github.com/ignitionrobotics/ign-tools/pull/82
* Part of https://github.com/ignition-tooling/release-tools/issues/685
I checked that `jenkins-scripts/tools/detect_cmake_major_version.py` correctly returns `1` for the `ign-tools1` branch and `2` for the branch on the PR above.
Build with this branch: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_tools-pr-win&build=44)](https://build.osrfoundation.org/job/ign_tools-pr-win/44/)

Use colcon auto major version for ign-tools

---

jenkins-scripts/lib/dependencies_archive.sh

This fixes the issue where ignition-tools gets installed alongside ignition-tools2 for versions that use it.
Also, this is a partial deprecation of the dependencies_archive in general.

Deprecate Dependencies Archive for ign-tools installs

---

jenkins-scripts/lib/dependencies_archive.sh

Building on top of @methylDragon 's work in:
* https://github.com/ignition-tooling/release-tools/pull/704
* https://github.com/ignition-tooling/release-tools/pull/705
* https://github.com/ignition-tooling/release-tools/pull/707
* https://github.com/ignition-tooling/release-tools/pull/708
This PR completely skips all dependency resolution for Garden versions. We should probably be able to change this all the way back to Citadel, but for now sticking to Garden to be quicker.
Builds have been installing more than they needed for a while, but it hasn't been a problem until now because all libraries could be installed side-by-side. But while we work on #698, `ign-tools2` will be conflicting with `ign-tools1` for a while. So it's especially important that we only install what we need, as …

Completely rely on packages.apt from Garden

---

docs/BUILDFARM_NODES.md

To setup the `linux-nightly-jammy` label is hard to do it using AWS spawing machines (like current ip-* nodes). The are ocasionally destroyed by AWS and new nodes are using new images for AMI. This makes the fact of keeping the `linux-nightly-jammy` label in a single node 
Let's move the label to one of our permanent nodes, drogon.

Change linux-nightly-jammy from ip-* node to to drogon

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/dsl/gazebo.dsl
jenkins-scripts/parser_rules/gazebo_err.parser

The library libglvnd is being used in our docker build although I'm not sure that we really need it. The description of the library says: "libglvnd is a vendor-neutral dispatch layer for arbitrating OpenGL API calls between multiple vendors" . Our Jenkins nodes should not needed AFAIK.
The compilation is broken on Jammy.  The PR skip it for Jammy although it is maintained for Bionic/Focal to avoid possible regressions on current builds. I've tested the changes with Gazebo classic. To make it work some other fixes are in this PR:
* Gazebo packages from Ubuntu are unversioned f74de1571f6004f3af0c6066073593dba3068f88
* Do not make the build to be unstable if Gazebo error about OpenAL (sounds) is found 2e405856b401cb3399b9955034433e47674e8508
Currently broken: [![Build …

Remove libglvnd in docker for jammy (broken) and fix gazebo CI

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/lib/dependencies_archive.sh

- Move ROS 2 Rolling CI to Jammy
- Use unversioned gazebo packages in Jammy
DSL testing
https://build.osrfoundation.org/job/_dsl_gazebo_ros_pkgs/880/console
```
Unreferenced items:
GeneratedJob{name='ros2_gazebo_pkgs-ci-default_rolling-focal-amd64'}
GeneratedJob{name='ros2_gazebo_pkgs-ci-pr_any_rolling-focal-amd64'}
Disabled items:
GeneratedJob{name='ros2_gazebo_pkgs-ci-default_rolling-focal-amd64'}
GeneratedJob{name='ros2_gazebo_pkgs-ci-pr_any_rolling-focal-amd64'}
Finished: SUCCESS
```
Build ci:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros2_gazebo_pkgs-ci-default_rolling-jammy-amd64&build=1)](https://build.osrfoundation.org/job/ros2_gazebo_pkgs-ci-default_rolling-jammy-amd64/1/)

Support for Rolling on Jammy for gazebo_ros_pkgs

---

jenkins-scripts/dsl/extra.dsl

After moving the org to the new name, change the github name to the new gazebo-forks.

Use gazebo-forks instead of ignition-forks

---

jenkins-scripts/docker/lib/debbuild-base.bash

The PR implements the detection of new gz- names in source packages and modify the `PACKAGE_ALIAS` accordingly.
This should help with the transition of ign- packages to the new gz- names and make possible to work debbuilder without modifying the input parameters from release.py (nightly generation included).
The scape of `PACKAGE_ALIAS` variable needs to happen to get the new value generated in the script instead of hardcoding the value from input parameters.

Auto detect PACKAGE_ALIAS to help with gz transition

---

one-line-installations/gazebo.sh

Unversioned packages for Ubuntu Jammy in the one-liner installation

Add support to Jammy for one-liner installation of Gazebo Classic

---

jenkins-scripts/docker/lib/boilerplate_prepare.sh
jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/multidistribution-ignition-debbuild.bash

Tested with new gz- packages [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-tools2-debbuilder&build=92)](https://build.osrfoundation.org/view/all/job/ign-tools2-debbuilder/92/)

Remove obsolete GITHUB_ORG and use new github orgs in debbuild

---

source-repo-scripts/source_changelog.bash

These are needed if you clone from the new `gz` URLs. 
~~I tried to keep compatibility with old `ign` clones, but I haven't fully tested this yet.~~
Works with old `ign-` clones too, used it in
* https://github.com/gazebosim/gz-rendering/pull/651
Also used with
* https://github.com/gazebosim/gz-sensors/pull/238

Support gz- repos on source_changelog script

---

jenkins-scripts/docker/ign_tools-compilation.bash

Similar to
* https://github.com/gazebo-tooling/release-tools/pull/688
* https://github.com/gazebo-tooling/release-tools/pull/692
Needed by the following, so nightlies are enabled
* https://github.com/gazebosim/gz-tools/pull/96
Test builds
* Using https://github.com/gazebosim/gz-tools/pull/96 (gz-tools2 requiring nightlies): [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_tools-ci-pr_any-ubuntu_auto-amd64&build=284)](https://build.osrfoundation.org/job/ignition_tools-ci-pr_any-ubuntu_auto-amd64/284/)
* Using `ign-tools1` (make sure that the logic doesn't break it): [![Build Status](http://build.osrfoundation.org/job/ignition_tools-ci-pr_any-ubuntu_auto-amd64/285/badge/icon)](http://build.osrfoundation.org/job/ignition_tools-ci-pr_any-ubuntu_auto-amd64/285/)

Add GZDEV_PROJECT_NAME to gz-tools

---

source-repo-scripts/merge_forward_pull_request.bash

I don't know exactly what conditions make this necessary, but I often run into a situation where the `gh` CLI complains like this:
`pull request create failed: GraphQL error: Head sha can't be blank...`
I noticed that passing an explicit head fixes the issue

Explicit head branch when opening forward-port PR

---

jenkins-scripts/lib/windows_library.bat

* Part of https://github.com/gazebo-tooling/release-tools/issues/718
We need to support Citadel and Fortress `ignition-` packages, as well as Garden `gz-` packages.
The logic here checks if colcon can detect the `ignition-` package in the workspace, and if it can't, it renames the package to `gz-` and tries that.
Test runs:
* With `gz-`, using https://github.com/gazebosim/gz-utils/pull/57: https://build.osrfoundation.org/job/ign_utils-pr-win/225/console#console-section-6
```
Packages in workspace:
gz-cmake3
gz-utils2
gz-utils2
Using package name gz-utils2
```
* With `ignition-`, using `ign-utils1` branch: https://build.osrfoundation.org/job/ign_utils-pr-win/227/console
```
Packages in workspace:
ignition-cmake2
ignition-utils1
ignition-utils1
ignition-utils1
Using package name …
```

Windows colcon: Rename ignition package to gz if not in ws

---

jenkins-scripts/lib/colcon-default-devel-windows.bat

Part of https://github.com/gazebo-tooling/release-tools/issues/718

Windows colcon: Rename ignition package to gz if not in ws (2)

---

jenkins-scripts/ign_common-default-devel-windows-amd64.bat
jenkins-scripts/ign_fuel-tools-default-devel-windows-amd64.bat
jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat
jenkins-scripts/ign_gui-default-devel-windows-amd64.bat
jenkins-scripts/ign_launch-default-devel-windows-amd64.bat
jenkins-scripts/ign_math-default-devel-windows-amd64.bat
jenkins-scripts/ign_msgs-default-devel-windows-amd64.bat
jenkins-scripts/ign_physics-default-devel-windows-amd64.bat
jenkins-scripts/ign_plugin-default-devel-windows-amd64.bat
jenkins-scripts/ign_rendering-default-devel-windows-amd64.bat
jenkins-scripts/ign_sensors-default-devel-windows-amd64.bat
jenkins-scripts/ign_tools-default-devel-windows-amd64.bat
jenkins-scripts/ign_transport-default-devel-windows-amd64.bat
jenkins-scripts/ign_utils-default-devel-windows-amd64.bat

Reverting the part of #752 which changes the `COLCON_PACKAGE` variables because that breaks Fortress and earlier

Restore ignition COLCON_PACKAGE var

---

jenkins-scripts/lib/colcon-default-devel-windows.bat
jenkins-scripts/lib/windows_library.bat

* Part of https://github.com/gazebo-tooling/release-tools/issues/718
Follow up to
* https://github.com/gazebo-tooling/release-tools/pull/754
* https://github.com/gazebo-tooling/release-tools/pull/755
`gz-sim` has been failing with 
```
C:\Jenkins\workspace\ign_gazebo-pr-win>echo Packages in workspace: 
Packages in workspace:
C:\Jenkins\workspace\ign_gazebo-pr-win>colcon list --names-only 
gz-cmake3
gz-common5
gz-fuel_tools8
gz-gui7
gz-math7
gz-msgs9
gz-physics6
gz-plugin2
gz-rendering7
gz-sensors7
gz-sim7
gz-sim7
gz-tools2
gz-transport12
gz-utils2
sdformat13
C:\Jenkins\workspace\ign_gazebo-pr-win>colcon list --names-only   | find "ignition-gazebo7" 
C:\Jenkins\workspace\ign_gazebo-pr-win>if errorlevel 1 (set COLCON_PACKAGE=gz-gazebo7 ) 
C:\Jenkins\workspace\ign_gazebo-pr-win>colcon list …
```

Windows colcon: handle ignition-gazebo -> gz-sim case

---

jenkins-scripts/ign_tools-default-devel-windows-amd64.bat
jenkins-scripts/lib/colcon-default-devel-windows.bat
jenkins-scripts/lib/windows_library.bat

The wrong variable substitution directive is used for `COLCON_PACKAGE` for some of the windows jenkins scripts (`% %` does substitution at parse-time, while `! !` does substitution at runtime), causing variables to not get updated and for builds to fail.
This PR fixes that.

Use appropriate substitution invocation for COLCON_PACKAGE

---

release.py

* Part of https://github.com/gazebo-tooling/release-tools/issues/736
The `release.py` script has a sanity check that verifies the package name on the `-release` repo's changelog and control files.
I did the easy change for now for the sanity check to accept either an `ignition` or a `gz` name. A cleaner solution may be to set the package alias to be `gz` for Garden and remain `ignition` for Citadel and Fortress, but I didn't find a simple way of doing that.

Support releasing gz packages

---

jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat
jenkins-scripts/ign_launch-default-devel-windows-amd64.bat

Hoping to fix the Garden CI builds of gz-sim on windows:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_gazebo-ci-win&build=209)](https://build.osrfoundation.org/job/ign_gazebo-ci-win/209/) https://build.osrfoundation.org/job/ign_gazebo-ci-win/209/
~~~
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindBoost.cmake:1793 (file):
file STRINGS file
"C:/vcpkg/installed/x64-windows/include/boost/version.hpp" cannot be read.
Call Stack (most recent call first):
C:/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package)
CMakeLists.txt:98 (find_package)
CMake Warning at C:/Jenkins/workspace/ign_gazebo-ci-win/ws/install/gz-cmake3/share/cmake/gz-cmake3/cmake3/IgnConfigureBuild.cmake:69 (message):
CONFIGURATION WARNINGS:
-- Ogre 1.x versions greater …

windows: add boost-core vcpkg dep to ign-gazebo, launch

---

jenkins-scripts/lib/windows_library.bat

This simple command will allow us to check differences between the versions of the packages used when building a buildfarm job for Windows. 
Any suggestions to implement something similar for Linux? we've realized the packages are not being imported there via `vcs`.
FYI: @Crola1702
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

Print vcs export information on Windows

---

README.md

This will encourage those who perform a release to monitor the debbuild jobs for unstable builds and report them where appropriate.

Release checklist: check for unstable debbuilds

---

jenkins-scripts/dsl/extra.dsl

Match the priority used in OSRFLinuxBuildPkg for the ogre debbuild jobs
* https://build.osrfoundation.org/job/ogre-2.3-debbuilder
* https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkg.groovy#L35

extra.dsl: debbuild priority 100

---

source-repo-scripts/merge_forward_pull_request.bash

Support URLs like
`git@github.com:ignitionrobotics/ign-utils.git`
Used this to open
* https://github.com/gazebosim/gz-utils/pull/71

Forward-port PR: handle .git URLs

---

.github/ISSUE_TEMPLATE/release_collection.md

* https://github.com/gazebo-tooling/release-tools/issues/578
The Garden release timeline will be considerably longer than Fortress and earlier. This proposal is to create the stable branches earlier, so that feature PRs can continue landing on `main` during feature freeze and code freeze. If we kept our original process, those PRs would be hanging for 2 months and couldn't be merged anywhere.

Branch off earlier from Garden release

---

jenkins-scripts/ign_common-default-devel-windows-amd64.bat

* https://github.com/gazebosim/gz-common/pull/393
We already install it for `gz-sim` and `gz-launch`, i.e.
https://github.com/gazebo-tooling/release-tools/blob/f7959b4fdf58188129112d67e956f57dc52f0ef3/jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat#L8

Install assimp for gz-common on Windows

---

source-repo-scripts/merge_forward_pull_request.bash

I noticed a pull request created with the same branch name used for the source and destination. We can easily check for that case and return an error.

merge forward script: ensure different args

---

jenkins-scripts/ign_cmake-default-devel-windows-amd64.bat
jenkins-scripts/ign_common-default-devel-windows-amd64.bat
jenkins-scripts/ign_fuel-tools-default-devel-windows-amd64.bat
jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat
jenkins-scripts/ign_gui-default-devel-windows-amd64.bat
jenkins-scripts/ign_launch-default-devel-windows-amd64.bat
jenkins-scripts/ign_math-default-devel-windows-amd64.bat
jenkins-scripts/ign_msgs-default-devel-windows-amd64.bat
jenkins-scripts/ign_physics-default-devel-windows-amd64.bat
jenkins-scripts/ign_plugin-default-devel-windows-amd64.bat
jenkins-scripts/ign_rendering-default-devel-windows-amd64.bat
jenkins-scripts/ign_sensors-default-devel-windows-amd64.bat
jenkins-scripts/ign_tools-default-devel-windows-amd64.bat
jenkins-scripts/ign_transport-default-devel-windows-amd64.bat
jenkins-scripts/ign_utils-default-devel-windows-amd64.bat

* Part of https://github.com/gazebo-tooling/release-tools/issues/698
* Goes with https://github.com/gazebo-tooling/gazebodistro/pull/112

[ign ➡️  gz] Update VCS directory for Windows CI

---

jenkins-scripts/docker/lib/debian-git-repo-base.bash

This mirrors what we do in our nightly debbuilder (https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/docker/lib/debbuild-base.bash#L236-L245) but for other packages such as ogre-2.3 debs.
This should make the ogre-2.3 packages built be able to be successfully uploaded to the package servers.
Once this job passes, it should trigger the copy to the prerelease repo:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ogre-2.3-debbuilder&build=28)](https://build.osrfoundation.org/job/ogre-2.3-debbuilder/28/)

Disable zstd compression for now

---

jenkins-scripts/docker/lib/_gazebo_utils.sh
jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/debian-git-repo-base.bash

The debian-git-repo-base.bash script was declaring the default for `RUN_AUTOPKGTEST` variable after the `_gazebo_utils.sh` script was sourced so the default value was not in use and the build was broken https://build.osrfoundation.org/job/ogre-2.3-debbuilder/3/.
Test with this branch: https://build.osrfoundation.org/job/ogre-2.3-debbuilder/5/badge/

Use default for RUN_AUTOPKGTEST in _gazebo_utils.sh

---

jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ignition_collection.dsl
jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

* Requires https://github.com/osrf/homebrew-simulation/pull/1984
* The intention is to fix CI for https://github.com/gazebosim/gz-cmake/pull/296
Test build using this PR together with the 2 above: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_cmake-ci-pr_any-homebrew-amd64&build=911)](https://build.osrfoundation.org/job/ignition_cmake-ci-pr_any-homebrew-amd64/911/)
---
Ah had to rebuild the DSL with this branch: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_ignition&build=1340)](https://build.osrfoundation.org/job/_dsl_ignition/1340/)
Build after rebuilding the DSL: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_cmake-ci-pr_any-homebrew-amd64&build=912)](https://build.osrfoundation.org/job/ignitio …

Use gz- projects on Homebrew CI

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

* Follow up to https://github.com/gazebo-tooling/release-tools/pull/778/files
`gz-sim` is a special snowflake, we were ending up with `brew install gz-gazebo3 --only-dependencies`
Just fixing it within the bash file for now, ideally we'll pass `sim` as the project name eventually
Merging to fix CI

Fix gz-sim for Homebrew

---

jenkins-scripts/dsl/_configs_/GenericAnyJobGitHub.groovy
jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/_configs_/OSRFGitHub.groovy
jenkins-scripts/dsl/_configs_/OSRFWinCompilationAnyGitHub.groovy
jenkins-scripts/dsl/ignition.dsl

Different fixes to deal with right naming for directory Git checkouts on Windows and Brew:
* Relocate `Globals.ign2gz` method at the beginning to deal with problems coming ign-gazebo -> gz-sim
* Add an extra replace to deal with errors in gn-gazebo -> gz-sim transformation in other DSL files
* For Windows: remove the optional argument in `OSRFGitHub.create` to leave the default which is just correct. Use new repository name in `OSRFWinCompilationAnyGitHub.create` to make the directory checkout to be correct.
* For Brew: deal with ign-gazebo -> gz-sim conversion when invoking scripts
Should fix: https://github.com/gazebo-tooling/gazebodistro/pull/117#issuecomment-1204425171
Retry test run: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_gazebo-pr-win&build=4855)](h …

ign2gz: fixes for checkout directory names in Win/Brew

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Follow up to:
* #778 
* https://github.com/gazebo-tooling/release-tools/pull/780
* #779 
The `detect_cmake_major_version` script is failing: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-pr_any-homebrew-amd64&build=8992)](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/8992/)
```
+ PROJECT=gz-sim
+ PROJECT_ARGS=
+ PROJECT_PATH=gz-sim
+ [[ -sim != gz-sim ]]
+ PROJECT_PATH=ign-sim
+ PROJECT_PATH=ign-sim
+ PROJECT=gz-sim
++ python ./scripts/jenkins-scripts/tools/detect_cmake_major_version.py /Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/ign-sim/CMakeLists.txt
Traceback (most recent call last):
File "./scripts/jenkins-scripts/tools/detect_cmake_major_version.py", line 11, in <module>
f = open(fileName, …
```

Homebrew: more gz-sim band-aids 🩹 

---

.github/workflows/ci.yaml
jenkins-scripts/dsl/_configs_/GenericRemoteToken.groovy

The PR adds a short CI for checking that PR changes are not breaking DSL files. This is a simple action that opens the door to do something more useful like showing the real diffs in Jenkins configurations when a PR is being created and DSL files are touched.
Nothing very special in the Github action a part of checking in DSL files are being modified and only run the action in that case. The CI discovered an error in one of the DSL files, fixed in 5421b2eda145719de92ec28aa0876dae2197978e.
Next steps could be:
* Run the generation only in modified files or in all files if the file is a shared code (inside _configs_).
* Run the generation in master and compare the XML files being generated exporting a file with real diffs on changes to land in Jenkins.

Add a github action CI to check correctness of DSL files 

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

When generating the `Dockerfile` we inject a command to invalidate the docker cache monthly. If that happens, it is possible that new gzdev configuration is needed to update to possible recent changes in configuration and/or code before we install packages in the next command.
Example of errors: https://build.osrfoundation.org/job/ignition_gui-ci-pr_any-ubuntu_auto-amd64/1729/console
Testing first run with invalidated cache: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gui-ci-pr_any-ubuntu_auto-amd64&build=1743)](https://build.osrfoundation.org/job/ignition_gui-ci-pr_any-ubuntu_auto-amd64/1743/)

Be sure of update gzdev if docker cache is invalidated

---

jenkins-scripts/dsl/sdformat.dsl

There are several `*_branches` variables that are actually sdformat package names (`sdformat6`, `sdformat9`, etc.) or `main`. This renames the variables to `*_versions` to try to clarify matters.

sdformat.dsl: rename internal variables

---

jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/sdformat.dsl

This renames the `supported_branches` method in `ignition.dsl` to `supported_ign_branches` (https://github.com/gazebo-tooling/release-tools/commit/eab7c8eed4e35d49980e0599e728794c296478f8) and adds a parallel `supported_gz_branches` method that draws from a `gz_branches` data structure (https://github.com/gazebo-tooling/release-tools/commit/9ab203a95aa0b29e843393fbadf4acef4a9f3dcf). It also adds the `sdf13` branch in `sdformat.dsl` (https://github.com/gazebo-tooling/release-tools/commit/558d0e69ad9b40e3cf3cb0d5b06bfa81bafe9dc8).
The code duplication could potentially be reduced with some refactoring, but I think this is the easiest way to get CI working for our garden branches.

Add CI jobs for garden branches

---

jenkins-scripts/ign_tools-default-devel-windows-amd64.bat
jenkins-scripts/lib/colcon-default-devel-windows.bat
jenkins-scripts/lib/windows_library.bat

@methylDragon while working on #753 I found that Windows builds [seems to fail ](https://build.osrfoundation.org/job/_test_ign_physics-ign-2-win/1/console)with problems in COLCON_PACKAGE var. We are chaging in #753 all COLCON_PACKAGE names to `gz-*`, something that is going to break old supported branches that expect `ignition-*`. I made 75877eec8c54725074b4cf996790ed14025477d8 to revert the logic.
The other patch here is removing the code in windows_library since the `build_workspace` is only called from the `jenkins-scripts/lib/colcon-default-devel-windows.bat` that already implements the logic as far as I can tell.
I've tested this branch in: https://build.osrfoundation.org/job/_test_ign_physics-ign-2-win/8/

Windows fixes for 753 (ign -> gz)

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash
jenkins-scripts/sdformat-default-devel-homebrew-amd64.bash

As mentioned in https://github.com/gazebosim/sdformat/pull/1063, `pytest` is needed to generate junit xml files for python tests.

Add pytest to list of pip installed dependencies for sdformat

---

.github/workflows/ci.yaml

Idea is easy: for the current DSL files modified we generate the real XML configuration in Jenkins in our CI currently to check syntax. With this PR we store the set of XML files generated, we use the master branch to get the current XML configurations in Jenkins and we run diff to export the changes between `master` and the PR so real differences appear clearly. The PR export two files: one with just the name of the config files changed and other with content changed.
Tested: https://github.com/j-rivero/release-tools/pull/1/files reporting https://github.com/j-rivero/release-tools/actions/runs/2886111942

Export Jenkins XML configuration diffs for DSL changed files in the CI

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Something changed recently in the way python works on homebrew, and some of our tests are currently unable to find our installed python bindings:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat13-homebrew-amd64&build=8)](https://build.osrfoundation.org/job/sdformat-ci-sdformat13-homebrew-amd64/8/) https://build.osrfoundation.org/job/sdformat-ci-sdformat13-homebrew-amd64/8/
~~~
282:     from gz.math import Pose3d, Color
282: E   ModuleNotFoundError: No module named 'gz'
~~~
Setting `PYTHONPATH` to `/usr/local/lib/python` allows finding the `gz` python bindings.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat13-homebrew-amd64&build=9)](https://build.osrfoundation.org/job/sdformat-ci-sdformat13-homebrew- …

brew CI: set PYTHONPATH

---

terminal-dashboard/_dashboard_lib.sh
terminal-dashboard/table.bash

* Use `gz` names
* Leave only AMD
Current status:

Dashboard for Garden pre-release

---

jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ignition_collection.dsl
jenkins-scripts/ign_cmake-default-devel-windows-amd64.bat
jenkins-scripts/lib/colcon-default-devel-windows.bat
jenkins-scripts/lib/windows_library.bat

This is the last gz- of #412. ign-cmake was a bit special since it adds a CMake parameters to the compilation thus I needed to implement that parameter passing in the form of `_COLCON_EXTRA_CMAKE_ARGS`.
If we want to keep the history of the CI jobs, we can rename them before we merge this PR. //cc @Blast545. This also affects t https://github.com/osrf/buildfarmer/pull/338.
Test:
* New ign_cmake-ci-win [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_cmake-ci-win&build=9)](https://build.osrfoundation.org/job/ign_cmake-ci-win/9/)
* No use of cmake argument ign-plugin [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_plugin-ci-win&build=31)](https://build.osrfoundation.org/job/ign_plugin-ci-win/31/)

Port gz-cmake to use colcon on Windows

---

release.py

Completing #799.
release.py should handle the gz-physics in the same way it did with ignition-physics to setup the right label for powerful nodes in the buildfarm.

Fix bug for node labels in gz-physics when using release.py

---

jenkins-scripts/dsl/ignition_collection.dsl
jenkins-scripts/dsl/sdformat.dsl

To get consistency in the naming scheme I would like to change sdformat Windows names to use the same format the the ones using colcon in ignition.dsl. The format is: 
* Branch CI: `$software_name-$branch_unversioned-$version-win`
* Any PR testing: `$software_name-pr-win`
* Main branch CI: `$software_name-ci-win`
This will follow up #812 to get the whole family of Windows jobs with a consistent name scheme, if I'm not wrong.
This also affects https://github.com/osrf/buildfarmer/pull/338. To keep history, we should rename the jobs before merging //cc @Blast545

Use short names for Windows sdformat DSL jobs

---

jenkins-scripts/dsl/ignition_collection.dsl

Reverts #810 and use `gz-` prefixes for debbuilders in the collection metapackage.

Use gz- debbuilders in collections

---

jenkins-scripts/dsl/ignition.dsl

- Stop using gazebo7 extra builder. 
- Add 'sim' to the support list of packages for GPU
- Fix all_branches to take into account 'sim' and not 'gazebo'

Fixes for DSL related to gz transition: sim7 support, gpu for sim jobs

---

.github/ISSUE_TEMPLATE/release_collection.md

We haven't yet updated the Garden changelogs, since the prereleases did not require a version bump pull request. I think prereleases are a good time to update the changelog, so I've updated the `release_collection` issue template to remind us to do so at that time. Please share thoughts if you think a different time in the release process would be better.

release_collection: prerelease Changelog updates

---

source-repo-scripts/source_changelog.bash

Currently the source_changelog.bash script only works for ignition-* tags, while garden will use gz-* tags. This updates the script to grep for a tag that ends with the specified version number. It also uses the current branch for the comparison to avoid assumptions about ign-* or gz-* branch names.
I needed to make these changes in order to generate gz-garden changelogs:
~~~
cd gz-cmake
git checkout gz-cmake3
../release-tools/source-repo-scripts/source_changelog.bash 2.15.0
~~~

changelog script: improve tag/branch detection

---

jenkins-scripts/dsl/_configs_/OSRFLinuxCompilation.groovy

Should fix #814 
Tested [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros2_gazebo_pkgs-ci-default_rolling-jammy-amd64&build=22)](https://build.osrfoundation.org/job/ros2_gazebo_pkgs-ci-default_rolling-jammy-amd64/22/)

Ignore ALSA lib false positive in warnings inside Jenkins

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/sdformat.dsl

The _ign_TEST CLI tests are skipped for asan due to an LD_PRELOAD error, but the _gz_TESTs on garden
should be skipped as well.
Currently passes in fortress:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci_asan-sdformat12-focal-amd64&build=21)](https://build.osrfoundation.org/view/asan/job/sdformat-ci_asan-sdformat12-focal-amd64/21/) https://build.osrfoundation.org/view/asan/job/sdformat-ci_asan-sdformat12-focal-amd64/21/
Unstable in garden:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci_asan-sdformat13-focal-amd64&build=8)](https://build.osrfoundation.org/view/asan/job/sdformat-ci_asan-sdformat13-focal-amd64/8/) https://build.osrfoundation.org/view/asan/job/sdformat-ci_asan-sdformat13-focal-amd64/8/
~~~
119: [ RUN …

asan dsl: skip _gz_TEST tests also

---

jenkins-scripts/dsl/ignition_collection.dsl

There is no stable release of an ignition-garden debian package, so don't create a CI job for it.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_garden-install-pkg-focal-amd64&build=101)](https://build.osrfoundation.org/job/ignition_garden-install-pkg-focal-amd64/101/) https://build.osrfoundation.org/job/ignition_garden-install-pkg-focal-amd64/101/

dsl: disable ignition_garden-install-* jobs

---

jenkins-scripts/docker/ign_launch-install-test-job.bash
jenkins-scripts/docker/lib/_gazebo_utils.sh
jenkins-scripts/dsl/ignition_collection.dsl

Extend the CI done in `gz-collection` metapackages to check that `gz-tools` submodules are all installed by default.
* Current problems in Garden detected: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_garden-install-pkg-focal-amd64&build=11)](https://build.osrfoundation.org/job/gz_garden-install-pkg-focal-amd64/11/)
* Citadel run: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_citadel-install-pkg-bionic-amd64&build=13)](https://build.osrfoundation.org/job/gz_citadel-install-pkg-bionic-amd64/13/)
This should help to detect problems related to #830 and https://github.com/gazebosim/gz-tools/issues/111

Test gz-tools subcommands expected when installing gz- metapackages

---

jenkins-scripts/gazebo-default-devel-homebrew-amd64.bash
jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

When testing a new Mac mini in build.osrfoundation.org, we found that python 2.X is no longer available in macOS Monterey in `/usr/bin/python`. This is fine, we should be using `python3` explicitly anyway.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_ignition_cmake-ci-gz-cmake3-homebrew-amd64&build=1)](https://build.osrfoundation.org/job/_test_ignition_cmake-ci-gz-cmake3-homebrew-amd64/1/) https://build.osrfoundation.org/job/_test_ignition_cmake-ci-gz-cmake3-homebrew-amd64/1/
~~~
++ python ./scripts/jenkins-scripts/tools/detect_cmake_major_version.py /Users/jenkins/workspace/_test_ignition_cmake-ci-gz-cmake3-homebrew-amd64/ign-cmake/CMakeLists.txt
./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash: line 31: python: command not found
++ …

brew CI: use python3 explicitly

---

jenkins-scripts/dsl/brew_release.dsl

We now have a Mac mini running macOS Monterey, so let's build some bottles.
Testing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_brew_release&build=741)](https://build.osrfoundation.org/job/_dsl_brew_release/741/) https://build.osrfoundation.org/job/_dsl_brew_release/741/
* https://github.com/osrf/homebrew-simulation/pull/2081#issuecomment-1275584239
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder&build=995)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/995/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/995/

brew_release.dsl: build monterey bottles

---

source-repo-scripts/merge_forward_pull_request.bash
source-repo-scripts/release_pull_request.bash

This is similar to the `merge_forward_pull_request.bash` script added in #720 but assists with opening version bump pull requests based on the template in the [pull request template](https://github.com/gazebosim/.github/blame/main/PULL_REQUEST_TEMPLATE.md#L69-L89). It takes the currently released version, target branch, and previous version as arguments for filling in the template. After running the scipt, you can click the boxes that you have completed.
To test it, I opened https://github.com/gazebosim/sdformat/pull/1178 with the following command from a terminal with current directory in an sdformat repository with the `scpeters/bump_990` branch checked out:
~~~
bash ../release-tools/source-repo-scripts/release_pull_request.bash 9.9.0 sdf9 9.8.0
~~~

Add script for opening release PR

---

release-repo-scripts/README.md
release-repo-scripts/convert_gazebodistro_to_release.py

The PR adds a little script that generates vcs compatible files using a gazebodistro file as input and all the -release repositories associated with the input file. More info in the content added to the README.

Add script to convert a gazebodistro file to vcs file with -release repos

---

terminal-dashboard/table.bash

The PR changes the approach used in the terminal dashboard since it is broken after the inclusion of the `ignition-*` transitional packages that arch-independent. When they are built for one arch, they appear in all the arches so the terminal dashboard wrongly assumes that there were packages built for the rest of arches.
New approach assumes that all the gz- libraries have a package named libgz-${LIB} except for the collection packages. This is now valid but somehow fragile. Real solution would imply a real parsing and add logic which is quite an effort much bigger.
PR also takes i386 out from new collections starting with Debian.

Fix terminal-dashboard to avoid confusions with arch=all packages

---

jenkins-scripts/dsl/ignition.dsl

Since windows_nuc is not working fine for rendering jobs, the PR restrict the Windows gz-rendering jobs to nodes with the label `win_rendering`.
I've setup beefy to use this label: https://build.osrfoundation.org/computer/win-beefy.win10/

Workaround to enable rendering on Win only in selected nodes

---

jenkins-scripts/docker/gazebo-abichecker.bash
jenkins-scripts/docker/lib/_gazebo_version_hook.bash
jenkins-scripts/docker/lib/gazebo-base-default.bash
jenkins-scripts/gazebo-default-devel-homebrew-amd64.bash
jenkins-scripts/gazebo-default-devel-windows7-amd64.bat
jenkins-scripts/lib/dependencies_archive.sh

This has a follow-up to #843 that is needed to fix some CI failures, built on top of some clean up of the gazebo-classic scripts. It's easiest to review by commit:
* https://github.com/gazebo-tooling/release-tools/commit/eb5a0d1010adf4263f603016a9076cd0790ea48d?w=1 (without whitespace): remove `GAZEBO_EXPERIMENTAL_BUILD` variable related to outdated https://github.com/osrf/gazebo_experimental repository.
* https://github.com/gazebo-tooling/release-tools/commit/29774df20d9ca5f6be2e9e6cfa61125813386e38?w=1 (without whitespace): remove logic that checks for EOL versions of gazebo-classic
* https://github.com/gazebo-tooling/release-tools/commit/ea81afcd005d90499f81e720cd7388f6ce682d6d: update source folder names to `gazebo-classic`
Needed to fix [![Build …

Fix gazebo-classic folder name and clean up

---

jenkins-scripts/docker/ignition-abichecker.bash
jenkins-scripts/docker/lib/generic-abi-base.bash

In combination with https://github.com/gazebosim/gz-sim/pull/1778 should fix the abichecker for gz-sim7.
Testing: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-abichecker-any_to_any-ubuntu_auto-amd64&build=5845)](https://build.osrfoundation.org/job/ignition_gazebo-abichecker-any_to_any-ubuntu_auto-amd64/5845/)

Add -fPIC to abichecker for qt dependent builds

---

README.md

The script to generate source changelog lives in the ``source-repo-scripts`` directory, updating that in the PR.

Update changelog generation instructions

---

jenkins-scripts/docker/gazebo-abichecker.bash
jenkins-scripts/lib/gazebo-base-windows.bat
jenkins-scripts/lib/gazebo9_10-base-windows.bat

Follow-up to #846. Some gazebo abichecker jobs are failing on certain machines:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-abichecker-any_to_any-ubuntu_auto-amd64&build=1243)](https://build.osrfoundation.org/job/gazebo-abichecker-any_to_any-ubuntu_auto-amd64/1243/) https://build.osrfoundation.org/job/gazebo-abichecker-any_to_any-ubuntu_auto-amd64/1243/
~~~
> git rev-parse --resolve-git-dir /home/jenkins/workspace/gazebo-abichecker-any_to_any-ubuntu_auto-amd64/gazebo-classic/.git # timeout=10
Fetching changes from the remote Git repository
> git config remote.origin.url https://github.com/gazebosim/gazebo-classic.git # timeout=10
Fetching upstream changes from https://github.com/gazebosim/gazebo-classic.git
...
+ cp -a …

Use gazebo-classic in more scripts

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

This triggered a failure on debbuilder for gz-transport8 on autopkgtest [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-transport8-debbuilder&build=134)](https://build.osrfoundation.org/job/ign-transport8-debbuilder/134/)
```
W: Target Packages (restricted/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Packages (restricted/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Packages (universe/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Packages (universe/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4 …
```

Do not add ubuntu repository twice on i386

---

jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkg.groovy
jenkins-scripts/lib/repository_uploader.bash

For testing proposes when we test the -release repo changes or other packaging stuff, this PR improves the "unofficial" support for `none` value in the `UPLOAD_TO_REPO` parameter:
* DSL code change: ddede4bcc609a4c28b5c2eba9be8337dd6bdfe30 Avoid the call to `repository_uploader` if none is passed in `UPLOAD_TO_REPO`.
* Changes in repsitory_uploader script: in the case that the 'none' value is found in the `UPLOAD_TO_REPO` parameter do not execute any upload code and finish successfully. bad3c51f177f2e7a81efbc00c3cda2b587b3877d
Note: the tabs were very broken in the code, better see this PR [with ?w=1](https://github.com/gazebo-tooling/release-tools/pull/858/files?w=1)

Better support for "none" in UPLOAD_TO_REPO param in Jenkins debbuilders

---

jenkins-scripts/dsl/brew_release.dsl

homebrew-core has stopped building catalina bottles, so we will do the same.
Noticed in https://github.com/osrf/homebrew-simulation/pull/2146
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder%2Flabel%3Dosx_catalina&build=1062)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_catalina/1062/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_catalina/1062/
* https://github.com/Homebrew/homebrew-core/commit/791fce5b059caf7b1a3444cba69798809965ecc6

brew_release.dsl: stop catalina bottle builds

---

jenkins-scripts/dsl/ignition.dsl

The extra debbuilders, mostly used for nightlies are using the `ign-` prefix, what is breaking nightlies. I think that makes more sense to move all them to `gz` and make the exception of `utils1` which is the only one not belonging to the Harmonic release.

Use gz insetead of ign for extra_debbuilders

---

jenkins-scripts/dsl/ignition.dsl

Signed-off-by: Ian Chen <ichen@osrfoundation.org>
spotted this while learning about recent changes in release-tools
launch7 is the latest version in harmonic not launch8

gz_extra_debbuild: launch8 -> launch7

---

jenkins-scripts/dsl/gazebo.dsl

We can switch to 20.04 for gazebo-classic CI when the fix for gazebo9 is merged in https://github.com/gazebosim/gazebo-classic/pull/3278, which will resolve the issue https://github.com/gazebosim/gazebo-classic/issues/3151.

gazebo.dsl: use 20.04 for pull request CI builds

---

jenkins-scripts/lib/repository_uploader.bash

Using old s3cmd is looking for python instead of python3. Remove and use the system provided one with new provision.

Use system s3cmd instead of using 1.5.0

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash
jenkins-scripts/lib/project-install-homebrew.bash

Homebrew 4.0 now installs from an API by default instead of requiring a large git clone, but it doesn't work for all operations. Set an environment variable for our CI jobs to avoid API installs for now.
This should fix the following failures:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat13-install_bottle-homebrew-amd64&build=192)](https://build.osrfoundation.org/job/sdformat13-install_bottle-homebrew-amd64/192/) https://build.osrfoundation.org/job/sdformat13-install_bottle-homebrew-amd64/192/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_math7-install_bottle-homebrew-amd64&build=113)](https://build.osrfoundation.org/job/ignition_math7-install_bottle-homebrew-amd64/113/) …

Set HOMEBREW_NO_INSTALL_FROM_API for CI jobs

---

jenkins-scripts/lib/homebrew_bottle_creation.bash

Follow up to #879. Should fix the Monterey build of https://github.com/osrf/homebrew-simulation/pull/2222.

Set HOMEBREW_NO_INSTALL_FROM_API for bottle builds

---

jenkins-scripts/lib/windows_library.bat

List of toolchain versions in the nodes:
- cuda 10.2.89
- python 3.11.2
- ruby 3.1.3
- cmake 3.25
- git 2.38.1
- VS 2022 Comunitty
- java 8
Testing builds (note that other things that are not the compiler may fail):
* gz-sim6 full build [![Build Status](https://build.osrfoundation.org/job/_test_ign_gazebo-ign-6-win/1/badge/icon)](https://build.osrfoundation.org/job/_test_ign_gazebo-ign-6-win/1/)
* gz-sim7 build [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_ign_gazebo-gz-sim7-win&build=3)](https://build.osrfoundation.org/job/_test_ign_gazebo-gz-sim7-win/3/)

Support MSVC 2022 on Windows AWS nodes

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Remove build folder without sudo. I think this should work without `sudo`. Running some tests to confirm.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_utils-ci-gz-utils2-homebrew-amd64&build=21)](https://build.osrfoundation.org/view/ign-garden/job/ignition_utils-ci-gz-utils2-homebrew-amd64/21/) https://build.osrfoundation.org/view/ign-garden/job/ignition_utils-ci-gz-utils2-homebrew-amd64/21/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gui-ci-gz-gui7-homebrew-amd64&build=33)](https://build.osrfoundation.org/view/ign-garden/job/ignition_gui-ci-gz-gui7-homebrew-amd64/33/) https://build.osrfoundation.org/view/ign-garden/job/ignition_gui-ci-gz-gui7-homebrew-amd64/33/
* [![Build …

brew without sudo: part 1

---

jenkins-scripts/dsl/ignition.dsl

Quick and ugly fix for https://github.com/gazebo-tooling/release-tools/pull/885#issuecomment-1460951173 . The whole file is quite messy and would needs a big cleanup. That or wait until Citadel and Fortress are EOL and we can remove all references to ignition-gazebo.

Use right short name for Mac CI jobs using gz-sim branches

---

jenkins-scripts/dsl/ros_gz_bridge.dsl

Part of https://github.com/gazebo-tooling/release-tools/issues/895
Complements #896 by adding a locking system to avoid race conditions when releasing ros_gz bloom packages.

Implement a locking system to orchestrate releasing of ros_gz

---

jenkins-scripts/dsl/gazebo.dsl

We don't need a separate label for gazebo-classic CI jobs anymore.

Replace osx_gazebo label with osx

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/brew_release.dsl
jenkins-scripts/dsl/core.dsl
jenkins-scripts/dsl/debian.dsl
jenkins-scripts/dsl/extra.dsl
jenkins-scripts/dsl/gazebo.dsl
jenkins-scripts/dsl/gazebo_ros_pkgs.dsl
jenkins-scripts/dsl/gzdev.dsl
jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ignition_collection.dsl
jenkins-scripts/dsl/ros_gz_bridge.dsl

Support to define a node label called `test-instance` that will be ignored by all the works.
The implementation adds a new helper function to Globals to supply the logic to ignore the test label.

DSL: ignore nodes labeled as test-instance

---

jenkins-scripts/docker/gazebo-abichecker.bash
jenkins-scripts/docker/ignition-abichecker.bash
jenkins-scripts/docker/lib/generic-abi-base.bash
jenkins-scripts/docker/sdformat-abichecker.bash

Fixes #890.
The ABI script currently assumes that the headers are installed in a subfolder that
starts with the `ABI_JOB_HEADER_PREFIX` variable and a `-`, which only works for `sdformat-9` but requires adjustment for most other packages. This adds an `ABI_JOB_HEADER_PREFIX` variable to help locate the header folder.

ABI script: get correct header paths

---

jenkins-scripts/dsl/ignition.dsl

**DESCRIPTION**
We remove win_rendering label since it's no longer needed given that all windows agents in the buildfarm can manage jobs that need gui/sensors/sim.
This reverts partially changes introduced in #847 .
**CHANGES**
:heavy_minus_sign: win_rendering tag introduction when gui/sensors/sim is matched.

Remove win_rendering tag from windows_ci  job

---

jenkins-scripts/dsl/core.dsl

Fixes a couple of problems with #917:
* The `built-in` label is not ready in our combination of Jenkins version and node plugin version. Use `master` until we execute the full migration.
* The build is not marked as unstable since it lacks the configuration to run the console-log parser that transform the `MARK_AS_UNSTABLE` text into real unstable build status.

Add the unstable parser and master label to the nightly_labeler

---

.gitignore
jenkins-scripts/dsl/_configs_/OSRFUNIXBase.groovy

**DESCRIPTION**
Since  moving to cloud instances for the `nvidia agents` we have encountered issues with versioning resulting in `nvml version mismatch errors` (See [issue](https://github.com/gazebo-tooling/release-tools/issues/912)). This is an unrecoverable error for the builds, and requires manual steps to bring back the agent to a funtional state. 
This PR automates those steps as postbuild actions. If the build failed due to the Nvidia error, we do the following steps: 
1. Remove all labels from current agent and add a `recovery-process` label to indicate that that agent is performing recovery actions, preventing it from taking on any other build.
2. Requeue the job with same parameters with a delay of 70s to give time for the next step. 
3. Schedule a system restart on 1 minute (the …

nvidia mismatch recovery

---

jenkins-scripts/docker/lib/boilerplate_prepare.sh
jenkins-scripts/docker/lib/docker_cleanup.sh

This [issue](https://github.com/gazebo-tooling/release-tools/issues/929) appeared today due to legacy code expecting extreme option for the docker_cleanup process.

remove legacy reference to 'extreme' option in docker cleanup process

---

docs/BUILDFARM_NODES.md
jenkins-scripts/dsl/ignition.dsl

This PR changes node labels, so we're using the same convention for the agents that have a lot of memory to run heavy jobs.

Change huge-memory to large-memory

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash
jenkins-scripts/lib/project-install-homebrew.bash

This fixes a `brew doctor` complaint for some of the bottle install testing jobs.
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_common3-install_bottle-homebrew-amd64&build=1074)](https://build.osrfoundation.org/view/ign-citadel/job/ignition_common3-install_bottle-homebrew-amd64/1074/) https://build.osrfoundation.org/view/ign-citadel/job/ignition_common3-install_bottle-homebrew-amd64/1074/
~~~
+ brew doctor
Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in …

Add brew sbin to PATH to fix doctor complaint

---

jenkins-scripts/dsl/gazebo.dsl

EOL a while ago, there were some jobs being generated for gazebo9. This PR should cleanup the code a bit.

Remove gazebo-classic 9 support in gazebo.dsl

---

.github/workflows/ci.yaml
.gitignore
jenkins-scripts/README.md
jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/ignition_collection.dsl
jenkins-scripts/dsl/tools/setup_local_generation.bash

This PR is the initial work for trying to move the current gz-collections (or releases) metadata out from the Groovy code and write a yaml file that can provide all the necessary metadata to generate the Jenkins jobs and reuse the same file potentially for other users. By now the file is hosted in the same `dsl` directory.
The structure of the yaml file is yet to be properly proposed and defined, I've included a comment in the yaml with some ideas and will evolve it in the next PR as I need info to replace other parts of Groovy.
In this first PR the goal is to replace the generation of `-install-` and `-ci-` jobs for the Gazebo collections moving the initial data from Groovy to the yaml file. Mainly this comment: 08daf596df5e0696aed3cd4a64e33d65d1e5fd7b. The goal is not modify the …

Initial work to move gz-collections metadata to a yaml file

---

jenkins-scripts/docker/ignition-abichecker.bash

Fixes #939 
I'm guessing we could just check for the distro version instead of the version of each package, but for now, I just changed it to include version 6.

Enable -fPIC for ign-gazebo6

---

.github/workflows/ci.yaml
jenkins-scripts/dsl/test.dsl

Remove deprecated code in github actions https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix deprecation on github actions: use GITHUB_OUTPUT instead of set-output

---

jenkins-scripts/dsl/_configs_/OSRFWinBase.groovy
jenkins-scripts/parser_rules/opengl_problem.parser

Include a parser on Windows to detect problems with OpenGL installations. Ideally this should only run on GPU jobs but for now it should be fine to spend a bit of time detecting the problem on all the jobs since the changes required to make it happen only in GPU jobs are not trivial and I would prefer to wait until the `gz-collections.yaml` changes are deployed before doing so.
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_job_from_dsl_win&build=8)](https://build.osrfoundation.org/job/_test_job_from_dsl_win/8/)
//cc @iche033

Add a parser for OpenGL problems on Windows

---

bloom/ros_gz/Dockerfile
bloom/ros_gz/README.md
bloom/ros_gz/_rosdep_wrapper.bash
bloom/ros_gz/bloom_from_special_env.bash
bloom/ros_gz/ros_gz-release.py.bash

Part of https://github.com/gazebo-tooling/release-tools/issues/895.
Reading the `README.md` file can give you an overview of the process implemented.
TODO: the `-release` repository should be changed from my personal account to a different location.

Unofficial ros_gz: script to release a new version of the ros_gz wrappers

---

jenkins-scripts/dsl/_configs_/Globals.groovy

The current cron expression is not supported in Jenkins, which seems to be compatible with the `gnu_mcron` implementation that supports `x-y/z` and `*/z` but does not `x/z` syntax.
The PR changes the starting time of the nightlies to `9:10` so the nightly node cron job runs from `9:00` each 20 minutes until `11:00`.

Fix cron syntax in Jenkins: use gnu_mcron compatible expression

---

bloom/release-bloom.py
bloom/ros_gz/Dockerfile
bloom/ros_gz/_check_metadata.bash
bloom/ros_gz/bloom_from_special_env.bash
bloom/ros_gz/ros_gz-release.py.bash

The PR mainly change the humble use to support different ROS_DISTROs and particularly Iron. The change is simple and made in 511c60535b2d2bd75cf48cf3799673b599b49f20.
To avoid problems when blooming without the right bloom template changes, I've added a check for the modified metadata. It will run after blooming to check the results d7bd5e8e0bea21925064e63e4edfe7be7e595d62 and when someone is trying to trigger the builds in 2d18b37d5b7afc9d3a5253d4f64eda3d759ecd6e

Parametrize ros_gz bloom tooling to accept different ROS_DISTRO values

---

jenkins-scripts/dsl/ignition.dsl

After https://github.com/gazebo-tooling/release-tools/pull/953 the compilation scripts were renamed. Fix the errors of gz_gazebo by using gz_sim in CI jobs.

Fix the calls to gz-gazebo compilation script

---

jenkins-scripts/dsl/_configs_/OSRFUNIXBase.groovy

`nvml error: driver/library version mismatch` was missing a `:` character in the `regexpForRerun` attribute. This PR adds that character
I also moved the "# BEGIN SECTION: NVIDIA MISMATCH RECOVERY" to the real section where the recovery is made, replacing the original message with "Checking if nvidia mismatch error is present in log" for debug processes

Fix nvml error discovery in log

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Part of https://github.com/gazebo-tooling/release-tools/issues/923 efforts. Should have no change in behavior.
Tested:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz-utils2-debbuilder&build=994)](https://build.osrfoundation.org/job/gz-utils2-debbuilder/994/)
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_cmake-ci-pr_any-jammy-amd64&build=12)](https://build.osrfoundation.org/job/gz_cmake-ci-pr_any-jammy-amd64/12/)

Scape $USER in Dockerfile to avoid bash expansion 

---

jenkins-scripts/dsl/_configs_/Globals.groovy

Currently, [_outdated_job_runner](https://build.osrfoundation.org/job/_outdated_job_runner/) it's running every minute instead of every hour as expected.

Fix outdated job cron trigger

---

jenkins-scripts/dsl/_configs_/Globals.groovy

CRON_HOURLY was unintentionally defined to run every minute in #962 
After #965 it was, again, unintentionally defined to run every day instead of every hour.
This PR corrects this problem by making sure it runs every hour using the correct syntax.

Fix `CRON_HOURLY` string

---

jenkins-scripts/lib/check_graphic_card.bash

Attempting to improve the display detection for the Linux GPU agents to resolve #906.

Make display detection more robust.

---

jenkins-scripts/lib/check_graphic_card.bash

Running lsof without sudo rights ends up in a silent error. `strace` displays multiple "Permission denied" on `/proc/` accessed. Error introduced in #916 . Problem not detected since the problem is not appearing in nodes with a valid DISPLAY setup and  Xorg running. 
Quick fix is to use sudo although this does not help towards the rootless CI builds. We can merge it to solve the current problem, which is severe, and think in an alternative to the `lsof`call.
Tested with DISPLAY disabled in [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_sensors-ci-main-jammy-amd64&build=6)](https://build.osrfoundation.org/job/gz_sensors-ci-main-jammy-amd64/6/).

Need to run lsof with sudo from Jenkins CI

---

jenkins-scripts/tools/outdated-job-runner.groovy

The 8 days threshold from an outdated job was defined when we ran the gazebo jobs manually using daily report. Now that this work is automated, it would make sense to decrease the threshold, so the gazebo jobs are run more frequently by [_outdated_job_runner](https://build.osrfoundation.org/job/_outdated_job_runner/).
CC: @Blast545 @claraberendsen

Update outdated job condition from 8 to 4 days

---

docs/BUILDFARM_NODES.md
jenkins-scripts/tools/label-assignment-backstop.groovy

Closes: #967 
Modified the code (and comments) to use the label `large-memory` instead of `docker`. I also found not true that current code is able to support label expression, looking at the code `node.getLabelString().contains()` is probably unable to parser that expressions. Anyway, the filter of test instances is being done inside `findAll`.
I also removed outdate info in 7767c4f8e7715a999b1697beeecf4ef1ce0c0ae5

Use large-memory nodes for nightlies

---

jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkg.groovy

Nightly mode in debbuild base is enabled when "nightly" value is detected in `UPLOAD_TO_REPO`. This is preventing the `UPLOAD_TO_REPO` to set the value `none` for testing and test a nightly with it. Seems more logical to use the `VERSION` field since there is no case where you want to use the `nightly` value in that field for a different reason that to build a nightly.
The [nightly scheduler](https://github.com/gazebo-tooling/release-tools/blob/86049e20b4273a337bc999f68142c13d679c75c4/jenkins-scripts/dsl/ignition_collection.dsl#L662) pass the `nightly` value in the second arg ( `VERSION`) so the nightly builds should not be affected. 
Tested [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz-math7-debbuilder&build=1566)](https://build.osrfoundation.org/job/gz-math7-de …

Enable nighty mode when using nightly on VERSION instead of UPLOAD_TO_REPO

---

jenkins-scripts/lib/check_graphic_card.bash

Should fix #979 
I noticed that the DISPLAY variable contains a weird `:unix::0` with two `::` instead of just one. Removed in 3b48a3ce06cbb7e29314e53ac4934fa6aa51fcae.
Tested for gz-sim7 in:  [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-pr_any-ubuntu_auto-amd64&build=10665)](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/10665/)

Resurrect "Robust display detection" with a variable fix

---

jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/sdformat.dsl

#982 added `sdformat14` in `ignition.dsl`, which I think should be `sdformat.dsl` instead.

Fix sdformat14 dsl

---

jenkins-scripts/dsl/gazebo_libs.dsl
jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/ignition.dsl

Two different implementations:
* Legacy code `ignition.dsl` 3336df73c134384f094bab20c77413e6e18d4f2c ; harcoding the check and the instructions in all the places.
* New code based on yaml in `gazebo_libs` e564c79a03ed9f1bacc68551bd520a866905c502: implement `pre_setup_script_hook:` as part of the spec to support the injecting of random setup scripts for the different libraries. Define the MAKE_JOBS=1 for physics.

Limit physics to jobs to use MAKE_JOBS=1

---

docs/BUILDFARM_NODES.md

@Blast545 noticed that this document had duplicated the `large-memory` label. I think the one that remains is the most clear and concise between the two definitions.

Remove duplicate `large-memory` label

---

jenkins-scripts/docker/gz-source-generation.bash
jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy
jenkins-scripts/dsl/test.dsl

The PR implements the creation of Jenkins jobs that generates and export a tarball for software that uses `gz-cmake`. 
Three main actions:
-  Script to generate tarballs from Gazebo libs source code 
- DSL class for the tarball generation 
- Add a test job for the source generation
Testing [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_gz_source&build=44)](https://build.osrfoundation.org/job/_test_gz_source/44/)

Source code generation Jenkins DSL support

---

jenkins-scripts/dsl/_configs_/OSRFReleasepy.groovy
jenkins-scripts/dsl/test.dsl

Wrapper to call release.py using Jenkins parameters as release.py arguments. Note that the script is not fully functional for standard releases since it currently requires a local software checkout to be run.
This can work with nightly builds or future calls to release.py that don't need to generate the tarballs.
The test inject DRY_RUN to avoid any real run.
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_releasepy&build=7)](https://build.osrfoundation.org/job/_test_releasepy/7/)

Add OSRFReleasepy DSL class

---

jenkins-scripts/lib/windows_library.bat

This PR modifies the location of the cache files in the agent to mirror the default configuration where vcpkg builds it. The goal of this is to use the baked AMI cache instead of rebuilding it every time a new agent comes to life. 
[![Build Status](https://build.osrfoundation.org/job/test_ignition_common-pr-win/7/badge/icon)](https://build.osrfoundation.org/job/test_ignition_common-pr-win/7/)

Change caching dir to default one 

---

jenkins-scripts/dsl/brew_release.dsl

We now have a macOS Ventura machine (intel): https://build.osrfoundation.org/computer/mac-four.ventura/
So let's build bottles with it.

brew_release.dsl: build ventura bottles

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ignition_collection.dsl

Part of https://github.com/gazebo-tooling/release-tools/issues/974

Use stable branch for gz-fuel-tools in harmonic

---

jenkins-scripts/docker/lib/_gazebo_utils.sh

Tested [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros-gz-image-bloom-debbuilder&build=18)](https://build.osrfoundation.org/job/ros-gz-image-bloom-debbuilder/18/)

Default timeout value in _gazebo_utils

---

jenkins-scripts/lib/repository_uploader.bash

Change in repository_uploader to be able to pass files directly to the S3 uploaders by naming them exactly. This should help with the right upload of new tarballs generated in Jenkins.
The `repository_uploader_packages` job does not have a DSL definition yet but [I have tested](https://build.osrfoundation.org/job/repository_uploader_packages/43063/) the execution of the code in an expected failed build to be sure that the uploader does not fail when there is no package specified and just the normal use of uploading .deb packages and source packages.
```
...
+ case ${UPLOAD_TO_REPO} in
+ ENABLE_S3_UPLOAD=false
++ find /home/jenkins/workspace/repository_uploader_packages/pkgs -type f -name '*.zip' -printf '%f\n'
+ S3_FILES_TO_UPLOAD=' '
++ find …
```

Make repository_uploader to support S3_FILES_TO_UPLOAD 

---

.github/workflows/ci.yaml
jenkins-scripts/dsl/gazebo_libs.dsl

An attempt to store generated job names into a variable and a save that variable to a file. This tries to help different tools that consume the names of the jobs generated by the DSL, mainly the buildfarmer dashboard and the different Jenkins views.
The code uses the enviroment variable `WRITE_JOB_LOG` to active the mechanism of storing the job names into a file called `jobs.txt`. It can be invoked by `WRITE_JOB_LOG=1 java -jar tools/jobdsl.jar *.dsl`. The format of the file generated is (space separated):
```bah
job_type collection job_name
```
The PR uses the approach is GitHub action for also testing the generation and control the contents of the file generated.

Make DSL generation to store jobs generated in a log file

---

jenkins-scripts/dsl/sdformat.dsl

This should help with missing jobs. It will bring some undesired focal builds that should be removed under the scope of #1010.

Move sdformat14 as stable in sdformat.dsl

---

jenkins-scripts/dsl/ignition_collection.dsl

Minor fix for ROS bootstrap repository testing:
Before: [![Build Status](https://build.osrfoundation.org/job/ignition_fortress-install-pkg_ros_bootstrap-any-manual/22/badge/icon)](https://build.osrfoundation.org/job/ignition_fortress-install-pkg_ros_bootstrap-any-manual/22/)
After: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_fortress-install-pkg_ros_bootstrap-any-manual&build=24)](https://build.osrfoundation.org/job/ignition_fortress-install-pkg_ros_bootstrap-any-manual/24/)

Do use ign instead of gz for testing ROS imports on Fortress

---

jenkins-scripts/lib/homebrew_formula_pullrequest.bash

Sanitize ~ characters from the brew version string.
Follow up to https://github.com/osrf/homebrew-simulation/issues/2390.

homebrew_formula_pullrequest.bash: sanitize ~

---

jenkins-scripts/docker/reprepro_updater.bash

The packages machines no longer uses sudo rights: b2f6a297c11331a936c81367f1a38f5e9d16bc4f
The GNUPGHOME directory no longer needs to be hardcoded: 3a2ac8fbbf6406ed044f4b89fc715db1e87beae8
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=reprepro_importer&build=86)](https://build.osrfoundation.org/job/reprepro_importer/86/)

Fixes for reprepro-importer

---

jenkins-scripts/lib/repository_uploader.bash

When using the testing (experimental) repository, disable the S3 uploads.
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=repository_uploader_packages&build=43388)](https://build.osrfoundation.org/job/repository_uploader_packages/43388/)

Disable S3 uploads for the testing repository

---

jenkins-scripts/dsl/brew_release.dsl

homebrew-core has stopped building bigsur bottles as of https://github.com/Homebrew/brew/pull/16019, so we will as well.

brew_release.dsl: disable bigsur bottling

---

release.py

Fix the fail in the check for github repository, that now displays the error:
```bash
Error running command (git ls-remote -q --exit-code https://foo:foo@github.com/gazebo-release/gz-cmake-release).
stdout: 
stderr: remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/gazebo-release/gz-cmake-release/'
```

Fix -release repository check in release.py

---

bloom/ros_gz/Dockerfile
bloom/ros_gz/README.md
bloom/ros_gz/rename-ros_gz-pkgs.bash

Three small things to finish with changes in the scripting:
* [Support conflicting versions of unofficial wrappers](https://github.com/gazebo-tooling/release-tools/commit/def8aa189b8869f7cc1c5a8a8b29b48f1cecdf40)
* [Complete README with custom RELEASE_REPO_URL](https://github.com/gazebo-tooling/release-tools/commit/1f0675200b460de5505e12c666b313a1ac04e1ba)
* [Important precedence when adding rosdep keys](https://github.com/gazebo-tooling/release-tools/commit/b0e7884e67ae0b46b09655db56d2cff902ca2cc9)

Patches and doc for GzHarmonic ros_gz creation

---

jenkins-scripts/docker/ros_gz-install-test-job.bash

The `ros_gz_sim` package for being able to run with ros launch needs to have the `gz-sim*-cli` package. This is probably a bug in `ros_gz` code.
Until we get that fixed, this PR adds automatically that package into the testing job so the smoke test can be run.
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros_gz_bridge-install-pkg_unofficial-any-manual&build=55)](https://build.osrfoundation.org/job/ros_gz_bridge-install-pkg_unofficial-any-manual/55/)

Install gz-sim*-cli on ros_gz testing builds

---

.github/workflows/ci.yaml
jenkins-scripts/dsl/gazebo_libs.dsl
jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/sdformat.dsl

The CI moves all CI done in our repositories to use the yaml documentation. After adding all distribution metadata to the yaml file in #1017, we are in the position of moving all the `-ci-pr_any-` generated jobs to use the yaml configuration. 
Until now the `-ci-pr_any-ubuntu-auto` jobs register all supported branches and dispatch the CI work. The new setup creates jobs based on the ubuntu distribution, so now the names are `-ci-pr_any-ubuntu-${distro}`. Each job register the supported branches (i.e: `-ci-pr_any-ubuntu-jammy` supports Garden and Harmonic branches).
Some details:
* The current `-ci-pr_any-ubuntu-auto` jobs can not be renamed to the new `-ci-pr_any-ubuntu-${distro}`.  This PR set a transition step of returning always `true` from the old jobs before removing the completely. …

Change all PR ci jobs (-ci-pr_any-) to use the yaml configuration

---

jenkins-scripts/docker/gz-source-generation.bash
jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy
jenkins-scripts/dsl/test.dsl

Following up https://github.com/gazebo-tooling/release-tools/pull/989 and https://github.com/gazebo-tooling/release-tools/pull/1008, some fixes and improve of the testing. Each commit is self-contained:
- Fix PACKAGE_NAME replaced by PACKAGE in previous changes e5b2ebc948a3bd557e90fc644315f781bbeb2825
- Change TARBALL_NAME bY S3_FILES_TO_UPLOAD 3602f12acd42de1198037aa55e6419ae68576bdd
- Use PROJECT_NAME_TO_COPY_ARTIFACTS instead of hardcoding test job 05afb08d89185f8deb759af51ea0aea2ce407e8b
- Support EXTRA_OSRF_REPO to be passed to OSRFReleasepy 7122876b484d54c32e84363a5ad4cf153fd518c5
- Handle ~ symbols in git tags https://github.com/gazebo-tooling/release-tools/pull/1024/commits/0543b683376e2d3d0eb5414ef10ab5af0347babe

Fixes for OSRFSourceCreation and tests related

---

source-repo-scripts/bump_dependency.bash

Replace the `~` separator characters with `-` in homebrew formula version strings to satisfy osrf/homebrew-simulation#2390.
See https://github.com/osrf/homebrew-simulation/pull/2450#discussion_r1351219074.

bump_dependency.bash: use - in version strings

---

release.py

Following  up #1014 part of https://github.com/gazebo-tooling/release-tools/issues/990
Easy to read commit by commit, changes done:
- Add support for testing repo releases 
- Remove sanity_use_prerelease_branch, obsolete
- Remove the use of obsolete OSRF_REPOS_SELF_CONTAINED
- Refactor: move tag repo to a method
- Remove obsolte NO_SRC_FILE
- Fix dry-run to output real actions
- Remove is_catking_package. Obsolete
- Improve output format
- Refactor: move Jenkins call to a method
- Remove UBUNTU_DISTROS: not in use
- Remove s3cmd check to facilitate changes
- Added error on non existing release repo

II part of clean up and refactoring release.py

---

jenkins-scripts/docker/gz-source-generation.bash
jenkins-scripts/dsl/_configs_/OSRFReleasepy.groovy
jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy
jenkins-scripts/dsl/test.dsl

The source generation jobs needs to use a given Ubuntu distribution since the `make package_source` coming from gz-cmake needs, indeed, to have gz-cmake installed b2e821565418cdef7162972a261d724a30d6b2e4. Not detected until now since the test case was gz-cmake which does not need a gz-cmake to be in place. Obviously. Changed to plugin in: 6866030dd31743c9ea84e8594ce7454d254bd1e0.
The installation of all gz-cmake available in the platform needs that plaform values reach the gz-source job from release.py. Done in 01cceab09ea52f1246e72f38567a3b3e188d38a1.
Not related but also in the PR a small change for OSRFReleasePy to use the new release.py script: 24cfea2feb72b5b873088758b38769affe3242ad

OSRFSourceCreation needs to install gz-cmake to generate sources

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ignition_collection.dsl
jenkins-scripts/dsl/sdformat.dsl

Part of https://github.com/gazebo-tooling/release-tools/issues/1027 and https://github.com/gazebo-tooling/release-tools/issues/1026

Create ign-ionic collection view and set up nightlies

---

jenkins-scripts/dsl/_configs_/OSRFReleasepy.groovy
jenkins-scripts/dsl/core.dsl

Part of https://github.com/gazebo-tooling/release-tools/issues/990. Add a real job to be a wrapper of releasepy calls inside the own Jenkins. Most of the work was already done for the test job so just a matter of creating the real job in core.dsl.

Add _releasepy job to be a wrapper of releasepy calls in Jenkins

---

jenkins-scripts/dsl/gz-collections.yaml

Harmonic release is stable and Ionic is being setup. We probably don't need nightlies anymore for Harmonic, @azeey ?

Remove nightly generation for Harmonic

---

jenkins-scripts/dsl/gazebo_libs.dsl
jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/ignition_collection.dsl

Part of #990 .
Create an index for packaging configuration composed by entries of source packages. Use it to generate the new source jobs that generates the tarballs.

Generate source jobs using an index of source packages

---

jenkins-scripts/lib/_homebrew_base_setup.bash
jenkins-scripts/lib/_homebrew_cleanup.bash

We're getting the "Another active Homebrew update process is already in progress" error very frequently now, so this is an attempt to fix it. ~It doesn't seem like a great approach since homebrew should be cleaning things up itself, but might be worth a try. At least, this is something others have [recommended](https://stackoverflow.com/a/40473139/283225). From the [logs](https://build.osrfoundation.org/job/ignition_transport-ci-pr_any-homebrew-amd64/1656/console), `brew` is able to install things before `_homebrew_cleanup.bash` is called, so I figured removing the locks when that script is done might fix the issue.~ The fix retries running `brew update` several times until it succeeds.

Retry brew update to fix errors about another active Homebrew process being active

---

jenkins-scripts/lib/_homebrew_base_setup.bash

#1032 added retries, but the problem hasn't gone away (https://build.osrfoundation.org/job/ignition_math-ci-pr_any-homebrew-amd64/2108/). Trying more retries and a longer sleep duration.

Increase `brew update` retries and sleep duration.

---

jenkins-scripts/dsl/gazebo_libs.dsl
jenkins-scripts/dsl/gz-collections.yaml

Fortress branches do not use `gz-` prefixes but `ign-`.

Fix Fortress branches prefix: gz -> ign

---

.github/workflows/ci.yaml
jenkins-scripts/dsl/dsl_checks.bash

Useful for local execution and more scalable than keep the code growing in the github action.
Add a small check for null values in 942e18991a210f06d0e42c0b5c01a46dd40c0f0a

Move github actions dsl checks to a script

---

jenkins-scripts/dsl/dsl_checks.bash
jenkins-scripts/dsl/gazebo_libs.dsl
jenkins-scripts/dsl/ignition.dsl

Some problems raised with broken paths for release-tools scripts. The PR fixes them and introduce a CI to avoid the problem in the future:
* [Fix compilation script path in -any- jobs](https://github.com/gazebo-tooling/release-tools/commit/0e9218e58ad18c92ce86b3280db1636640a7b870) . Broken -compilation.bash links in Citadel.
* [Remove death code in brew jobs](https://github.com/gazebo-tooling/release-tools/commit/a245628b3c890b9c1e3c92cfc49a53d4cd9b8ee5). Death code pointing to non existing scripts in Brew.
* [Add check for existing scripts](https://github.com/gazebo-tooling/release-tools/commit/ab9b95d44a37886c4d5708125c150c9da72e3c67). CI test to check for the links in the repo.

Fix broken script links generated in DSL code. Added CI test.

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/_configs_/OSRFReleasepy.groovy
jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy
jenkins-scripts/lib/repository_uploader.bash

A couple of small improvements in the releasing pipeline:
* [Be sure that we use a final / in S3_UPLOAD_PATH](https://github.com/gazebo-tooling/release-tools/commit/171ab976b2dc4e6a72a801e183ea83f0bc237cc9).
* [Make OSRFRelease to fail if release.py fails](https://github.com/gazebo-tooling/release-tools/commit/a04482e1b7dd2bd975a4ac7b8b9d0eee76462c59)

Improvements in the releasing pipeline

---

jenkins-scripts/docker/gz-source-generation.bash
jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy
jenkins-scripts/dsl/dsl_checks.bash
jenkins-scripts/dsl/gazebo_libs.dsl
jenkins-scripts/dsl/test.dsl

This has the benefit of not to have the same logic duplicated in different places, the one that builds the labels for tagging when releasing. It goes directly from release.py to the OSRFSourceCreation jobs.

OSRFSourceCreation: use git refs directly instead of rebuild it

---

jenkins-scripts/dsl/gz-collections.yaml

There is a discrepancy in [fortress gz-collections.yaml](https://github.com/gazebo-tooling/release-tools/blob/8c8880e00854bde1cbc4091e8e0c61759d1f03fe/jenkins-scripts/dsl/gz-collections.yaml#L154-L157) and [collection-fortress.yaml](https://github.com/gazebo-tooling/gazebodistro/blob/dfd98e79e17a146a25baaa72f7ef2ad07ff6f0ab/collection-fortress.yaml#L48-L50).
In the gz-collections it says ign-sensors7, but in collection-fortress it says ign-sensors6 (same happens for physics).

Fix sensors and physics versions

---

jenkins-scripts/dsl/gazebo_libs.dsl

There is a problem with the github checkout in `-ci-${branch}-` that don't match the github repository name, i.e: gz-common as github repository name and ign-common as library name comming from yaml.
Let's force the code to be always in sync by adding the checkout subdir parameter to `OSRFGitHub.create` and use the same variable in `BUILDING_SOFTWARE_DIRECTORY`.

Fix dsl to assure that BUILDING_SOFTWARE_DIRECTORY and git checkout dir are in sync

---

.github/ISSUE_TEMPLATE/new_collection.md

Removed checklist item for adding collection to Gazebo Answers since we're not using it any more.

Remove references to answers.gazebosim.org

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Use the fully qualified formula name (with the `osrf/simulation/` prefix) when checking for dependencies. Remove logic for tinyxml2@2.6.2 dependencies since it is not used by any current formulae.
Recently, the gz-physics2 CI builds stopped finding the `dartsim@6.10.0` dependency; this should fix it.
Testing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics-ci-ign-physics2-homebrew-amd64&build=133)](https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics2-homebrew-amd64/133/) https://build.osrfoundation.org/job/ignition_physics-ci-ign-physics2-homebrew-amd64/133/

brew CI: use full tap name

---

jenkins-scripts/lib/project-install-homebrew.bash

We have started documenting how to use the `ci_matching_branch/` naming pattern to use custom branches from tooling repositories in pull request CI in https://github.com/gazebosim/docs/pull/377. This PR will add the `ci_matching_branch/` functionality to the `install_bottle` jobs in the following way:
* If the release-tools branch (`RTOOLS_BRANCH`) for an `install_bottle` job starts with `ci_matching_branch/`, then it will try to check out a matching branch from the `osrf/homebrew-simulation` tap.
As an example for when this could be used, I'd like to re-enable a test for the `gz-sim7` formula that has been disabled for macOS Monterey since a fix in https://github.com/gazebosim/gz-physics/pull/529 has been merged and released. The test is enabled in …

Add ci_matching_branch/ for bottle install jobs

---

.github/workflows/ci.yaml
check_releasepy.bash
release.py

The PR changes the release.py logic to be able to use the new generation of tarball that happens on Jenkins instead of using the dev local machines. See the linked docs update for a general usage and data flow overview https://github.com/gazebosim/docs/pull/403
**No changes in releasing workflow and the release.py call:** Note that the tag of the project code to be built still happens in the local dev system so the workflow is the same than now: go to the source code you want to build and run `release.py` with the same arguments than now. Instead of calling `-debbuilders` there will a chain of actions composed 
PR is quite long, probably easier to read change by change to understand the logic:
1. Remove all current code related to tarball generation …

Change release.py to use the new centralized tarball approach

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

@Crola1702 reported that Bionic builds were failing continuously something that I tried to debug in other occasions and could not reproduce the error locally, so flakiness is involved in the issue. Error on Bionic build is:
```
#14 0.607 Warning: apt-key output should not be parsed (stdout is not a terminal)
#14 0.625 Executing: /tmp/apt-key-gpghome.pDPnL9osSh/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
#14 0.883 gpg: keyserver receive failed: Cannot assign requested address
```
gpg is unable to get packages.osrfoundation,org key under some circumstances.
My hypothesis has to do with the: gpg/ssl/apt-key libraries/apps versions on Bionic that might not implement new/modern aspect of a protocol that has been updated in …

Alternative keyserver for Bionic

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

After #1054 the brew builds are broken with problem to execute the detection of the major versions. Problem seems to be in the bash code of `jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash` that was modifying the value passed as the relative path for workaround to force the `ign-` prefix injection. We should not need that anymore.
Failing:
gz-cmake [![Build Status](https://build.osrfoundation.org/job/gz_cmake-ci-pr_any-homebrew-amd64/1/badge/icon)](https://build.osrfoundation.org/job/gz_cmake-ci-pr_any-homebrew-amd64/1/)
This PR:
gz-cmake [![Build Status](https://build.osrfoundation.org/job/gz_cmake-ci-pr_any-homebrew-amd64/2/badge/icon)](https://build.osrfoundation.org/job/gz_cmake-ci-pr_any-homebrew-amd64/2/)

Fix brew -ci-pr_any-: remove workarounds in project-default bash file

---

jenkins-scripts/dsl/gazebo_libs.dsl

Remove the workaround since it won't work with ign- jobs generated for Citadel in modern branches since there is
no ign- formulas anymore.
The brew CI would be handle in the same way that Linux for non stable branches, see https://github.com/gazebo-tooling/release-tools/issues/1044.

Do not integrate all brew pr_any job with all branches

---

jenkins-scripts/dsl/dsl_checks.bash
jenkins-scripts/dsl/gazebo_libs.dsl
jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/ignition.dsl
jenkins-scripts/dsl/ros_gz_bridge.dsl
jenkins-scripts/dsl/sdformat.dsl

Move Brew jobs to be generated by gz-collections.yaml.
Mainly reuse a good bunch of the code in `gazebo_libs` and include a brew generating function f4fa9305b50de3c2b07717b27073de014aacd322 and remove the current jobs generated by `ignition.dsl` in 83eab4b4e1d8d72b90d93c2802a4fc6f755d6c2b

Change homebrew -ci- daily jobs to use gz-collections.yaml 

---

jenkins-scripts/dsl/gz-collections.yaml

In gz-sim repository, the defined branch for gz-sim in fortress is named: `ign-gazebo6`.
This was changed in https://github.com/gazebo-tooling/release-tools/pull/1040

Fix ign-gazebo6 branch name

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

After many problems related to an apt-key failure that has poisoned many of our docker cache, this PR should invalidate docker cache. This PR will help to keep the cache clean for a couple of months to facilitate image rotation.
See #1069

INVALIDATE_DOCKER_CACHE in Bionic and Focal for the next two months

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Use gzdev `--keyserver` option to pass ~~keys.openpgp.org~~ (opengpg is not working for our key) hkps://pgp.surf.nl on Bionic / Focal for trying to mitigate https://github.com/gazebo-tooling/release-tools/issues/1069.
Needs testing together with gzdev PR https://github.com/gazebo-tooling/gzdev/pull/73

Use keys.openpgp.org keyserver on gzdev for Bionic/Focal

---

jenkins-scripts/dsl/gazebo_libs.dsl
jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

My approach in this PR has been trying to be explicit with the checkout directory for brew instead of trying to calculate it from PROJECT (lib name) and `PROJECT_FORMULA`. Accept to pass environment variables to the values and fallback to keep current behaviour, see 8c175f40dc42a593588a24712014f6c44462320f.
Change DSL to use that approach in 03cc3d0b5c09ebf86fa36b7753cb713df6b523d1
Refactoring code to use a single function to setup the bash call, I disliked the idea of having `PROJECT_FORMULA` from DSL since it really has no notion of "package-name" so I removed it and leaved as it was before (using `PROJECT + detect_cmake_major_version` and just fix the ign- value when going to the project to be ignition-, see def89176fa57182791e0928b6f642bfd3309e897

Fix brew ign- formula names

---

jenkins-scripts/gazebo-one_liner-homebrew.bash
jenkins-scripts/lib/_homebrew_cleanup.bash
one-line-installations/gazebo.sh

I noticed the following failed CI job and made a few fixes after some debugging:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=2959)](https://build.osrfoundation.org/view/ign-citadel/job/gazebo-install-one_liner-homebrew-amd64/2959/) https://build.osrfoundation.org/view/ign-citadel/job/gazebo-install-one_liner-homebrew-amd64/2959/
That first failure has the following error:
~~~
++ brew cleanup --prune-prefix
./scripts/jenkins-scripts/lib/_homebrew_cleanup.bash: line 34: brew: command not found
~~~
The fix in https://github.com/gazebo-tooling/release-tools/commit/8e852017192e5f4c93f07a3107f60f72bcc981bc is to use `${BREW_BINARY}` to match the rest of the script.
After that I saw a `brew doctor` complaint about `sbin` …

Fixes for gazebo-install-one_liner-homebrew-amd64

---

jenkins-scripts/dsl/gz-collections.yaml

The list of CMake warning exclusion did not include sdformat before.

Exclude sdformat CMake warnings on brew in gz-collections.yaml

---

jenkins-scripts/lib/homebrew_formula_pullrequest.bash

The homebrew formula pull requests sometimes are triggered twice, but the second pull request is not created due to overlapping branch names. This gives each pull request a unique branch name so that duplicate pull requests will be created, and the maintainer can figure out which has the correct tarball SHA.
Fixes #1020.

homebrew_formula_pullrequest: unique branch name

---

.github/workflows/ci-releasepy.yaml
.github/workflows/ci.yaml

Split the releasepy checks to its own file and trigger it only on changes to that file since it does not use any other file or resource in the repo.

Split CI: Move releasepy checks to its own workflow

---

.github/workflows/ci.yaml

Modify the GitHub actions workflow to rely on `paths:` for triggering the CI instead of having a custom logic of detecting changes on dsl directory.

Clean up DSL CI by using GitHub actions paths

---

jenkins-scripts/dsl/gz-collections.yaml

ign-common4 (Fortress) is configured to run on `focal`, but we were excluding the abichecker from the `focal` ci_configs.
https://build.osrfoundation.org/job/gz_common-abichecker-any_to_any-ubuntu-jammy-amd64/ only triggers on `gz-common5`.

Do not exclude gz-common from focal ci_configs

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Need to exclude gz-sim and gz-launch from Citadel. To avoid adding harcoded values in the DSL, the declarative approach is to create a new ciconfig for Citadel, just by duplicating the win configuration and make the exclusions for the libraries.

Make Citadel to use custom ciconfig to exclude gz-sim/gz-launch

---

jenkins-scripts/lib/homebrew_bottle_creation.bash

`URI.decode` has been obsolete for a while in Ruby, and with Homebrew's recent change to use Ruby 3.1 across the board, this call needs to be changed in our bottle creation script, which now causes bottle builds to fail. `URI::DEFAULT_PARSER.escape` appears to be equivalent for our purposes.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder%2Flabel%3Dosx_monterey&build=1354)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_monterey/1354/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/1354/label=osx_monterey/console
~~~
++ brew ruby -e 'puts URI.decode(JSON.load(IO.read("gz-physics7--7.0.0_2.monterey.bottle.json")).values[0]['\''bott …

homebrew_bottle_creation: fix ruby syntax

---

jenkins-scripts/dsl/core.dsl

Expose `REPREPRO_GIT_BRANCH` variable as a Jenkins parameter

Implement REPREPRO_GIT_BRANCH for reprepro importer

---

bloom/ros_gz/rename-ros_gz-pkgs.bash

When creating the ros_gz unofficial packages, if `GZ_RELEASE_TO_CONFLICT` is set the conflict on the original ROS package is lost. For example: releasing Harmonic packages for Humble that conflict with the unofficial Garden packages make the packages not to conflict with `ros-humble-ros-gz`.
The PR preserves the original conflict and add a new one when using `GZ_RELEASE_TO_CONFLICT`

ros_gz wrappers: include ROS package in conflicts when adding a second conflict

---

jenkins-scripts/docker/lib/boilerplate_prepare.sh

There were some issues with unattended upgrades making builds fail ([See](https://build.osrfoundation.org/job/gz_sim-abichecker-any_to_any-ubuntu-jammy-amd64/120)). After some research it seems this is due to release-tools installing packages that are already provisioned when the image for the agents is built. This PR removes all dependencies that are installed through this mechanism.

Removes apt-get installed packages from Dockerfile

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/core.dsl

We want to be sure that there is a nightly node labeled always, not just during the nightly creation or generation. The PR uses a cron expression that tries to be sure that we still run it at 9:00, 10 minutes before the nightly creation but also add the rest of the day.

Change nightly labeler to run every 20min all day

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

This is currently broken, so disable for now to un-break CI.
Testing with `ign-math6`:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_math-ci-ign-math6-homebrew-amd64&build=24)](https://build.osrfoundation.org/job/gz_math-ci-ign-math6-homebrew-amd64/24/) https://build.osrfoundation.org/job/gz_math-ci-ign-math6-homebrew-amd64/24/

brew CI: temporarily disable pip install

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Try this until we switch to a venv.
This should allow `pytest` to be installed, which provides better feedback to jenkins about python test results.
Testing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_math-ci-ign-math6-homebrew-amd64&build=25)](https://build.osrfoundation.org/job/gz_math-ci-ign-math6-homebrew-amd64/25/) https://build.osrfoundation.org/job/gz_math-ci-ign-math6-homebrew-amd64/25/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdf14-homebrew-amd64&build=25)](https://build.osrfoundation.org/job/sdformat-ci-sdf14-homebrew-amd64/25/) https://build.osrfoundation.org/job/sdformat-ci-sdf14-homebrew-amd64/25/

brew CI: pip install with --break-system-packages

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/core.dsl

Although the XML generated by using several cron invocations seemed to be fine the reality is that the generated code did not work and the last entry was overwriting the first one. After modifying the config manually the XML seems to be using several lines for different entries. The PR modifies the code to use this approach.
Patching #1113

Fix cron DSL entries for the _nightly_node_labeler

---

jenkins-scripts/dsl/_configs_/Globals.groovy
jenkins-scripts/dsl/gazebo_ros_pkgs.dsl

Modify the DSL to remove the jobs that were running on Rolling/Jammy since this combination is no longer supported.
Also removed in the PR the jobs for Bionic/Melodic since it is EOL.

Remove rolling/jammy + melodic/bionic combinations in gazebo_ros_pkgs

---

jenkins-scripts/docker/gz-source-generation.bash
jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy

The `PACKAGE` parameter in -source jobs is being populated by the args of `release.py` using always hyphens even if the `project` name in CMakeLists.txt of the package (and thus the tarball generated) is using underscores. Some other parts of the infrastructure also applies this same naming.
This is making the gz-fuel-tools -source package to fail since the -source jobs check for existence of `{canonical_package_name}-\${VERSION}.tar.*` tarball. This PR relax that restriction and make a second pass to just `*-\${VERSION}.tar.*` to grab this exception.
Tested: 
* _test_gz_source [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_gz_source&build=90)](https://build.osrfoundation.org/job/_test_gz_source/90/)
* Cloned _test_gz-fuel-tools9-source [![Build …

Fix -source jobs to deal with packages with underscores (i.e gz-fuel_tools)

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

gz-transport Python tests are failing because Python bindings were removed in the latest update of protobuf homebrew bottle. It seems like the [recommended](https://github.com/protocolbuffers/protobuf/tree/main/python#installation) way to install the Python bindings is through `pip`. Since this will be needed for anything above gz-transport, I thought we should just add it here to `PIP_PACKAGES_NEEDED` as a global dependency.

brew: pip install protobuf in CI

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

This should be merged after https://github.com/gazebo-tooling/gzdev/pull/86
The PR update the gzdev calls to remove the deprecated '--keyserver' call (was doing nothing currently) and use the new `repository purge` action to remove all previous gzdev configurations done on the image. This should avoid problems with docker cache and updated gzdev configurations.

Update gzdev to use "purge" and remove the deprecated "--keyserver"

---

jenkins-scripts/tools/detect_cmake_major_version.py

Some of the sequences in the regex patterns are not valid in python string literals (such as `\(`, so use raw strings instead (see [related stack overflow answer](https://stackoverflow.com/a/52335971)). This fixes some `SyntaxWarning`s when running the script with `python@3.12`:
~~~
++ python3 detect_cmake_major_version.py /github/workspace/CMakeLists.txt
/github/workspace/detect_cmake_major_version.py:15: SyntaxWarning: invalid escape sequence '\('
old_version = re.search('set *\( *PROJECT_MAJOR_VERSION +(\d+)', txt)
/github/workspace/detect_cmake_major_version.py:16: SyntaxWarning: invalid escape sequence '\('
gazebo_version = re.search('set *\( *GAZEBO_MAJOR_VERSION +(\d+)', txt)
/github/workspace/detect_cmake_major_version.py:17: SyntaxWarning: invalid escape sequence '\(' …

detect_cmake_version.py: use raw regex strings

---

check_releasepy.bash
jenkins-scripts/dsl/_configs_/OSRFSourceCreation.groovy
jenkins-scripts/dsl/test.dsl
release.py

Following up https://github.com/gazebo-tooling/release-tools/issues/1102#issuecomment-1890772414 and https://github.com/gazebo-tooling/release-tools/pull/1105.
Add extra checks for the tests that assure the PACKAGE and PACKAGE_ALIAS. 
If needed some tweaks and relaxation of safety checks with names to operate correctly, most important
* [Use gz- in SOURCE_REPO_URI](https://github.com/gazebo-tooling/release-tools/pull/1109/commits/91086d599029df542a3ea34ba426326df6e2321d)
* [Disable safety check on package-name tarball](https://github.com/gazebo-tooling/release-tools/pull/1109/commits/60e49a73bb0abc4ee3d7b248882c095b643b5a54)
Tested with real ign-rendering 6.6.3: 
- source: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz-rendering6-source&build=4)](https://build.osr …

Make release.py to automatically deal with ign- Citadel packages

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Starting from jammy the official docker images to generate armhf can be used through the dockerx platform command. To support jammy, I'm reverting the logic here to restric the use of osrf/ images to focal.
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz-cmake3-debbuilder&build=1282)](https://build.osrfoundation.org/job/gz-cmake3-debbuilder/1282/)

For armhf use docker ubuntu images instead of osrf/ for Jammy onwards

---

jenkins-scripts/docker/lib/docker_run.bash

Follow up of #1135. Needs platform command for ubuntu different

Use platform in docker call for amrhf builds on Noble

---

jenkins-scripts/dsl/gazebo_libs.dsl
jenkins-scripts/dsl/logs/generated_jobs.txt

The DSL generation in `gazebo_libs` is based on an approach of building two indexes before looping over the gz-collections.yaml file. That approach does not respect the fact of having different ci_config (CI confgurations) that use the same platform and will overwrite the first one found if that situation occurs. The index build process also did not load the exclusion clauses included in the ci_configuration which are useful to be parsed when building the index.
The changes in this PR modify it to mainly:
* Loop over the gz-collections.yaml directly the first time to generate the jobs that are linked to lib branches `gz-fooX`. 
* While looping it build a branch_index that will be used to build the pr jobs that are in the form `gz-foo-pr_any-` not based on the branch directly.
* Loop over …

Rewrite DSL generation to remove the approach based on Indexes

---

jenkins-scripts/tools/outdated-job-runner.groovy

Outdated job runner can fail if there is a job that doesn't contain any builds (`project.lastBuild.getTime()` raises a NullPointerException) such as: [gz_ionic-install_bottle-homebrew-amd64](https://build.osrfoundation.org/job/gz_ionic-install_bottle-homebrew-amd64/) (checked in May 23rd 2:15 UTC)
This PR adds the condition to run the job if `project.lastBuild` is null
Failed build: https://build.osrfoundation.org/job/_outdated_job_runner/7800/

Outdated job runner: Add condition to run job if it hasn't been run yet

---

README.md
jenkins-scripts/dsl/tools/README.md
jenkins-scripts/dsl/tools/get_collections_from_package_and_version.py

A helper script to obtain the Gazebo collection/releases given a library and a major version. It uses the gz-collections.yaml as the database to search for the metadata.

Include a script to obtain gazebo releases for a given library

---

jenkins-scripts/lib/_homebrew_cleanup.bash

The `git fsck` call added to `_homebrew_cleanup.bash` in f5e9ef9ad6bef555ca4e30d04d4c10f3ff59bc4e is trying to improve reliability, but it can fail if git from brew is broken. Since this script is removing all installed formulae,
just continue if `git fsck` fails, and it should remove the broken `git` for us.
Testing on Mac-four:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_cmake3-install_bottle-homebrew-amd64&build=244)](https://build.osrfoundation.org/job/gz_cmake3-install_bottle-homebrew-amd64/244/) https://build.osrfoundation.org/job/gz_cmake3-install_bottle-homebrew-amd64/244/

homebrew_cleanup: don't fail on git fsck

---

jenkins-scripts/docker/gz_rendering-compilation.bash

This was added in #456, but now it seems to be causing a cmake warning for an unused manually specified variable:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_rendering-ci-main-noble-amd64&build=24)](https://build.osrfoundation.org/job/gz_rendering-ci-main-noble-amd64/24/) https://build.osrfoundation.org/job/gz_rendering-ci-main-noble-amd64/24/cmake/
~~~
CMake Warning:
Manually-specified variables were not used by the project:
SKIP_optix
~~~
testing with this branch:
* 1 test failure expected, but no cmake warnings [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_rendering-ci-main-noble-amd64&build=25)](https://build.osrfoundation.org/job/gz_rendering-ci-main-noble-amd64/25/) https://build.osrfoundation.org/job/gz_rendering-ci-main-nobl …

gz-rendering9+: build without -DSKIP_optix

---

jenkins-scripts/lib/windows_env_vars.bat

Needed by gazebosim/gz-utils#134.
Also, I think that comment is outdated? I think we are still using this for releases newer than garden.

Add spdlog to VCPKG_DEPENDENCIES_LEGACY

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Needed to make a pre-release of gz-cmake4.

Use stable branch for gz-cmake4

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Needed to make a pre-release of gz-utils3.

Use stable branch for gz-utils3

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Needed to make a pre-release of gz-math8.

Use stable branch for gz-math8

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Needed to make a pre-release of gz-gui9.

Use stable branch for gz-gui9

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Needed to make a pre-release of gz-msgs11.

Use stable branch for gz-msgs11

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Needed to make a pre-release of gz-transport14.

Use stable branch gz-transport14

---

source-repo-scripts/source_changelog.bash

We'd like to print the baseline version for the changelog of a given release, so print a formatted line with this info in our changelog script.

source_changelog.bash: print baseline version

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Ionic CI: use stable branch for gz-physics8

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Ionic CI: use stable branch for gz-common6

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Ionic CI: use stable branch for gz-sim9

---

jenkins-scripts/dsl/_configs_/OSRFLinuxCompilation.groovy

Fixes https://github.com/gazebosim/gz-sim/issues/2555

Workaround to exclude false positives in GCC warning plugin

---

jenkins-scripts/dsl/brew_release.dsl

Homebrew has already stopped supporting monterey as of https://github.com/Homebrew/brew/pull/18314.
With this change, any bottle builds will only attempt to build bottles for ventura, until we add CI machines with a newer OS version.

brew supported distros: replace monterey with sonoma

---

release.py

The only piece difficult to test that we changed in #1150 is failing :( 
The ssh URL is using : instead of / and makes the vendor package PR to fail. Tested in https://github.com/gazebo-release/gz_msgs_vendor/pull/4

Fix release.py ssh clone URL for vendor packages

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

One of our brew build scripts has a `HOMEBREW_PREFIX` variable to represent the location where brew is installed (either `/usr/local` for Intel macOS machines or `/opt/homebrew` for arm macOS machines), but it also has many paths hard-coded to /usr/local. In preparation for supporting arm-based CI machines, use the `HOMEBREW_PREFIX` variable more widely.

Replace /usr/local with HOMEBREW_PREFIX part 1

---

jenkins-scripts/docker/debian-ratt-builder.bash
jenkins-scripts/docker/gz-source-generation.bash
jenkins-scripts/docker/lib/_common_scripts.bash
jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash
jenkins-scripts/docker/lib/boilerplate_prepare.sh
jenkins-scripts/docker/lib/debbuild-backport.bash
jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/docker/lib/debbuild-bloom-base.bash
jenkins-scripts/docker/lib/debian-git-repo-base.bash
jenkins-scripts/docker/lib/docker_generate_dockerfile.bash
jenkins-scripts/docker/lib/gazebo_ros_pkgs-check-release.bash
jenkins-scripts/docker/lib/generic-abi-base.bash
jenkins-scripts/docker/lib/generic-install-base.bash
jenkins-scripts/docker/lib/gzdev-base-linux.bash

The PR mainly implement the option to use `SHELL_ON_ERRORS` variable to define a trap in the `build.sh` script that will allow a local run of it that permits the jump into a shell inside the container if something fails. Relevant lines are in `jenkins-scripts/docker/lib/_common_scripts.bash`. This should help with #923 .
To avoid code duplication all over the place the PR also refactor the creation of the initial lines in `build.sh` to be in a single function include shebang, SHELL_ON_ERRORS, set -ex and timing.
Tested it in: [![Build Status](https://build.osrfoundation.org/job/gz_msgs-ci-pr_any-noble-amd64/43/badge/icon)](https://build.osrfoundation.org/job/gz_msgs-ci-pr_any-noble-amd64/43/)

Refactor build.sh initial lines and include SHELL_ON_ERRORS

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Alternative to https://github.com/gazebo-tooling/release-tools/pull/1193.
This should ensure that freshly installed `pip` packages are used.
Test with this branch:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_transport-ci-gz-transport14-homebrew-amd64&build=27)](https://build.osrfoundation.org/job/gz_transport-ci-gz-transport14-homebrew-amd64/27/) https://build.osrfoundation.org/job/gz_transport-ci-gz-transport14-homebrew-amd64/27/

brew CI: use python venv for pip installs

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

Follow-up to #1194:
* https://github.com/gazebo-tooling/release-tools/commit/ad0867bc76c415e93756f74e40b4f9663f1635e3: use `hash -r` to ensure that we use the correct `python3` executable
* https://github.com/gazebo-tooling/release-tools/commit/55fc23a7c1a9a486c5d83bf87dfb46dd2090899b: add the brew python3's site-packages to `PYTHONPATH` so we can use the installed python bindings from gazebo formulae
* python test failures: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdf15-homebrew-amd64&build=23)](https://build.osrfoundation.org/job/sdformat-ci-sdf15-homebrew-amd64/23/) https://build.osrfoundation.org/job/sdformat-ci-sdf15-homebrew-amd64/23/
* clean: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdf15-homebrew-amd6 …

brew CI: use correct python and set PYTHONPATH

---

release.py

When creating vendor packages for Harmonic versions, the script starts from the default branch instead of the branch that corresponds to the matching ROS version. Here's an example of an incorrect PR https://github.com/gazebo-release/gz_sim_vendor/pull/6

release.py: Use correct base branch when creating vendor package PRs

---

jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash

The gz-sim python system loader integration test is having trouble finding the protobuf python bindings, which are installed in a python virtual environment as of #1194.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_sim-ci-gz-sim9-homebrew-amd64&build=30)](https://build.osrfoundation.org/job/gz_sim-ci-gz-sim9-homebrew-amd64/30/) https://build.osrfoundation.org/job/gz_sim-ci-gz-sim9-homebrew-amd64/30/
Excerpt from python system loader test log:
~~~
309: [ RUN      ] PythonSystemLoaderTest.LoadMultipleSystems
309: (2024-11-10 12:40:35.172) [info] [Server.cc:145] Loading SDF world file[/Users/jenkins/jenkins-agent/workspace/gz_sim-ci-gz-sim9-homebrew-amd64/gz-sim/test/worlds/python_system_loader.sdf].
309: (2024-11-10 12:40:35.339) [info] [SystemManager.cc:54] …

brew CI: prepend venv site-packages to PYTHONPATH

---

jenkins-scripts/lib/colcon-default-devel-windows.bat

Preparing to execute conda enviroments, the existing colcon script does use of colcon as if it was installed in the system. While this is true in the current provisioning, for conda we use colcon declared in the toml file what also facilitates the use of it locally.
The PR relocates the code that helps with the existing `ignition` names (Gz Fortress) into a section after the dependencies/environment files are installed. 
Testing it here [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_sim-pr-win&build=1042)](https://build.osrfoundation.org/job/gz_sim-pr-win/1042/)

Windows colcon: relocate Fortress workaround for ignition names

---

jenkins-scripts/dsl/brew_release.dsl
jenkins-scripts/lib/homebrew_bottle_creation.bash

While removing the osrf-migration token I noticed that it is being used in bottle_job_builder for authenticating the `hub` cli . We need it even if there are no push/clone operations involved, otherwise the `hub` cli is asking for credentials.
This PR changes the osrf-migration user to use existing osrfbuild token.

Replace osrf-migration token by osrfbuild-token in bottle_job_builder

---

jenkins-scripts/dsl/_configs_/OSRFCredentials.groovy
jenkins-scripts/dsl/test.dsl

This PR replaces the `test.dsl` in #1206 and checks the two main token that are going to be used for the `osrfbuild` user as discussed in https://github.com/gazebo-tooling/release-tools/pull/1206#issuecomment-2483688025:
* OSRFBUILD_GITHUB_TOKEN: for git operations and pull requests
* OSRFBUILD_JENKINS_TOKEN: for authenticate into the server
The credential class also has an `allowOsrfbuildToRunTheBuild` that can restrict which projects can be build by the `osrfbuild` user when making remote calls.
Operations needs to be done in production:
* Generate a new `OSRFBUILD_JENKINS_TOKEN` for the `osrfbuild` user with the id of `
* Change the type of the `OSRFBUILD_GITHUB_TOKEN` or generate a new one and set it up as a `usernamePassword` with the ID `github-osrfbuild-credentials`

Add OSRFcredentials class and test for DSL

---

jenkins-scripts/dsl/brew_release.dsl
jenkins-scripts/lib/_homebrew_github_commit.bash
jenkins-scripts/lib/_homebrew_github_setup.bash

The PR removes the injection of the GITHUB token into `jenkins-scripts/lib/_homebrew_github_setup.bash` to work using the same variable injected via credentials plugin. @scpeters if you please find a chance to test it, appreciated.

Remove filesystem token for Brew. Use crendential plugin

---

jenkins-scripts/tools/outdated-job-runner.groovy

Same logic as #1214 applied to outdated job runner (that also has been failing because of this problem)

Fix outdated_job_runner when nodes are not fully available (Apply #1214)

---

jenkins-scripts/tools/label-assignment-backstop.groovy

Fix the plain wrong code to use the right API call `node.toComputer().IsOnline()`. The call is not safe since `toComputer()` can return NULL in cases were nodes are not fully initialized.
`node.toComputer()?.IsOnline()` should deal with it.
Failing [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_nightly_node_labeler&build=17250)](https://build.osrfoundation.org/job/_nightly_node_labeler/17250/)
Fixed [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_nightly_node_labeler&build=17251)](https://build.osrfoundation.org/job/_nightly_node_labeler/17251/)

Fix nightly_labeler when nodes are not fully available

---

jenkins-scripts/dsl/gazebo.dsl

One more note: to release gazebo11 the release.py command needs a tweak:
```
release.py gazebo11 <version> --source-repo-uri https://github.com/gazebosim/gazebo-classic
```
Otherwise it will return a 403 problem (can be checked in Jenkins log, it is using gazebo instead of gazebo-classic as repo name).
I tested it to release 11.15.0:
https://github.com/gazebosim/gazebo-classic

Add gazebo11 source job to DSL

---

release.py

The nightly call was failing without an error message although the same `--dry-run` was just fine.
The PR adds right error reporting an fixes the bad handling of auth credentials by enforcing the parameter in the function call.
Failing: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition-__upcoming__-nightly-scheduler&build=32)](https://build.osrfoundation.org/job/ignition-__upcoming__-nightly-scheduler/32/)
Working: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition-__upcoming__-nightly-scheduler&build=36)](https://build.osrfoundation.org/job/ignition-__upcoming__-nightly-scheduler/36/)

Fix auth in release.py for nightly: right handle --auth values in Jenkins calss

---

jenkins-scripts/dsl/gazebo.dsl

Missing permissions in gazebo11-debbuilder. Retriggered 11.15.1 manually with my user but this is the right patch.

Need osrfbuild permissions in gazebo11-debbuilder

---

jenkins-scripts/lib/colcon-default-devel-windows.bat

The `dxdiag` binary on Windows can be useful to debug problems related to the configuration and support of Nvidia in the different AWS machines. It can output to a file and the code prints that to the Console for reference.
Used: https://build.osrfoundation.org/job/_test_gz_rendering_ogre23-pr-cwin/20/consoleFull#console-section-0

Print dxdiag output on Windows colcon builds

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Gz-jetty major version is not being ignored, producing an error in [jetty-nightly-scheduler](https://build.osrfoundation.org/job/ignition-jetty-nightly-scheduler/5/console):
```
+ python3 ./scripts/release.py gz-jetty1 nightly --auth osrfbuild:**** --release-repo-branch main --nightly-src-branch main --upload-to-repo nightly
Downloading releasing info for gz-jetty1
Error running command (git ls-remote -q --exit-code https://github.com/gazebo-release/gz-jetty1-release).
stdout: 
stderr: fatal: could not read Username for 'https://github.com/': No such device or address
```

Ignore gz-jetty major version

---

conda/envs/legacy/pixi.lock
conda/envs/legacy/pixi.toml

To reduce the number of changes brought by `pixi update` on each iteration, I'm setting some of the versions in pixi.toml for part of the relevant software.
While testing this, I noticed that the we can declare which msvc compiler to use via toml configuration (that previously was included as a dependency by one of versions used by the explicit set of dependencies in this toml file). I'm declaring it explicitly here until we decide in we want to use compilers this way or use the system installed ones.

Conda legacy env: use vs2019 package and fixed versions

---

jenkins-scripts/lib/colcon-default-devel-windows.bat

We should not expect colcon to be installed before pixi installation. The PR relocates the code before the compilation where it is still needed for Fortress ignition names.
Testing it [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_math-pr-win&build=250)](https://build.osrfoundation.org/job/gz_math-pr-win/250/)

Relocate colcon code after pixi installation

---

release.py

It the version in the local CMakeLists.txt file doesn't match the intended release version, released.py currently starts the source job, which gives the false impression that everything is working well. However, the source job will fail and debbuilder jobs are never triggered.  This patch adds a sanity check so that released.py fails if the release version doesn't match what's in CMakeLists.txt.
To test the script can parse versions correctly, I ran the following from the **directory containing** `release.py`:
```bash
for d in ~/ws/ionic/src/{gz-*,sdf*}; do echo -n "$d "; python3 -c "import release; print(release.get_version_from_cmake(\"$d/CMakeLists.txt\"))"; done
```

Add sanity check on version in CMakeLists.txt file

---

jenkins-scripts/lib/colcon-default-devel-windows.bat

There is a problem with the production Windows agents provisioned with the vcpkg static cache. Since it is not affecting to the production CI builds, this PR restrict the fail on bad GPU setup to just the testing that uses Conda.
Testing:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_sim-pr-win&build=1131)](https://build.osrfoundation.org/job/gz_sim-pr-win/1131/)

Only run the GPU test on Conda

---

conda/README.md
conda/envs/legacy_ogre23/pixi.lock
conda/envs/legacy_ogre23/pixi.toml

The PR adds a new conda environment that is a twin of the legacy environment but bumps the ogre-next package from 2.2.x to 2.3.x:
```diff
--- envs/legacy/pixi.toml	2025-01-10 18:17:45.242337893 +0100
+++ envs/legacy_ogre23/pixi.toml	2025-01-10 18:19:35.096468104 +0100
@@ -24,7 +24,7 @@
libsqlite = "*"
libzip = "*"
ogre = "1.10.12.1.*"
-ogre-next = "2.2.*"
+ogre-next = "2.3.*"
openssl = "*"
protobuf = "3.14.0.*"  # closest with py3.9 ABI to jammy 3.12
pybind11 = "*"
```
The Goal is to use it with Harmonic and Ionic. We can start using it for Jetty although at this point of the development cycle it should be open to have its own environment with up-to-date dependencies.

Add new conda env: legacy_ogre23

---

jenkins-scripts/lib/colcon-default-devel-windows.bat
jenkins-scripts/lib/windows_env_vars.bat
jenkins-scripts/lib/windows_library.bat

Although disabled by default under the flag `USE_PIXI` the PR adds the following support to main Windows build script:
* :pixi_installation:
*  Download the given version of pixi into the PIXI_TMPDIR
* :pixi_create_gz_environment_legacy
*  Clean up and create a PIXI_PROJECT_PATH (%TMP%\pixi\project"), copy the legacy environment files and run `pixi install`
* :pixi_cmd 
* Wrapper to run pixi commands passed as arguments
* :pixi_load_shell
* Workaround to enable a `pixi shell` like on Jenkins by exporting the results on shell-hook to .bat file and call it.
Tested for PIXI [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_test_gz_rendering_ogre23-pr-cwin&build=34)](https://build.osrfoundation.org/job/_test_gz_rendering_ogre23-pr-cwin/34/)
Tested for current vcpkg: …

Conda environments and pixi support for colcon-default-devel-windows.bat

---

conda/envs/legacy/pixi.lock
conda/envs/legacy/pixi.toml
jenkins-scripts/lib/windows_env_vars.bat

Needed by gazebosim/gz-utils#167.

Add cli11 to VCPKG_DEPENDENCIES_LEGACY and Conda legacy env

---

jenkins-scripts/dsl/gazebo_libs.dsl

The `pr-win` stub jobs should not use testing and cmake warnings.

Disable testing and CMake on pr-win stub

---

.github/workflows/ci-dsl.yaml

Version `v3` of actions/upload-artifact is [no longer working](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/); switch to `v4`.

ci-dsl.yaml: use upload-artifact@v4

---

release.py

There's a conflict in the branch name used by release.py when a package belongs to multiple collections (eg. gz-tools2 is used in Harmonic and Ionic) since it tries to create two PRs with the same branch. See https://github.com/gazebo-release/gz_tools_vendor/pull/5 https://github.com/gazebo-release/gz_tools_vendor/pull/6
This fixes it by adding the base branch name (eg. rolling or jazzy) in the generated branch. See https://github.com/gazebo-release/gz_tools_vendor/pull/7 and https://github.com/gazebo-release/gz_tools_vendor/pull/8

Avoid conflict in branch names used when vendor package PRs

---

jenkins-scripts/docker/lib/_sdformat_version_hook.bash
jenkins-scripts/docker/sdformat-compilation.bash
jenkins-scripts/sdformat-default-devel-windows-amd64.bat

Needed for:
* https://build.osrfoundation.org/job/sdformat-ci-main-noble-amd64/73/
* https://build.osrfoundation.org/job/sdformat-main-clowin/6/console
./scripts/jenkins-scripts/docker/sdformat-compilation.bash and ./scripts/jenkins-scripts/sdformat-default-devel-windows-amd64.bat were removed in #1263

Restore sdformat scripts removed in #1263

---

conda/envs/legacy/pixi.lock
conda/envs/legacy/pixi.toml
conda/envs/legacy_ogre23/pixi.lock
conda/envs/legacy_ogre23/pixi.toml

Related issue: https://github.com/gazebosim/gz-launch/issues/288
Needed by: https://github.com/gazebosim/gz-sim/pull/2792
The pixi files are updated by running `pixi add libwebsockets`

Add libwebsockets dependency to conda

---

jenkins-scripts/lib/colcon-default-devel-windows.bat

I've found some weird reports where the pull request seemed to be used an old version of the code. I found that the clean up of the colcon workspace on Windows was not done in the right way. 
Tested [![Build Status](https://build.osrfoundation.org/job/gz_common-pr-clowin/4/badge/icon)](https://build.osrfoundation.org/job/gz_common-pr-clowin/4/)

Avoid duplicating packages in colcon Windows CI

---

jenkins-scripts/dsl/gazebo_libs.dsl

Some whitespace sneaked in with 87f76ef06 in #1274 and is breaking builds. Removing it fixes the builds.
~~~
for /F %i in ('python "C:\J\workspace\gz_utils-3-clowin\scripts\jenkins-scripts\\tools\detect_cmake_major_version.py" "C:\J\workspace\gz_utils-3-clowin\gz-utils            \CMakeLists.txt"') do set PKG_MAJOR_VERSION=%i  
if errorlevel 1 exit 1  
set GAZEBODISTRO_FILE=gz-utils            !PKG_MAJOR_VERSION!.yaml 
)  else (echo Using user defined GAZEBODISTRO_FILE:  ) 
Traceback (most recent call last):
File "C:\J\workspace\gz_utils-3-clowin\scripts\jenkins-scripts\\tools\detect_cmake_major_version.py", line 11, in <module>
f = open(fileName, 'r')
^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\J\\workspace\\gz_utils-3-clowin\\gz-utils …

gazebo_libs.dsl: fix whitespace breaking builds

---

jenkins-scripts/lib/colcon-default-devel-windows.bat

This will remove the need of Python installed in the base system of Windows agents since the code will use the python installed in the pixi environment.
Testing it here [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_common-pr-clowin&build=8)](https://build.osrfoundation.org/job/gz_common-pr-clowin/8/)

Relocate detect_cmake_major_version to be used after pixi enviroment setuo

---

.github/workflows/ci-pixi.yaml

Answering the security issue https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/.

Replace tj-actions by pure git code

---

jenkins-scripts/dsl/gazebo_libs.dsl

There is a problem with the `-pr-win` old jobs that are now a stub that should return always green. Affecting this: https://github.com/gazebosim/gz-transport/pull/590
The bug is that it only reacts to the branches that are using new `-pr-clowin` that leaves out the good old Fortress (and the previously removed Citadel).
The code is affected since it generates the same job twice, one with the first Windows configuration `-pr-clwin` and the other one with `-pr-clowin` that overrides the first one. This way the fortress branches configuration is being overriding by the rest of the branches configuration.
A nice fix is not trivial to implement but I think that we can force the stub to operate in all branches without bad side effects.

Run the -pr-win stub jobs in all branches

---

jenkins-scripts/lib/windows_library.bat

To activate the pixi enviroment in our Jenkins the best way I found was to use the `shell-hook` command to create a .bat file that we can "call". For doing it the current code uses the `call %win_lib% :pixi_cmd ... > hooks.bat`. This is making that many of the scripts code ended up in the .bat file and it is generating random commands.
The PR changes the call to use directly the pixi executable. This generates a clear execution.

Fix pixi hooks run: do not use call with windows redirection

---

.github/workflows/ci-pixi.yaml
conda/envs/legacy/pixi.toml
setup.cfg

Replace the current code based on push + external github action to use pull_request.
The current detection code should filter the changes without toml files so it can operate on all pull request open. The machinery necessary to make the push event to work properly on github pull request is not trivial (hence the github external action) but I think that we can live with this running only pull requests.
Used for testing in #1286

Replace changed-files action by custom code

---

jenkins-scripts/dsl/_configs_/OSRFBase.groovy

Jobs that fail with error: `Error: Another ``brew update`` process is already running.` (e.g., https://build.osrfoundation.org/job/gz_sensors-ci-ign-sensors6-homebrew-amd64/123/console), can be retriggered safely

Retry jobs failed that have another brew update process

---

jenkins-scripts/dsl/_configs_/OSRFBase.groovy
jenkins-scripts/dsl/dsl_checks.bash
jenkins-scripts/dsl/test.dsl

Just detected that core.dsl jobs run without a limit in the number of builds. Modifying the Base class in DSL so almost all jobs are covered by at least 75 build limit.
Add a check to the CI to avoid next cases in the future.

Do not allow infinite number of builds. Set base at 75 builds

---

jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash

The asan CI builds configured in [gazebo_libs.dsl's generate_asan_ci_job method](https://github.com/gazebo-tooling/release-tools/blob/9b9f9b8550671f095ce89e6b85060e79df40e7c8/jenkins-scripts/dsl/gazebo_libs.dsl#L150C6-L150C26) set the `ASAN_OPTIONS` environment variable on the host machine, but the variable is not passed into the docker container's build script, so it has no effect. This pull request passes it into the generated build.sh script.
To test, I copied  [example code to generate an initialization-order-fiasco bug](https://github.com/google/sanitizers/wiki/AddressSanitizerExampleInitOrderFiasco) into the gz-math Angle_TEST in https://github.com/gazebosim/gz-math/pull/671. I manually reconfigured the [jenkins noble ci-pr_any …

Set ASAN_OPTIONS in build.sh used by docker

---

.github/workflows/ci-pixi.yaml
jenkins-scripts/lib/windows_env_vars.bat

There are problems with the pixi lock format when running modern pixi versions locally. The PR bumps the use of pixi to 0.44.0.

Use new pixi version 0.44.0

---

conda/envs/noble_like/pixi.lock
conda/envs/noble_like/pixi.toml

Added zenoh dependencies by running `pixi add libzenohc libzenohcxx`
Related gz-transport PR: https://github.com/gazebosim/gz-transport/pull/600

Add zenoh dependencies to noble-like conda environment

---

jenkins-scripts/dsl/gazebo_libs.dsl

The `-pr-win` jobs were removed during the transition to Conda. The stub to report green has been running for some weeks now to give time to the PRs to update to the new jobs while not being blocked by previous failures in these -pr-win jobs. Might a be a good time to remove them so they are not reporting useless CI in new builds.

Remove -pr-win stub jobs

---

jenkins-scripts/gz_common-default-devel-windows-amd64.bat
jenkins-scripts/gz_tools-default-devel-windows-amd64.bat
jenkins-scripts/lib/colcon-default-devel-windows.bat
jenkins-scripts/sdformat-default-devel-windows-amd64.bat

When provisioning the new agents for Windows, I think that we can remove the host dependency on Python just by removing some leftovers in the gz_*-default-devel-windows-amd64.bat scripts. The only important piece is ignition-tools from Fortress that implements a logic needed. I moved it to the base lib in c349937d582039c6ae20723d1d7406ef1cb6efbd.
This should leave us with non python base dependency for Agents in buildfarm and user local systems since all the operations with python are done AFTER the pixi environment is created.
Doing some tests in the testing buildarm:
* gz-common6 is fine [![Build Status](https://citest.build.osrfoundation.org/buildStatus/icon?job=gz_common-6-cnlwin&build=3)](https://citest.build.osrfoundation.org/job/gz_common-6-cnlwin/3/)
* ign-tools1 in fortress: …

Remove python calls from gz_*.bat scripts. Move MAJOR_VERSION to use lib/colcon-default-windows.bat

---

jenkins-scripts/dsl/gz-collections.yaml

There are currently no cmake warnings for gz-cmake or gz-utils on brew, so enable checking for these warnings.

brew: check gz-cmake, gz-utils for cmake warnings

---

release.py

Add kilted as a supported ROS 2 distribution linked to Gazebo Ionic.
Needed to change code a little bit to support more than one ROS 2 release per Gazebo collection.
Before using the code, we need to prepare the ROS vendor repositories with a branch named `kilted` or otherwise the script will fail:
```
ROS vendor packages that can be updated:
* Github gazebo-release/gz_transport_vendor part of ionic in ROS 2 kilted
+ Preparing a PR: WARNING: Skipping /usr/lib/python3.12/dist-packages/pybind11-2.11.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib/python3.12/dist-packages/pybind11-2.11.1.dist-info due to invalid metadata entry 'name'
Error running command (git clone -q -b kilted https://github.com/gazebo-release/gz_transport_vendor …
```

Support for ROS 2 Kilted in release.py

---

jenkins-scripts/docker/gz_transport-compilation.bash
jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash

gz-transport15 depends on ros2 repo's `ros-jazzy-zenoh-cpp-vendor` package. We need to source the ros setup.bash script to find this package

Source ros distro setup file if needed

---

jenkins-scripts/docker/lib/_generic_linux_compilation_build.sh.bash

https://github.com/gazebo-tooling/release-tools/pull/1311 made ROS setup a requirement when building gz-transport15. That  's needed for the zenoh work being done in the `zenoh_main` branch in gz-transport. However, we are not ready to merge those changes back to the `main` branch yet so temporarily commenting out the exit logic if ROS is not found. This is so that we can continue building and testing `main` for now.
Test build
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_transport-ci-pr_any-noble-amd64&build=156)](https://build.osrfoundation.org/job/gz_transport-ci-pr_any-noble-amd64/156/)

Do not exit if ROS is not found when building gz-transport15

---

release-repo-scripts/README.md
release-repo-scripts/convert_gazebodistro_to_release_ros_vendor.py

Add an script to get a compatible vcs file for Gazebo ROS vendor repositories with the input of a gazebodistro file.

Include a gazebodistro to vendor repos vcs script

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Should help with the problem described in https://github.com/gazebosim/gz-sim/pull/2910#issuecomment-2896506657
Testing it here [![Build Status](https://build.osrfoundation.org/job/gz_sim-ci-pr_any-noble-amd64/758/badge/icon)](https://build.osrfoundation.org/job/gz_sim-ci-pr_any-noble-amd64/758/)

Run apt-get autoremove in Linux builds

---

.github/workflows/ci-dsl.yaml
jenkins-scripts/dsl/tools/setup_local_generation.bash

This is part of preparations for the 24.04 migration. Closes https://github.com/gazebo-tooling/release-tools/issues/1325.
Mostly resolves the problem of DSL for generation with new versions of Java and new versions of Jenkins. See #1325 for the details and https://github.com/gazebo-tooling/release-tools/pull/1330 for the implementation.

Update DSL generation: modern Jenkins and Java versions

---

jenkins-scripts/docker/lib/docker_generate_dockerfile.bash

Follow up #1319 after https://github.com/gazebosim/gz-sim/pull/2910#issuecomment-2899396935

Run autoremove after dist-upgrade

---

jenkins-scripts/dsl/_configs_/OSRFDslBase.groovy

Jobs are failing in citest because we are passing the file paths as DSL code to the generate dsl job. The PR change it to ~~read from workspace as suggested by the DSL API~~ `external` as suggested by the API.

Fix generate_dsls: use file path not code for filenames

---

jenkins-scripts/dsl/_configs_/GenericMail.groovy

There is a problem with the existing filter for Email that previously filter emails only to the osrfoundation.org emails. The PR removes it completely. To avoid sending emails extensively to all the users participating in PRs I'm also removing the developers from the emailer.

Remove old filter in email and restrict sendTo

---

jenkins-scripts/dsl/gazebo_libs.dsl

We have a problem with -asan- jobs after the 24.04 migration. They seems to be hanging and generate Gigabytes of logs.

Disable ASAN jobs due to huge log produciton and hanging

---

check_releasepy.bash
release.py

As part of implementing a sha256 verification of sources produced by gz-*-source jobs in the gz-*-debbuilders, this PR implements the intermediate step of adding the feature to release.py.
The calling chain is:
```
JOB gz-source -> 
Generates artifact foo.tar.bz
CALLS:
--> JOB repository_uploader_packages 
Upload to S3 the [foo.tar.bz]
--> JOB _release.py
Runs release.py  --source-tarball-uri S3://.../foo.bar.bz ... that end up calling the jobs:
--->JOB gz-*-debbuilder
--->JOB generic-release-homebrew_pull_request_updater
```
There is support to be made for the Jenkins jobs to pass the parameters around but this first PR allows release.py to call jobs with the optional support of sha256.

Implement --source-tarball-sha256 for release.py

---

jenkins-scripts/docker/lib/debbuild-base.bash
jenkins-scripts/dsl/_configs_/OSRFLinuxBuildPkg.groovy
jenkins-scripts/dsl/_configs_/OSRFReleasepy.groovy

The PR complete the sha256 support after #1351 and #1353 .
Two commits to implement:
* _releasepy job support: not optional since it currently only handle the calls using `--source-tarball-uri` (not nightlies) so all the upstream callers can provide sha256.
* The other support is for the `OSRFLinuxBuildPkg.groovy` that creates the -debbuilders. In this case it is optional since it needs to deal nightlies that do not provide a `SOURCE_TARBALL_URI` but builds the sources directly in the same build.

Complete sha256 support in release: _releasepy job and -debbuilders

---

jenkins-scripts/dsl/gazebo_libs.dsl

After reverting a commit in #1357 it was not sufficient to restore all asan builds. Doing so in this PR.

Remove previous lock on -asan- builds

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Part of https://github.com/gazebosim/gz-jetty/issues/24

gz-jetty: Use stable branch for gz-common7

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Part of https://github.com/gazebosim/gz-jetty/issues/22.

jetty: use gz-math9 stable branch

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Part of https://github.com/gazebosim/gz-jetty/issues/29.

jetty: use gz-physics9 stable branch

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Part of https://github.com/gazebosim/gz-jetty/issues/18

Use stable branch for gz-launch9

---

jenkins-scripts/docker/gz_transport-compilation.bash

It was previously added to get `zenoh-cpp-vendor` packages from ROS repo. This is no longer needed as the zenoh packages have been imported to packages.osrfoundation.org. Removing this env will make gz-transport15 use the zenoh packages from packages.osrfoundation.org.
Test build: https://build.osrfoundation.org/job/gz_transport-ci-pr_any-noble-amd64/282/
[![Build Status](https://build.osrfoundation.org/job/gz_transport-ci-pr_any-noble-amd64/282/badge/icon)](https://build.osrfoundation.org/job/gz_transport-ci-pr_any-noble-amd64/280/)
Related PR for github actions: https://github.com/gazebosim/gz-transport/pull/696

Do not setup ROS distro for gz-transport15

---

jenkins-scripts/dsl/gz-collections.yaml
jenkins-scripts/dsl/logs/generated_jobs.txt

Part of https://github.com/gazebosim/gz-jetty/issues/33

gz-jetty: Use stable branch for gz-sim10

---

jenkins-scripts/dsl/brew_release.dsl

Upstream homebrew-core has stopped building new ventura bottles since https://github.com/Homebrew/brew/pull/20672 was merged, so we should stop as well.

brew_release.dsl: stop building ventura bottles

---

jenkins-scripts/docker/lib/docker_run.bash

The support in our arm nodes does not seem to be able to use buildx with --platform probably due to a lack of right buildx plugin installation or a low version of the plugin.  Previous builds of armhf in Jenkins did not use the plugin although the support was there, probably a bug making things to work :roll_eyes: 
I'm removing its usage since the standard builder seems to work fine on arm64 to build armhf. 
Tested a variant of this branch successfully in gz-cmake5 (built the armhf package). Scheduled these same changes in gz-utils4: [![Build Status](https://build.osrfoundation.org/job/gz-utils4-debbuilder/205/badge/icon)](https://build.osrfoundation.org/job/gz-utils4-debbuilder/205/)

Fix armhf calls in docker: remove explict buildx support

---

jenkins-scripts/lib/_homebrew_github_get_formula_path.bash
jenkins-scripts/lib/_homebrew_github_setup.bash
jenkins-scripts/lib/homebrew_bottle_pullrequest.bash
jenkins-scripts/lib/homebrew_formula_pullrequest.bash

Set the `PATH` appropriately and replace usage of BREW variable with brew in `_homebrew_github_setup.bash` and related scripts to match the approach taken for scripts that execute on macOS in https://github.com/gazebo-tooling/release-tools/pull/1366. I attempt to use `_homebrew_path_setup.sh` in https://github.com/gazebo-tooling/release-tools/pull/1392/commits/035cf90e9126ab340b81f0e39de1109bfd194f8c, though it requires checking for the presence of `SCRIPT_LIBDIR` or `SCRIPT_DIR` and includes a fallback.

Add linuxbrew bin to PATH, use brew

---

jenkins-scripts/lib/homebrew_formula_pullrequest.bash

Unset VERSION_LINE variable after deleting a redundant version field to fix the location of sha256 field.
Should fix issue in https://github.com/osrf/homebrew-simulation/pull/3194.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_pull_request_updater&build=1715)](https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/1715/) https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/1715/

Fix brew formula PR field order
